import type { QuizStem } from "../quizData";

export const CA_STEMS: QuizStem[] = [
  {
    id: "CA-001",
    questionNumber: "MEQ-095",
    topic: "child_adolescent",
    difficulty: "consultant",
    title: "Aboriginal adolescent self-harm, family violence and child protection",
    candidateRole: "Consultant child and adolescent psychiatrist, emergency liaison service",
    setting: "Regional emergency department after police and ambulance attendance",
    stem: `You are the consultant child and adolescent psychiatrist contacted by a registrar in a regional ED.

Tahlia is a 14-year-old Aboriginal girl brought in by ambulance after cutting her forearm with glass during an argument at home. She says, "I only cut so Mum would stop yelling." Police attended because neighbours reported screaming. Tahlia says her mother's partner "gets drunk and smashes things" but asks staff, "Don't call child protection because they already took my cousins."

Tahlia's mother is angry and says, "She's attention-seeking and needs to learn consequences." The mother's partner is waiting outside the ED and wants to take them both home. The Aboriginal Liaison Officer is not on site overnight, and ED staff want psychiatry to decide whether Tahlia can be discharged.

The registrar says Tahlia denies current suicidal intent and wants to go home, but nursing staff report she becomes visibly frightened whenever her mother's partner walks past the cubicle.`,
    totalMarks: 22,
    signals: [
      { id: "s1", name: "Glass cutting requires acute self-harm formulation", category: "risk_self", severity: "critical", clueInStem: "Tahlia is a 14-year-old Aboriginal girl brought in by ambulance after cutting her forearm with glass during an argument at home.", whyItMatters: "Missing this signal means the candidate has not assessed method, intent, escalation and immediate safety after adolescent self-harm.", modelWording: "Assess the cutting episode directly because glass self-harm during family conflict may represent acute distress even if suicidal intent is denied.", keywords: ["self-harm", "glass", "adolescent", "intent", "escalation"] },
      { id: "s2", name: "Self-harm function is linked to stopping yelling", category: "diagnosis_formulation", severity: "critical", clueInStem: "She says, \"I only cut so Mum would stop yelling.\"", whyItMatters: "Missing this signal means the candidate has dismissed self-harm as attention-seeking rather than understanding it as communication and affect regulation under threat.", modelWording: "Formulate the function of self-harm because Tahlia is describing cutting as a way to stop overwhelming conflict.", keywords: ["function", "Mum yelling", "affect regulation", "family conflict", "formulation"] },
      { id: "s3", name: "Intoxicated violence at home creates child-safety risk", category: "immediate_safety", severity: "critical", clueInStem: "Tahlia says her mother's partner \"gets drunk and smashes things\" but asks staff, \"Don't call child protection because they already took my cousins.\"", whyItMatters: "Missing this signal means the candidate has planned discharge into a home where intoxication and property violence may continue tonight.", modelWording: "Assess immediate home safety because a drunken adult smashing things creates risk regardless of Tahlia's current suicidal denial.", keywords: ["family violence", "drunk", "smashes things", "home safety", "child safety"] },
      { id: "s4", name: "Child protection fear needs transparent cultural safety", category: "cultural_safety", severity: "important", clueInStem: "Tahlia says her mother's partner \"gets drunk and smashes things\" but asks staff, \"Don't call child protection because they already took my cousins.\"", whyItMatters: "Missing this signal means the candidate may either avoid safeguarding or escalate coercively without acknowledging Aboriginal family trauma around removal.", modelWording: "Explain child-safety duties transparently because Tahlia's fear of child protection must be respected while safeguarding thresholds are assessed.", keywords: ["child protection", "Aboriginal", "cousins", "cultural safety", "transparency"] },
      { id: "s5", name: "Mother's attention-seeking label minimises distress", category: "family_carer", severity: "important", clueInStem: "Tahlia's mother is angry and says, \"She's attention-seeking and needs to learn consequences.\"", whyItMatters: "Missing this signal means the candidate has accepted a rejecting parental explanation that may worsen shame and obscure family violence.", modelWording: "Challenge the attention-seeking frame because it invalidates Tahlia's distress and may increase risk after discharge.", keywords: ["attention-seeking", "mother", "invalidation", "consequences", "carer"] },
      { id: "s6", name: "Mother's partner is not a safe discharge decision-maker", category: "disposition", severity: "critical", clueInStem: "The mother's partner is waiting outside the ED and wants to take them both home.", whyItMatters: "Missing this signal means the candidate has allowed a possible source of threat to control discharge.", modelWording: "Do not discharge Tahlia with the mother's partner until independent safety assessment and a safe care arrangement are confirmed.", keywords: ["mother's partner", "take home", "unsafe discharge", "care arrangement"] },
      { id: "s7", name: "Aboriginal liaison absence should trigger alternative support", category: "system_pressure", severity: "important", clueInStem: "The Aboriginal Liaison Officer is not on site overnight, and ED staff want psychiatry to decide whether Tahlia can be discharged.", whyItMatters: "Missing this signal means the candidate has accepted overnight service limitations instead of seeking culturally safe alternatives.", modelWording: "Seek available Aboriginal health, on-call liaison or trusted kinship support because cultural safety remains required overnight.", keywords: ["Aboriginal Liaison Officer", "overnight", "cultural support", "ED"] },
      { id: "s8", name: "Fear response to partner outweighs simple denial", category: "collateral", severity: "critical", clueInStem: "The registrar says Tahlia denies current suicidal intent and wants to go home, but nursing staff report she becomes visibly frightened whenever her mother's partner walks past the cubicle.", whyItMatters: "Missing this signal means the candidate has over-weighted denial and ignored behavioural evidence of fear around the proposed discharge environment.", modelWording: "Use nursing observation as key collateral because Tahlia's visible fear suggests home may be unsafe despite wanting to leave.", keywords: ["nursing", "frightened", "partner", "collateral", "denies intent"] },
    ],
    priorityOrder: { urgent: ["s1", "s2", "s3", "s6", "s8"], secondary: ["s4", "s5", "s7"], lowYield: [] },
    modelAnswer: `Tahlia's presentation cannot be closed simply because she denies current suicidal intent. She is a 14-year-old Aboriginal girl brought by ambulance after cutting her forearm with glass during an argument at home. Her statement, "I only cut so Mum would stop yelling," means the self-harm needs formulation as distress communication and affect regulation in a frightening family environment.

The home-safety concern is immediate. Tahlia says her mother's partner "gets drunk and smashes things," and nursing staff observe that she becomes visibly frightened whenever he walks past the cubicle. That behavioural observation is powerful collateral and makes discharge with him unsafe until risk is clarified.

The child protection issue must be addressed transparently and culturally safely. Tahlia asks staff not to call child protection because they already took her cousins, which signals fear and possible family/community trauma around removal. I would acknowledge that fear, explain confidentiality limits, seek Aboriginal liaison or alternative Aboriginal health support, and look for safe kinship options where possible.

The mother's description of Tahlia as attention-seeking and needing consequences should not guide the assessment. It may reflect anger or stress, but it invalidates Tahlia's distress and does not answer whether the home is safe. I would interview Tahlia separately, obtain collateral from police, ambulance, nursing staff, school and safe relatives, and clarify who else lives at home.

Disposition must be based on safety, not ED pressure or the partner's wish to leave. If a safe kinship placement or supported plan can be arranged, that may be least restrictive. If home risk remains unresolved, she should remain in a safe setting while child protection, social work and culturally appropriate supports are engaged.`,
  },
  {
    id: "CA-002",
    questionNumber: "MEQ-096",
    topic: "child_adolescent",
    difficulty: "consultant",
    title: "Refugee adolescent school refusal, trauma and consent",
    candidateRole: "Consultant child and adolescent psychiatrist, community CAMHS",
    setting: "CAMHS urgent assessment after school welfare referral",
    stem: `You are the consultant child and adolescent psychiatrist supervising an urgent CAMHS assessment.

Hamid is a 16-year-old Syrian refugee boy referred because he has stopped attending school for six weeks. The school reports panic when fire alarms sound and says he hides under desks. Hamid says through his older brother, who is interpreting, "School is not safe; soldiers come when bells ring." His father insists, "He is lazy and must be forced back."

Hamid refuses trauma therapy and says, "If people know what happened, my family will be ashamed." His mother appears distressed but speaks little English. The GP has prescribed diazepam for sleep, and the school wants a certificate stating he is medically unfit or fit to return.

The registrar asks whether Hamid can consent to therapy without his father's agreement and whether school refusal should be treated as behavioural avoidance.`,
    totalMarks: 22,
    signals: [
      { id: "s1", name: "School refusal is likely trauma-triggered", category: "trauma", severity: "critical", clueInStem: "Hamid is a 16-year-old Syrian refugee boy referred because he has stopped attending school for six weeks.", whyItMatters: "Missing this signal means the candidate has treated prolonged school absence as behavioural avoidance without refugee trauma formulation.", modelWording: "Formulate school refusal through trauma and development because six weeks of absence follows panic and alarm-triggered fear.", keywords: ["school refusal", "trauma", "Syrian refugee", "absence", "PTSD"] },
      { id: "s2", name: "Fire alarms trigger war-related re-experiencing", category: "diagnosis_formulation", severity: "critical", clueInStem: "The school reports panic when fire alarms sound and says he hides under desks.", whyItMatters: "Missing this signal means the candidate has not linked school behaviour to threat physiology and possible PTSD.", modelWording: "Identify fire alarms as trauma triggers because hiding under desks suggests re-experiencing and perceived danger rather than laziness.", keywords: ["fire alarms", "panic", "hides under desks", "PTSD", "trigger"] },
      { id: "s3", name: "Sibling interpreting makes assessment unsafe", category: "cultural_safety", severity: "critical", clueInStem: "Hamid says through his older brother, who is interpreting, \"School is not safe; soldiers come when bells ring.\"", whyItMatters: "Missing this signal means the candidate has accepted a trauma and consent assessment through a family interpreter who may inhibit disclosure.", modelWording: "Use a professional interpreter because trauma, shame, risk and consent cannot be assessed safely through Hamid's brother.", keywords: ["brother interpreting", "professional interpreter", "confidentiality", "trauma disclosure"] },
      { id: "s4", name: "Father's forced-return framing is harmful", category: "family_carer", severity: "important", clueInStem: "His father insists, \"He is lazy and must be forced back.\"", whyItMatters: "Missing this signal means coercion may worsen shame, avoidance and family conflict.", modelWording: "Challenge the lazy-and-forced-back framing because trauma-informed school return needs safety and graded exposure, not punishment.", keywords: ["father", "lazy", "forced back", "coercion", "family"] },
      { id: "s5", name: "Shame blocks trauma disclosure and therapy", category: "cultural_safety", severity: "important", clueInStem: "Hamid refuses trauma therapy and says, \"If people know what happened, my family will be ashamed.\"", whyItMatters: "Missing this signal means the candidate has pushed trauma therapy before addressing shame, control and confidentiality.", modelWording: "Explore shame and confidentiality because engagement may require stabilisation before trauma processing.", keywords: ["shame", "trauma therapy", "family", "confidentiality", "engagement"] },
      { id: "s6", name: "Mother needs interpreter-supported involvement", category: "collateral", severity: "important", clueInStem: "His mother appears distressed but speaks little English.", whyItMatters: "Missing this signal means the candidate has excluded a potentially important caregiver because language support was not arranged.", modelWording: "Involve Hamid's mother with a professional interpreter because her distress and observations may be clinically important.", keywords: ["mother", "little English", "interpreter", "collateral", "caregiver"] },
      { id: "s7", name: "Diazepam is risky for adolescent trauma-related sleep", category: "substance_use", severity: "important", clueInStem: "The GP has prescribed diazepam for sleep, and the school wants a certificate stating he is medically unfit or fit to return.", whyItMatters: "Missing this signal means the candidate has not reviewed a benzodiazepine that may worsen avoidance, dependence and cognition in adolescent PTSD.", modelWording: "Review diazepam with the GP because benzodiazepines are not preferred long-term treatment for adolescent trauma-related insomnia.", keywords: ["diazepam", "sleep", "GP", "benzodiazepine", "adolescent"] },
      { id: "s8", name: "School needs graded return, not binary certificate", category: "system_pressure", severity: "important", clueInStem: "The GP has prescribed diazepam for sleep, and the school wants a certificate stating he is medically unfit or fit to return.", whyItMatters: "Missing this signal means school pressure may produce an over-simple fit-or-unfit decision rather than trauma-informed reintegration.", modelWording: "Recommend a graded school return because binary fit or unfit certification does not address trauma triggers and accommodations.", keywords: ["school certificate", "graded return", "accommodations", "fit or unfit"] },
      { id: "s9", name: "Adolescent consent needs capacity and confidentiality assessment", category: "consent_refusal", severity: "important", clueInStem: "The registrar asks whether Hamid can consent to therapy without his father's agreement and whether school refusal should be treated as behavioural avoidance.", whyItMatters: "Missing this signal means the candidate has not addressed Hamid's evolving autonomy and confidentiality rights at age 16.", modelWording: "Assess Hamid's capacity to consent because a 16-year-old may consent to confidential therapy depending on maturity and jurisdiction.", keywords: ["consent", "16", "confidentiality", "capacity", "therapy"] },
    ],
    priorityOrder: { urgent: ["s1", "s2", "s3"], secondary: ["s4", "s5", "s6", "s7", "s8", "s9"], lowYield: [] },
    modelAnswer: `Hamid's school refusal should be formulated as likely trauma-related rather than laziness or ordinary avoidance. He has stopped attending for six weeks, panics when fire alarms sound and hides under desks. His statement, "School is not safe; soldiers come when bells ring," strongly suggests war-related re-experiencing and threat perception.

The current assessment is not adequate because it is being conducted through his older brother as interpreter. For trauma, shame, risk and consent, a professional interpreter is essential. Hamid may not disclose torture, sexual trauma, family conflict, suicidality or shame through a sibling.

I would challenge the father's statement that Hamid is lazy and must be forced back. Coercive return could worsen symptoms. At the same time, I would not abandon school; the plan should involve stabilisation, psychoeducation, sleep support and a graded school return with alarm accommodations, a safe space, trusted staff and predictable routines.

Hamid's statement that his family will be ashamed means trauma therapy should not be forced prematurely. I would explain confidentiality, assess his capacity to consent to therapy, and consider confidential adolescent treatment depending on jurisdiction. Family involvement may still be useful if negotiated safely and with interpreter support for his mother.

The GP's diazepam prescription should be reviewed because benzodiazepines are not preferred for adolescent PTSD-related insomnia. The school should receive a practical graded-return plan rather than a binary fit or unfit certificate.`,
  },
  {
    id: "CA-003",
    questionNumber: "MEQ-097",
    topic: "child_adolescent",
    difficulty: "consultant",
    title: "Aboriginal boy, disputed ADHD and polypharmacy",
    candidateRole: "Consultant child psychiatrist, neurodevelopmental and trauma clinic",
    setting: "Regional child mental health outpatient clinic",
    stem: `You are the consultant child psychiatrist asked to review Jayden, a 12-year-old Aboriginal boy referred for "severe ADHD not responding to medication."

Jayden is prescribed methylphenidate LA, clonidine at night and risperidone for aggression. His grandmother says, "Every time he gets upset they add another tablet." School reports he runs from class when teachers shout and hides under tables. Jayden says, "I get scared when men yell because it sounds like home."

His mother has intermittent contact and a history of family violence. The paediatrician wants to increase stimulant dose, while the school wants an aide removed because "medication should fix this." No Aboriginal health worker, trauma service or occupational therapist has been involved.

The registrar asks whether this is treatment-resistant ADHD or conduct disorder.`,
    totalMarks: 22,
    signals: [
      { id: "s1", name: "ADHD label needs trauma-informed reformulation", category: "diagnosis_formulation", severity: "critical", clueInStem: "You are the consultant child psychiatrist asked to review Jayden, a 12-year-old Aboriginal boy referred for \"severe ADHD not responding to medication.\"", whyItMatters: "Missing this signal means the candidate has accepted the referral frame without reassessing whether trauma, environment and ADHD are being conflated.", modelWording: "Reformulate beyond severe ADHD because non-response to medication may reflect trauma, school triggers or mis-specified target symptoms.", keywords: ["ADHD", "trauma", "formulation", "non-response", "child psychiatry"] },
      { id: "s2", name: "Polypharmacy has escalated without clear formulation", category: "physical_health", severity: "critical", clueInStem: "Jayden is prescribed methylphenidate LA, clonidine at night and risperidone for aggression.", whyItMatters: "Missing this signal means the candidate has not reviewed adverse effects and rationale for three psychotropics in a 12-year-old.", modelWording: "Review medication rationale and monitoring because stimulant, clonidine and risperidone polypharmacy requires clear targets and safety checks.", keywords: ["methylphenidate", "clonidine", "risperidone", "polypharmacy", "monitoring"] },
      { id: "s3", name: "Grandmother sees medication escalation as distress management", category: "family_carer", severity: "important", clueInStem: "His grandmother says, \"Every time he gets upset they add another tablet.\"", whyItMatters: "Missing this signal means the candidate has ignored the carer's observation that distress is being medicalised without adequate psychosocial care.", modelWording: "Use grandmother's collateral because she identifies a pattern of adding medication whenever Jayden becomes distressed.", keywords: ["grandmother", "tablet", "collateral", "distress", "medicalisation"] },
      { id: "s4", name: "School behaviour follows threat triggers", category: "trauma", severity: "critical", clueInStem: "School reports he runs from class when teachers shout and hides under tables.", whyItMatters: "Missing this signal means the candidate has treated running and hiding as conduct problems rather than threat responses.", modelWording: "Assess school triggers because running from shouting teachers and hiding under tables suggests fear-based behaviour.", keywords: ["school", "teachers shout", "hides", "threat response", "trauma"] },
      { id: "s5", name: "Jayden links yelling men to home fear", category: "trauma", severity: "critical", clueInStem: "Jayden says, \"I get scared when men yell because it sounds like home.\"", whyItMatters: "Missing this signal means the candidate has missed direct evidence that family violence trauma is shaping behaviour.", modelWording: "Centre Jayden's own explanation because fear when men yell points to trauma-related hyperarousal rather than conduct disorder alone.", keywords: ["men yell", "home", "fear", "family violence", "hyperarousal"] },
      { id: "s6", name: "Family violence and contact arrangements need safeguarding review", category: "child_protection", severity: "important", clueInStem: "His mother has intermittent contact and a history of family violence.", whyItMatters: "Missing this signal means ongoing exposure or contact-related triggers may remain unassessed.", modelWording: "Clarify current safety and contact arrangements because family violence history may continue to affect symptoms and safeguarding.", keywords: ["mother", "family violence", "contact", "safeguarding", "safety"] },
      { id: "s7", name: "School wants to remove support based on medication logic", category: "system_pressure", severity: "important", clueInStem: "The paediatrician wants to increase stimulant dose, while the school wants an aide removed because \"medication should fix this.\"", whyItMatters: "Missing this signal means the candidate has allowed school and medication pressure to remove environmental supports before formulation is complete.", modelWording: "Advocate to retain school supports because medication alone will not fix trauma triggers or classroom mismatch.", keywords: ["school aide", "medication should fix", "environmental supports", "stimulant dose"] },
      { id: "s8", name: "Cultural, trauma and occupational supports are absent", category: "cultural_safety", severity: "important", clueInStem: "No Aboriginal health worker, trauma service or occupational therapist has been involved.", whyItMatters: "Missing this signal means the current plan lacks key non-medication supports needed for an Aboriginal child with trauma and sensory-regulation concerns.", modelWording: "Involve Aboriginal health, trauma and occupational therapy supports because culturally safe formulation requires more than medication adjustment.", keywords: ["Aboriginal health worker", "trauma service", "occupational therapist", "cultural safety"] },
      { id: "s9", name: "Registrar's differential is too narrow", category: "governance", severity: "important", clueInStem: "The registrar asks whether this is treatment-resistant ADHD or conduct disorder.", whyItMatters: "Missing this signal means the candidate has accepted a false binary and missed trauma, cultural context, school environment and neurodevelopmental complexity.", modelWording: "Teach the registrar to avoid the ADHD-versus-conduct binary because Jayden needs an integrated trauma, neurodevelopmental and cultural formulation.", keywords: ["registrar", "treatment-resistant ADHD", "conduct disorder", "false binary", "supervision"] },
    ],
    priorityOrder: { urgent: ["s1", "s2", "s4", "s5"], secondary: ["s3", "s6", "s7", "s8", "s9"], lowYield: [] },
    modelAnswer: `Jayden's presentation should not be reduced to treatment-resistant ADHD or conduct disorder. He is a 12-year-old Aboriginal boy whose school behaviour occurs when teachers shout, and he says, "I get scared when men yell because it sounds like home." That is direct evidence of threat response and trauma-related hyperarousal.

Medication safety is a major issue. Jayden is taking methylphenidate LA, clonidine and risperidone, and his grandmother says, "Every time he gets upset they add another tablet." I would review target symptoms, benefits, side effects, growth, appetite, sleep, cardiovascular observations, sedation, extrapyramidal effects and metabolic monitoring before any stimulant increase.

The school plan is also unsafe if it removes support because medication should fix the problem. Running from class and hiding under tables may be fear-based behaviour, so he needs trauma-informed classroom adjustments, predictable routines, avoidance of shouting, safe exit strategies, sensory assessment and appropriate aide support.

Cultural safety and family context are central. No Aboriginal health worker, trauma service or occupational therapist has been involved. I would involve those supports, obtain detailed collateral from grandmother, and clarify current contact with mother and whether family violence exposure continues.

I would teach the registrar that the question is not simply ADHD versus conduct disorder. ADHD may be present, but the defensible formulation must integrate trauma, neurodevelopment, medication effects, family violence, school environment, culture and safeguarding.`,
  },
  {
    id: "CA-004",
    questionNumber: "MEQ-098",
    topic: "child_adolescent",
    difficulty: "consultant",
    title: "Adolescent anorexia, medical risk and involuntary treatment",
    candidateRole: "Consultant child and adolescent psychiatrist, eating disorders liaison",
    setting: "Paediatric ward in tertiary hospital",
    stem: `You are the consultant child and adolescent psychiatrist reviewing Sophie, a 15-year-old girl admitted under paediatrics with anorexia nervosa.

Sophie has a heart rate of 38 overnight, postural hypotension and hypokalaemia. She says, "I know I might die, but gaining weight would be worse." Her father says hospital is "making her dramatic" and wants discharge to a private dietitian. Her mother is tearful and says, "I can't keep her alive at home."

Sophie refuses nasogastric feeding and says she will run away if forced. The paediatric consultant says she is medically unstable and asks whether psychiatry can authorise involuntary treatment. The family are from a close religious community and fear "everyone will know she is mentally ill."`,
    totalMarks: 22,
    signals: [
      { id: "s1", name: "Severe vital-sign and electrolyte abnormalities are life-threatening", category: "physical_health", severity: "critical", clueInStem: "Sophie has a heart rate of 38 overnight, postural hypotension and hypokalaemia.", whyItMatters: "Missing this signal means the candidate has not recognised immediate risk of arrhythmia, collapse and death.", modelWording: "Treat this as medical instability because bradycardia, postural hypotension and hypokalaemia require paediatric-led stabilisation.", keywords: ["heart rate 38", "hypokalaemia", "postural hypotension", "medical instability"] },
      { id: "s2", name: "Anorexic weighing may impair capacity", category: "capacity", severity: "critical", clueInStem: "She says, \"I know I might die, but gaining weight would be worse.\"", whyItMatters: "Missing this signal means the candidate has mistaken verbal understanding of death risk for capacity despite pathological weighting of weight gain.", modelWording: "Assess capacity to refuse nutrition because anorexic cognition may impair appreciation and weighing of death versus weight gain.", keywords: ["capacity", "weighing", "death", "weight gain", "anorexia"] },
      { id: "s3", name: "Father's discharge pressure minimises medical risk", category: "family_carer", severity: "important", clueInStem: "Her father says hospital is \"making her dramatic\" and wants discharge to a private dietitian.", whyItMatters: "Missing this signal means the candidate has allowed parental minimisation to support unsafe discharge.", modelWording: "Address the father's minimisation because private dietitian follow-up is unsafe while Sophie is medically unstable.", keywords: ["father", "dramatic", "private dietitian", "discharge pressure"] },
      { id: "s4", name: "Mother states home care cannot keep Sophie alive", category: "family_carer", severity: "critical", clueInStem: "Her mother is tearful and says, \"I can't keep her alive at home.\"", whyItMatters: "Missing this signal means the candidate has ignored carer evidence that discharge home is not safe.", modelWording: "Use the mother's statement as safety collateral because home management has failed and inpatient stabilisation is needed.", keywords: ["mother", "can't keep alive", "home", "carer", "safety"] },
      { id: "s5", name: "Nasogastric feeding refusal may require lawful treatment", category: "consent_refusal", severity: "critical", clueInStem: "Sophie refuses nasogastric feeding and says she will run away if forced.", whyItMatters: "Missing this signal means the candidate has not planned for life-saving feeding refusal and absconding risk.", modelWording: "Plan lawful nutrition and absconding precautions because refusal and running away could be fatal during medical instability.", keywords: ["nasogastric feeding", "refuses", "run away", "feeding", "absconding"] },
      { id: "s6", name: "Legal authority must be clarified with paediatrics", category: "mental_health_act", severity: "critical", clueInStem: "The paediatric consultant says she is medically unstable and asks whether psychiatry can authorise involuntary treatment.", whyItMatters: "Missing this signal means the candidate has given vague authority for coercive treatment without identifying the correct legal pathway.", modelWording: "Clarify the legal pathway because involuntary feeding may require emergency, parental, guardianship or Mental Health Act authority depending on jurisdiction.", keywords: ["paediatric consultant", "involuntary treatment", "legal authority", "MHA"] },
      { id: "s7", name: "Religious community stigma may drive secrecy", category: "cultural_safety", severity: "important", clueInStem: "The family are from a close religious community and fear \"everyone will know she is mentally ill.\"", whyItMatters: "Missing this signal means the candidate has not addressed shame and confidentiality concerns that may drive premature discharge.", modelWording: "Address stigma and confidentiality because community shame must not prevent life-saving treatment.", keywords: ["religious community", "everyone will know", "stigma", "confidentiality"] },
    ],
    priorityOrder: { urgent: ["s1", "s2", "s4", "s5", "s6"], secondary: ["s3", "s7"], lowYield: [] },
    modelAnswer: `Sophie's presentation is a medical emergency. A heart rate of 38 overnight, postural hypotension and hypokalaemia create risk of arrhythmia, collapse and death. The immediate plan must be paediatric-led medical stabilisation, cardiac monitoring, electrolyte correction and specialist eating-disorder care.

Capacity cannot be inferred from Sophie saying she knows she might die. Her statement, "I know I might die, but gaining weight would be worse," suggests anorexic cognition may be impairing her ability to weigh information. I would assess capacity specifically for refusal of nutrition, monitoring and admission.

Family dynamics are clinically important. Her father minimises the hospital response and wants discharge to a private dietitian, while her mother says, "I can't keep her alive at home." The mother's statement confirms home care is unsafe. I would hold a family meeting and explain the objective medical risk.

Sophie's refusal of nasogastric feeding and threat to run away require a lawful and proportionate plan. The paediatric consultant is right that she is medically unstable, but psychiatry should not vaguely authorise treatment; we should clarify whether emergency treatment, parental consent, guardianship or Mental Health Act authority applies.

The family's religious community concerns should be addressed respectfully with reassurance about confidentiality, but fear that others will know she is mentally ill cannot determine life-saving care. Documentation should cover medical instability, capacity reasoning, legal authority, family discussion, absconding precautions and the least restrictive plan.`,
  },
  {
    id: "CA-005",
    questionNumber: "MEQ-099",
    topic: "child_adolescent",
    difficulty: "consultant",
    title: "Gender-diverse youth, depression, parental rejection and MHA",
    candidateRole: "Consultant child and adolescent psychiatrist, crisis team",
    setting: "Metropolitan emergency department mental health assessment room",
    stem: `You are the consultant child and adolescent psychiatrist supervising a crisis assessment.

Alex is a 17-year-old gender-diverse young person brought to ED by a friend after sending a message saying, "I can't survive another night in that house." Alex reports worsening depression, self-harm and suicidal thoughts after their father said, "You are not my child if you keep this gender nonsense going." Alex asks staff to use they/them pronouns and not call their parents.

Alex's mother arrives distressed and says, "This is just internet influence; we want to take her home." Alex says there are tablets hidden in their bedroom and refuses admission because "hospital will just call my parents and make it worse." The ED is busy and the registrar asks whether Alex can be discharged to their parents because they are almost 18 but still a minor.

The family are active in a local faith community, and Alex fears being outed publicly.`,
    totalMarks: 22,
    signals: [
      { id: "s1", name: "Message indicates acute home-linked suicide risk", category: "risk_self", severity: "critical", clueInStem: "Alex is a 17-year-old gender-diverse young person brought to ED by a friend after sending a message saying, \"I can't survive another night in that house.\"", whyItMatters: "Missing this signal means the candidate has not recognised a direct statement that home is part of the suicide-risk pathway.", modelWording: "Assess acute suicide risk because Alex directly links survival tonight to not returning home.", keywords: ["can't survive", "home", "suicide risk", "gender-diverse", "ED"] },
      { id: "s2", name: "Parental rejection is driving depression and self-harm", category: "diagnosis_formulation", severity: "critical", clueInStem: "Alex reports worsening depression, self-harm and suicidal thoughts after their father said, \"You are not my child if you keep this gender nonsense going.\"", whyItMatters: "Missing this signal means the candidate has not linked family rejection and minority stress to current risk.", modelWording: "Formulate parental rejection as a dynamic risk factor because it is directly associated with worsening depression, self-harm and suicidal thoughts.", keywords: ["father", "not my child", "gender nonsense", "self-harm", "minority stress"] },
      { id: "s3", name: "Pronoun use is part of safe engagement", category: "cultural_safety", severity: "important", clueInStem: "Alex asks staff to use they/them pronouns and not call their parents.", whyItMatters: "Missing this signal means the candidate may worsen distress and disengagement by invalidating Alex's identity.", modelWording: "Use Alex's they/them pronouns consistently because gender-affirming engagement supports assessment and safety.", keywords: ["they/them", "pronouns", "gender-affirming", "engagement"] },
      { id: "s4", name: "Confidentiality request needs safety-limited explanation", category: "consent_refusal", severity: "important", clueInStem: "Alex asks staff to use they/them pronouns and not call their parents.", whyItMatters: "Missing this signal means the candidate has either ignored Alex's confidentiality or promised secrecy despite acute risk.", modelWording: "Explain confidentiality limits because a 17-year-old may have privacy rights but serious risk may require limited disclosure.", keywords: ["not call parents", "confidentiality", "minor", "17", "safety"] },
      { id: "s5", name: "Mother misgenders and minimises the risk", category: "family_carer", severity: "important", clueInStem: "Alex's mother arrives distressed and says, \"This is just internet influence; we want to take her home.\"", whyItMatters: "Missing this signal means the candidate has accepted parental attendance as safety despite invalidation and minimisation.", modelWording: "Assess whether either parent can provide safe care because the mother's response minimises Alex's gender identity and risk.", keywords: ["mother", "internet influence", "take home", "misgendering", "minimisation"] },
      { id: "s6", name: "Hidden tablets create immediate means risk", category: "immediate_safety", severity: "critical", clueInStem: "Alex says there are tablets hidden in their bedroom and refuses admission because \"hospital will just call my parents and make it worse.\"", whyItMatters: "Missing this signal means the candidate has not addressed available means in the location Alex fears returning to.", modelWording: "Remove or secure tablets before any discharge because hidden medication in the bedroom creates immediate overdose risk.", keywords: ["tablets", "bedroom", "means restriction", "overdose", "admission refusal"] },
      { id: "s7", name: "Admission refusal is driven by fear of parental escalation", category: "mental_health_act", severity: "important", clueInStem: "Alex says there are tablets hidden in their bedroom and refuses admission because \"hospital will just call my parents and make it worse.\"", whyItMatters: "Missing this signal means the candidate has treated refusal as simple non-cooperation rather than fear of confidentiality breach and worsening home risk.", modelWording: "Try voluntary care with confidentiality protections first because Alex's admission refusal is linked to fear that parents will worsen risk.", keywords: ["refuses admission", "parents", "make it worse", "voluntary care", "MHA"] },
      { id: "s8", name: "Minor status does not make parents automatically safe", category: "disposition", severity: "critical", clueInStem: "The ED is busy and the registrar asks whether Alex can be discharged to their parents because they are almost 18 but still a minor.", whyItMatters: "Missing this signal means the candidate has allowed legal simplification and ED pressure to override individual home-safety assessment.", modelWording: "Do not discharge to parents solely because Alex is a minor because the home environment appears central to current risk.", keywords: ["minor", "parents", "discharge", "ED busy", "home safety"] },
      { id: "s9", name: "Outing risk requires privacy protection", category: "ethics", severity: "important", clueInStem: "The family are active in a local faith community, and Alex fears being outed publicly.", whyItMatters: "Missing this signal means unnecessary disclosure could increase shame, rejection and suicide risk.", modelWording: "Protect Alex from unnecessary outing because faith-community exposure may intensify rejection and harm.", keywords: ["outed", "faith community", "privacy", "stigma", "gender identity"] },
    ],
    priorityOrder: { urgent: ["s1", "s2", "s6", "s8"], secondary: ["s3", "s4", "s5", "s7", "s9"], lowYield: [] },
    modelAnswer: `Alex is at acute suicide risk in the context of family rejection and an unsafe home environment. The message, "I can't survive another night in that house," should be taken literally as a risk signal, especially with worsening depression, self-harm, suicidal thoughts and tablets hidden in the bedroom.

Respecting Alex's identity is part of clinical safety. Staff should use they/them pronouns consistently. The father's statement that Alex is not his child if they continue with gender identity, and the mother's statement that this is internet influence, are not neutral parental views; they are dynamic risk factors.

Confidentiality needs careful explanation because Alex is 17. I would assess capacity and privacy rights, explain the limits of confidentiality in serious risk, and involve parents or others only to the extent necessary for safety. I would avoid unnecessary outing, especially given the faith-community context and Alex's fear of public disclosure.

Discharge to parents cannot be assumed safe just because Alex is still a minor. Before any discharge, tablets must be removed or secured, a safe adult or alternative accommodation identified, and a clear crisis plan arranged. The friend, youth crisis services, CAMHS crisis team, social work and LGBTQIA+ affirming supports may be more protective than immediate return home.

If Alex refuses admission because hospital will call their parents and make things worse, I would first try to make voluntary care safer through confidentiality protections and clear communication. If acute risk remains high and no safe plan is possible, involuntary assessment may be needed under the relevant law, using the least restrictive option that genuinely protects Alex.`,
  },
];
