import type { QuizStem } from "../quizData";

export const CL_STEMS: QuizStem[] = [
  {
    id: "CL-001",
    questionNumber: "MEQ-115",
    topic: "cl_psychiatry",
    difficulty: "consultant",
    title: "Afghan refugee refusing cardiac surgery",
    candidateRole: "Consultant psychiatrist, consultation-liaison service",
    setting: "Cardiothoracic ward in tertiary hospital",
    stem: `You are the consultant psychiatrist asked to assess Adil, a 35-year-old Afghan refugee with infective endocarditis requiring urgent valve surgery.

Adil refuses surgery and says in limited English, "Hospital papers go to immigration; surgery is a trap." The surgical registrar has been using Adil's cousin as interpreter because "professional interpreters take too long." Adil becomes visibly distressed when security stand near his bed.

His cousin says Adil was detained offshore for months and avoids government offices. Adil says, "Maybe Allah has decided my time." The cardiothoracic team says he may die without surgery but wants psychiatry to determine whether refusal is capacitous.`,
    totalMarks: 22,
    signals: [
      { id: "s1", name: "Urgent endocarditis surgery makes refusal high stakes", category: "physical_health", severity: "critical", clueInStem: "You are the consultant psychiatrist asked to assess Adil, a 35-year-old Afghan refugee with infective endocarditis requiring urgent valve surgery.", whyItMatters: "Missing this signal means the candidate has not recognised that the capacity assessment concerns potentially life-saving cardiac surgery.", modelWording: "Clarify the medical urgency because infective endocarditis requiring urgent valve surgery makes the refusal high stakes.", keywords: ["endocarditis", "valve surgery", "urgent", "capacity"] },
      { id: "s2", name: "Immigration fear may be trauma-related or psychotic", category: "trauma", severity: "critical", clueInStem: "Adil refuses surgery and says in limited English, \"Hospital papers go to immigration; surgery is a trap.\"", whyItMatters: "Missing this signal means mistrust is treated as simple incapacity or refusal rather than formulated in context.", modelWording: "Formulate immigration fear carefully because it may reflect refugee trauma, misunderstanding, delirium or psychosis.", keywords: ["immigration", "trap", "trauma", "refugee"] },
      { id: "s3", name: "Cousin interpreting makes capacity assessment unsafe", category: "cultural_safety", severity: "critical", clueInStem: "The surgical registrar has been using Adil's cousin as interpreter because \"professional interpreters take too long.\"", whyItMatters: "Missing this signal means a high-stakes refusal may be assessed through an unreliable and conflicted communication process.", modelWording: "Use a professional interpreter because family interpretation is unsafe for surgery consent, capacity and trauma disclosure.", keywords: ["cousin", "professional interpreter", "capacity"] },
      { id: "s4", name: "Security presence is worsening distress", category: "immediate_safety", severity: "important", clueInStem: "Adil becomes visibly distressed when security stand near his bed.", whyItMatters: "Missing this signal means visible coercion may intensify trauma and worsen refusal.", modelWording: "Minimise visible security where safe because security near the bed may re-traumatise Adil and impair engagement.", keywords: ["security", "distressed", "coercion"] },
      { id: "s5", name: "Offshore detention explains authority avoidance", category: "collateral", severity: "important", clueInStem: "His cousin says Adil was detained offshore for months and avoids government offices.", whyItMatters: "Missing this signal means key collateral explaining hospital paperwork fear is ignored.", modelWording: "Use detention history to guide trauma-informed explanation because authority avoidance may be understandable and modifiable.", keywords: ["detained offshore", "government offices", "collateral"] },
      { id: "s6", name: "Religious explanation needs respectful exploration", category: "cultural_safety", severity: "important", clueInStem: "Adil says, \"Maybe Allah has decided my time.\"", whyItMatters: "Missing this signal means faith-based meaning may be dismissed or mistaken for incapacity without exploration.", modelWording: "Explore Islamic spiritual meaning respectfully because acceptance of death may be values-based, demoralised or illness-driven.", keywords: ["Allah", "faith", "spiritual", "death"] },
      { id: "s7", name: "Capacity must follow valid communication", category: "capacity", severity: "critical", clueInStem: "The cardiothoracic team says he may die without surgery but wants psychiatry to determine whether refusal is capacitous.", whyItMatters: "Missing this signal means psychiatry may provide a yes-or-no capacity opinion before communication, trauma and medical information are adequate.", modelWording: "Assess decision-specific capacity only after valid interpretation, medical explanation and trauma-informed engagement.", keywords: ["capacity", "may die", "cardiothoracic", "refusal"] },
      { id: "s8", name: "Legal pathway depends on urgency and capacity", category: "consent_refusal", severity: "important", clueInStem: "The cardiothoracic team says he may die without surgery but wants psychiatry to determine whether refusal is capacitous.", whyItMatters: "Missing this signal means the team may delay life-saving treatment or override refusal without lawful basis.", modelWording: "Clarify lawful options because capacitous refusal must be respected, while incapacity plus urgency may require emergency or substitute decision pathways.", keywords: ["legal pathway", "emergency", "substitute decision"] },
    ],
    priorityOrder: { urgent: ["s1", "s2", "s3", "s7"], secondary: ["s4", "s5", "s6", "s8"], lowYield: [] },
    modelAnswer: `Adil's refusal cannot be assessed safely until communication is corrected. He is an Afghan refugee with infective endocarditis requiring urgent valve surgery, and the cardiothoracic team says he may die without surgery. This is a high-stakes decision that requires a valid, decision-specific capacity assessment.

The current interpretation process is unsafe. The registrar has used Adil's cousin because professional interpreters take too long, but family interpretation is not adequate for complex surgery, trauma, immigration fear and capacity. I would arrange a professional interpreter urgently by phone or video if necessary.

His statement that hospital papers go to immigration and surgery is a trap should be formulated in context. His cousin says he was detained offshore and avoids government offices, so mistrust may be trauma-related and potentially modifiable through explanation. It could also reflect psychosis, delirium or misunderstanding, so I would not assume either capacity or incapacity.

The ward environment should be made less coercive. Adil becomes distressed when security stand near his bed, so visible security should be reduced where safe. His statement that Allah may have decided his time should be explored respectfully, with spiritual support offered if he wants it.

If, after valid interpretation and explanation, Adil understands, appreciates and weighs the risks, he may refuse even life-saving surgery. If he lacks capacity and delay threatens life, the team needs the appropriate emergency or substitute decision pathway. My documentation would cover interpreter use, trauma formulation, surgical urgency, capacity reasoning, spiritual discussion, security minimisation and the legal basis for the final plan.`,
  },
  {
    id: "CL-002",
    questionNumber: "MEQ-116",
    topic: "cl_psychiatry",
    difficulty: "consultant",
    title: "Delirium missed as dementia on medical ward",
    candidateRole: "Consultant psychiatrist, consultation-liaison service",
    setting: "Medical ward in metropolitan hospital",
    stem: `You are the CL psychiatrist asked to review Mrs Wilson, an 84-year-old woman admitted after a fall.

The medical team says she has "progressive dementia" because she is confused, hallucinating and trying to climb out of bed. Her son says, "Mum was doing crosswords and paying bills three days ago." The chart includes oxybutynin, codeine, temazepam and promethazine. She has a urinary tract infection and sodium of 126.

Nurses have placed the bed rails up and requested haloperidol because "she is impossible to manage." Mrs Wilson is hard of hearing and her hearing aids are in a drawer. Her daughter asks why psychiatry is involved when "this is just old age."`,
    totalMarks: 22,
    signals: [
      { id: "s1", name: "Fall admission creates delirium-risk context", category: "physical_health", severity: "important", clueInStem: "You are the CL psychiatrist asked to review Mrs Wilson, an 84-year-old woman admitted after a fall.", whyItMatters: "Missing this signal means the acute medical context of confusion is overlooked.", modelWording: "Treat the fall as part of an acute delirium-risk presentation because older patients often present with falls from medical illness or medication toxicity.", keywords: ["fall", "older adult", "delirium"] },
      { id: "s2", name: "Progressive dementia label is contradicted by acute symptoms", category: "diagnosis_formulation", severity: "critical", clueInStem: "The medical team says she has \"progressive dementia\" because she is confused, hallucinating and trying to climb out of bed.", whyItMatters: "Missing this signal means an acute reversible brain syndrome may be mislabelled as chronic dementia.", modelWording: "Challenge the progressive dementia label because acute confusion, hallucinations and climbing behaviour require delirium assessment.", keywords: ["progressive dementia", "confused", "hallucinating"] },
      { id: "s3", name: "Recent independent baseline supports delirium", category: "collateral", severity: "critical", clueInStem: "Her son says, \"Mum was doing crosswords and paying bills three days ago.\"", whyItMatters: "Missing this signal means the strongest evidence of acute change is not used.", modelWording: "Use the son's collateral because crosswords and bill-paying three days ago strongly support delirium over dementia progression.", keywords: ["crosswords", "bills", "three days", "baseline"] },
      { id: "s4", name: "Medication chart contains deliriogenic drugs", category: "physical_health", severity: "critical", clueInStem: "The chart includes oxybutynin, codeine, temazepam and promethazine.", whyItMatters: "Missing this signal means anticholinergic, opioid and sedative burden remains untreated.", modelWording: "Review and rationalise deliriogenic medicines because oxybutynin, codeine, temazepam and promethazine can worsen delirium and falls.", keywords: ["oxybutynin", "codeine", "temazepam", "promethazine"] },
      { id: "s5", name: "UTI and hyponatraemia are treatable precipitants", category: "physical_health", severity: "critical", clueInStem: "She has a urinary tract infection and sodium of 126.", whyItMatters: "Missing this signal means reversible medical precipitants are not prioritised.", modelWording: "Prioritise treatment of UTI and hyponatraemia because these are direct delirium precipitants.", keywords: ["UTI", "sodium 126", "hyponatraemia"] },
      { id: "s6", name: "Bed rails may function as restraint", category: "ethics", severity: "important", clueInStem: "Nurses have placed the bed rails up and requested haloperidol because \"she is impossible to manage.\"", whyItMatters: "Missing this signal means restrictive interventions may increase injury, agitation and loss of dignity.", modelWording: "Review bed rails as restraint because least restrictive falls and delirium care should be used first.", keywords: ["bed rails", "restraint", "least restrictive"] },
      { id: "s7", name: "Haloperidol request is behaviour-control framing", category: "consent_refusal", severity: "important", clueInStem: "Nurses have placed the bed rails up and requested haloperidol because \"she is impossible to manage.\"", whyItMatters: "Missing this signal means antipsychotic medication may be used for manageability rather than severe distress or safety risk.", modelWording: "Use haloperidol only cautiously if severe distress or immediate risk persists because 'impossible to manage' is not a medication indication.", keywords: ["haloperidol", "impossible to manage", "antipsychotic"] },
      { id: "s8", name: "Hearing aids in drawer worsen confusion", category: "immediate_safety", severity: "important", clueInStem: "Mrs Wilson is hard of hearing and her hearing aids are in a drawer.", whyItMatters: "Missing this signal means a simple sensory intervention that can reduce delirium distress is missed.", modelWording: "Restore hearing aids immediately because sensory deprivation worsens confusion, fear and hallucination-like experiences.", keywords: ["hearing aids", "hard of hearing", "sensory"] },
      { id: "s9", name: "Family needs education that delirium is not old age", category: "family_carer", severity: "important", clueInStem: "Her daughter asks why psychiatry is involved when \"this is just old age.\"", whyItMatters: "Missing this signal means family misunderstanding may reinforce ageist minimisation and delay delirium treatment.", modelWording: "Explain delirium as acute medical brain dysfunction because it is not normal ageing and may be reversible.", keywords: ["old age", "family education", "delirium"] },
    ],
    priorityOrder: { urgent: ["s2", "s3", "s4", "s5"], secondary: ["s1", "s6", "s7", "s8", "s9"], lowYield: [] },
    modelAnswer: `Mrs Wilson's presentation is delirium until proven otherwise, not progressive dementia. She was admitted after a fall and is now confused, hallucinating and trying to climb out of bed. Her son's statement that she was doing crosswords and paying bills three days ago is the clearest evidence of acute change.

The medical precipitants are substantial. She has a urinary tract infection and sodium of 126, both of which can precipitate delirium. Her medication chart also includes oxybutynin, codeine, temazepam and promethazine, which add anticholinergic, opioid and sedative burden. I would work with the medical team to treat infection, correct hyponatraemia and rationalise deliriogenic medication.

The ward response needs to move from containment to delirium care. Bed rails can function as restraint and may increase injury if she climbs over them. Haloperidol requested because she is impossible to manage should be reframed; antipsychotic use should be reserved for severe distress or immediate safety risk after non-pharmacological measures and cause treatment.

A simple but important intervention is to restore her hearing aids, which are in a drawer. Sensory deprivation can worsen confusion, fear and misinterpretation. Delirium care should include reorientation, family presence, hydration, mobilisation, sleep-wake support, toileting, pain relief and close observation.

Her daughter's statement that this is just old age is an opportunity for education. I would explain that delirium is an acute medical brain syndrome, often reversible, and that psychiatry is involved to help identify causes, reduce restraint and avoid harmful sedation.`,
  },
  {
    id: "CL-003",
    questionNumber: "MEQ-117",
    topic: "cl_psychiatry",
    difficulty: "consultant",
    title: "Chronic pain, opioid dependence and staff conflict",
    candidateRole: "Consultant psychiatrist, consultation-liaison pain psychiatry",
    setting: "Surgical ward after repeated admissions for abdominal pain",
    stem: `You are the CL psychiatrist asked to review Rosa, a 39-year-old woman admitted with severe abdominal pain after multiple negative investigations.

Rosa says, "No one believes me because I have trauma and take opioids." She is prescribed high-dose oxycodone and asks for IV fentanyl. The surgical registrar says, "This is functional; she is manipulating us." The pain team says opioid-induced hyperalgesia is likely.

Rosa has a history of childhood sexual abuse and becomes distressed when male staff examine her. Her partner says, "If you discharge her without pain relief she will buy tablets on the street." Nursing staff are split between giving extra opioids and refusing all PRN medication.`,
    totalMarks: 22,
    signals: [
      { id: "s1", name: "Pain must be validated despite negative investigations", category: "diagnosis_formulation", severity: "critical", clueInStem: "You are the CL psychiatrist asked to review Rosa, a 39-year-old woman admitted with severe abdominal pain after multiple negative investigations.", whyItMatters: "Missing this signal means negative investigations are treated as proof of fabrication rather than part of a functional and pain formulation.", modelWording: "Validate Rosa's pain while formulating functional pain mechanisms because negative investigations do not mean the pain is not real.", keywords: ["pain", "negative investigations", "functional", "validation"] },
      { id: "s2", name: "Trauma and opioid stigma are damaging engagement", category: "trauma", severity: "important", clueInStem: "Rosa says, \"No one believes me because I have trauma and take opioids.\"", whyItMatters: "Missing this signal means the team may repeat invalidation that worsens distress and conflict.", modelWording: "Acknowledge Rosa's fear of disbelief because trauma and opioid stigma are shaping the therapeutic relationship.", keywords: ["trauma", "opioids", "not believed", "engagement"] },
      { id: "s3", name: "High-dose oxycodone and IV fentanyl request need addiction-pain plan", category: "substance_use", severity: "critical", clueInStem: "She is prescribed high-dose oxycodone and asks for IV fentanyl.", whyItMatters: "Missing this signal means opioid escalation may worsen dependence, sedation and pain sensitivity.", modelWording: "Avoid unstructured opioid escalation because high-dose oxycodone plus IV fentanyl requests require a coordinated pain and addiction plan.", keywords: ["oxycodone", "IV fentanyl", "opioid escalation"] },
      { id: "s4", name: "Manipulation label is stigmatising and unsafe", category: "mdt_conflict", severity: "important", clueInStem: "The surgical registrar says, \"This is functional; she is manipulating us.\"", whyItMatters: "Missing this signal means functional symptoms are misrepresented as deliberate deception.", modelWording: "Challenge the manipulation label because functional pain and opioid dependence need consistent care, not punitive language.", keywords: ["manipulating", "functional", "stigma"] },
      { id: "s5", name: "Opioid-induced hyperalgesia is a plausible mechanism", category: "physical_health", severity: "important", clueInStem: "The pain team says opioid-induced hyperalgesia is likely.", whyItMatters: "Missing this signal means ongoing opioid escalation may worsen the very pain being treated.", modelWording: "Integrate the pain team's hyperalgesia formulation because escalating opioids may worsen pain sensitivity.", keywords: ["hyperalgesia", "pain team", "opioids"] },
      { id: "s6", name: "Male examinations trigger trauma distress", category: "trauma", severity: "important", clueInStem: "Rosa has a history of childhood sexual abuse and becomes distressed when male staff examine her.", whyItMatters: "Missing this signal means necessary care may re-traumatise Rosa and intensify pain or refusal.", modelWording: "Use trauma-informed examination because male staff examinations are distressing in the context of childhood sexual abuse.", keywords: ["childhood sexual abuse", "male staff", "examine"] },
      { id: "s7", name: "Street tablet risk requires harm reduction", category: "risk_self", severity: "critical", clueInStem: "Her partner says, \"If you discharge her without pain relief she will buy tablets on the street.\"", whyItMatters: "Missing this signal means discharge may create illicit opioid use and overdose risk.", modelWording: "Plan harm reduction before discharge because buying street tablets creates overdose and contamination risk.", keywords: ["street tablets", "discharge", "overdose", "harm reduction"] },
      { id: "s8", name: "Nursing split requires one consistent plan", category: "governance", severity: "important", clueInStem: "Nursing staff are split between giving extra opioids and refusing all PRN medication.", whyItMatters: "Missing this signal means ward inconsistency will escalate conflict, unsafe prescribing and mistrust.", modelWording: "Create one MDT analgesia plan because inconsistent PRN decisions are unsafe and relationally destabilising.", keywords: ["nursing split", "PRN", "opioids", "MDT plan"] },
    ],
    priorityOrder: { urgent: ["s1", "s3", "s7"], secondary: ["s2", "s4", "s5", "s6", "s8"], lowYield: [] },
    modelAnswer: `Rosa's pain should be validated while still formulating functional mechanisms, trauma and opioid-related harm. Multiple negative investigations do not prove that she is fabricating pain. Her statement, "No one believes me because I have trauma and take opioids," shows that invalidation and stigma are already central to the ward conflict.

The opioid plan needs containment. Rosa is prescribed high-dose oxycodone and asks for IV fentanyl, while the pain team believes opioid-induced hyperalgesia is likely. Escalating opioids shift by shift may worsen pain sensitivity, dependence, sedation and respiratory risk. I would convene surgery, pain, addiction medicine, nursing and psychiatry to agree one plan.

The surgical registrar's statement that she is manipulating the team should be challenged. Functional pain is not deception, and stigmatising language produces punitive care. Nursing staff are already split between extra opioids and refusing all PRN medication, which will worsen mistrust and escalation.

Her trauma history must change physical care. She has childhood sexual abuse and becomes distressed when male staff examine her. Examinations should use consent, explanation, chaperone, female staff where possible and avoidance of repeated unnecessary examinations.

The partner's warning that she will buy tablets on the street if discharged without pain relief requires harm reduction. The discharge plan should include safe prescribing quantities, non-opioid strategies, naloxone if appropriate, addiction follow-up, GP handover, taper or substitution consideration and clear crisis advice.`,
  },
  {
    id: "CL-004",
    questionNumber: "MEQ-118",
    topic: "cl_psychiatry",
    difficulty: "consultant",
    title: "ICU fluctuating capacity and family demanding treatment",
    candidateRole: "Consultant psychiatrist, ICU consultation-liaison service",
    setting: "Intensive care unit family meeting",
    stem: `You are the CL psychiatrist asked to assess Mr Singh, a 62-year-old man in ICU after septic shock and multi-organ failure.

Mr Singh is intermittently awake and says, "No more tubes; let me go." Two hours later he asks when he can restart dialysis. His wife says, "Our faith says only God decides death, so you must continue everything." His adult daughter says he previously told her he would never want prolonged machines.

The ICU consultant says prognosis is poor and asks whether Mr Singh has capacity to refuse ventilation and dialysis. Mr Singh speaks Punjabi at home, but the family has been interpreting because staff say "he understands enough English."`,
    totalMarks: 22,
    signals: [
      { id: "s1", name: "Critical illness creates fluctuating capacity context", category: "physical_health", severity: "critical", clueInStem: "You are the CL psychiatrist asked to assess Mr Singh, a 62-year-old man in ICU after septic shock and multi-organ failure.", whyItMatters: "Missing this signal means ICU delirium, sepsis and organ failure are not considered when interpreting refusal.", modelWording: "Assess capacity in the context of critical illness because septic shock and multi-organ failure can cause delirium and fluctuation.", keywords: ["ICU", "septic shock", "multi-organ failure", "capacity"] },
      { id: "s2", name: "Refusal may be distress or values", category: "consent_refusal", severity: "important", clueInStem: "Mr Singh is intermittently awake and says, \"No more tubes; let me go.\"", whyItMatters: "Missing this signal means one statement may be accepted as a settled refusal without assessing distress, pain or delirium.", modelWording: "Explore the refusal because it may reflect values, pain, delirium, fear or exhaustion.", keywords: ["no more tubes", "refusal", "distress"] },
      { id: "s3", name: "Dialysis request two hours later shows fluctuation", category: "capacity", severity: "critical", clueInStem: "Two hours later he asks when he can restart dialysis.", whyItMatters: "Missing this signal means inconsistent wishes are not recognised as possible fluctuating capacity.", modelWording: "Treat capacity as time-specific and fluctuating because he asks for dialysis after earlier refusing tubes.", keywords: ["restart dialysis", "fluctuating", "capacity"] },
      { id: "s4", name: "Wife's faith position needs respect but cannot override patient wishes", category: "cultural_safety", severity: "important", clueInStem: "His wife says, \"Our faith says only God decides death, so you must continue everything.\"", whyItMatters: "Missing this signal means family faith values may either be dismissed or allowed to override patient-centred decision-making.", modelWording: "Acknowledge faith values while clarifying that decisions depend on Mr Singh's capacity, prior wishes and legal framework.", keywords: ["faith", "God decides", "wife"] },
      { id: "s5", name: "Daughter provides prior wishes about machines", category: "collateral", severity: "important", clueInStem: "His adult daughter says he previously told her he would never want prolonged machines.", whyItMatters: "Missing this signal means prior values relevant to substitute decision-making are ignored.", modelWording: "Use the daughter's collateral because prior refusal of prolonged machines may guide decisions if capacity is absent.", keywords: ["daughter", "prolonged machines", "prior wishes"] },
      { id: "s6", name: "Poor prognosis informs benefits and burdens", category: "ethics", severity: "important", clueInStem: "The ICU consultant says prognosis is poor and asks whether Mr Singh has capacity to refuse ventilation and dialysis.", whyItMatters: "Missing this signal means capacity and goals-of-care discussions proceed without clear treatment burden and prognosis information.", modelWording: "Clarify prognosis and treatment burdens because capacity assessment requires realistic ICU information.", keywords: ["poor prognosis", "ventilation", "dialysis"] },
      { id: "s7", name: "Punjabi language need requires professional interpreter", category: "cultural_safety", severity: "critical", clueInStem: "Mr Singh speaks Punjabi at home, but the family has been interpreting because staff say \"he understands enough English.\"", whyItMatters: "Missing this signal means life-and-death capacity assessment relies on partial English and conflicted family interpretation.", modelWording: "Use a professional Punjabi interpreter because family interpretation is unsafe for ICU capacity and goals-of-care decisions.", keywords: ["Punjabi", "interpreter", "family", "English"] },
      { id: "s8", name: "Family disagreement may require structured ethics support", category: "family_carer", severity: "important", clueInStem: "His wife says, \"Our faith says only God decides death, so you must continue everything.\" His adult daughter says he previously told her he would never want prolonged machines.", whyItMatters: "Missing this signal means competing family narratives may derail lawful decision-making.", modelWording: "Facilitate a structured family meeting because faith values and prior-wish collateral must be reconciled within the legal framework.", keywords: ["family meeting", "wife", "daughter", "ethics"] },
    ],
    priorityOrder: { urgent: ["s1", "s3", "s7"], secondary: ["s2", "s4", "s5", "s6", "s8"], lowYield: [] },
    modelAnswer: `Mr Singh's capacity cannot be determined from one statement because the stem shows fluctuation in critical illness. He is in ICU after septic shock and multi-organ failure, is intermittently awake, says "No more tubes; let me go," and two hours later asks when he can restart dialysis. That pattern suggests delirium, sedation effects, fear, pain or fluctuating capacity.

The language issue must be corrected before any final capacity opinion. Mr Singh speaks Punjabi at home, but family have been interpreting because staff believe he understands enough English. That is not adequate for decisions about ventilation, dialysis and possible end-of-life treatment. A professional Punjabi interpreter is required.

His refusal may still be meaningful. I would assess what he understands about his illness, ventilation, dialysis, prognosis, alternatives and what outcomes he would find acceptable. The ICU consultant should clarify reversibility, burdens and likely outcomes because capacity assessment depends on realistic information.

Family views should be held in a structured process. His wife says faith requires continuing everything, while his daughter says he previously did not want prolonged machines. Both need respectful hearing, but if Mr Singh has capacity, his decision governs. If he lacks capacity, prior wishes and best-interests or substitute decision law guide the plan.

I would offer spiritual care and consider ICU ethics support if disagreement persists. Documentation should include interpreter use, timing of assessment, fluctuation, delirium contributors, prognosis information, family views, prior wishes and the legal basis for treatment continuation or limitation.`,
  },
  {
    id: "CL-005",
    questionNumber: "MEQ-119",
    topic: "cl_psychiatry",
    difficulty: "consultant",
    title: "Cancer patient refusing chemotherapy and depression-related incapacity",
    candidateRole: "Consultant psychiatrist, psycho-oncology consultation-liaison service",
    setting: "Oncology ward",
    stem: `You are the psycho-oncology consultant asked to assess Maria, a 46-year-old woman with newly diagnosed lymphoma.

Oncology recommends curative chemotherapy, but Maria says, "I deserve this cancer; treatment would be wasted on me." She has severe depression, psychomotor retardation and has stopped eating. Her husband says, "She is not herself; last month she was begging to start treatment." Maria's mother believes chemotherapy is "poison" and wants traditional remedies from their community healer.

The oncologist says delay reduces chance of cure and asks whether Maria has capacity to refuse chemotherapy. Maria says she does not want her husband involved because "he should find someone better."`,
    totalMarks: 22,
    signals: [
      { id: "s1", name: "Curative chemotherapy refusal is high stakes", category: "capacity", severity: "critical", clueInStem: "You are the psycho-oncology consultant asked to assess Maria, a 46-year-old woman with newly diagnosed lymphoma.", whyItMatters: "Missing this signal means the candidate has not recognised that this is a potentially curative treatment refusal.", modelWording: "Assess capacity urgently because newly diagnosed lymphoma with curative chemotherapy makes refusal high consequence.", keywords: ["lymphoma", "curative", "chemotherapy", "capacity"] },
      { id: "s2", name: "Depressive guilt may distort treatment value", category: "diagnosis_formulation", severity: "critical", clueInStem: "Oncology recommends curative chemotherapy, but Maria says, \"I deserve this cancer; treatment would be wasted on me.\"", whyItMatters: "Missing this signal means pathological guilt may be mistaken for an autonomous oncology refusal.", modelWording: "Assess depressive guilt because believing treatment would be wasted may impair appreciation and weighing.", keywords: ["deserve cancer", "wasted", "depressive guilt"] },
      { id: "s3", name: "Severe depression and food refusal indicate self-neglect", category: "risk_self", severity: "critical", clueInStem: "She has severe depression, psychomotor retardation and has stopped eating.", whyItMatters: "Missing this signal means risk from severe depressive illness is not actively treated while chemotherapy decisions are made.", modelWording: "Treat severe depression urgently because psychomotor retardation and food refusal suggest self-neglect and possible suicidality.", keywords: ["severe depression", "psychomotor retardation", "stopped eating"] },
      { id: "s4", name: "Husband collateral suggests state-dependent refusal", category: "collateral", severity: "important", clueInStem: "Her husband says, \"She is not herself; last month she was begging to start treatment.\"", whyItMatters: "Missing this signal means a recent opposite treatment preference is ignored.", modelWording: "Use husband's collateral because last month's wish for treatment suggests current refusal may be depression-driven and state-dependent.", keywords: ["husband", "not herself", "begging to start"] },
      { id: "s5", name: "Traditional remedy preference needs respectful discussion", category: "cultural_safety", severity: "important", clueInStem: "Maria's mother believes chemotherapy is \"poison\" and wants traditional remedies from their community healer.", whyItMatters: "Missing this signal means cultural beliefs may be dismissed or allowed to override Maria's own valid decision-making.", modelWording: "Explore traditional healing respectfully because family beliefs should be understood without replacing evidence-based oncology or Maria's wishes.", keywords: ["poison", "traditional remedies", "community healer"] },
      { id: "s6", name: "Delay reduces cure chance", category: "physical_health", severity: "critical", clueInStem: "The oncologist says delay reduces chance of cure and asks whether Maria has capacity to refuse chemotherapy.", whyItMatters: "Missing this signal means the time window for curative treatment is not integrated into capacity and legal planning.", modelWording: "Clarify the treatment window because delay may reduce cure and affect urgency of psychiatric intervention.", keywords: ["delay", "chance of cure", "oncologist"] },
      { id: "s7", name: "Excluding husband may be depressive guilt", category: "ethics", severity: "important", clueInStem: "Maria says she does not want her husband involved because \"he should find someone better.\"", whyItMatters: "Missing this signal means confidentiality is respected mechanically without assessing whether guilt is isolating her from support.", modelWording: "Respect confidentiality while exploring whether depressive guilt is driving exclusion of a supportive husband.", keywords: ["husband", "find someone better", "confidentiality"] },
    ],
    priorityOrder: { urgent: ["s1", "s2", "s3", "s6"], secondary: ["s4", "s5", "s7"], lowYield: [] },
    modelAnswer: `Maria's refusal of chemotherapy may be impaired by severe depression and pathological guilt. Newly diagnosed lymphoma with curative chemotherapy is a high-stakes context, and her statement, "I deserve this cancer; treatment would be wasted on me," is not a neutral values-based refusal. It suggests depression is distorting appreciation of the value of treatment.

Her mental state requires urgent treatment in its own right. She has severe depression, psychomotor retardation and has stopped eating, which raises concern about self-neglect and suicidality. I would assess psychotic guilt, hopelessness, capacity, suicide risk and whether urgent antidepressant, antipsychotic or ECT treatment is needed.

The husband's collateral is important. He says she is not herself and that last month she was begging to start treatment. That suggests the refusal may be state-dependent and inconsistent with her recent wishes. I would seek Maria's consent to involve him, while recognising that her wish to exclude him because he should find someone better may itself be depressive guilt.

The oncology urgency must be clarified. The oncologist says delay reduces the chance of cure, so I would ask about the treatment window, expected cure rates, alternatives and whether brief psychiatric stabilisation is possible without losing curability. This information is necessary for capacity assessment and any legal pathway.

Maria's mother's belief that chemotherapy is poison and preference for traditional remedies should be explored respectfully. Cultural support may be integrated if Maria wants it and if it does not dangerously delay curative care. The final decision should rest on Maria's capacity and values, not depression, family pressure or unexamined cultural assumptions.`,
  },
];
