import type { QuizStem } from "../quizData";

export const CS_STEMS: QuizStem[] = [
  {
    id: "CS-001",
    questionNumber: "MEQ-079",
    topic: "cultural_safety",
    difficulty: "consultant",
    title: "Aboriginal Woman Refusing ED Mental Health Assessment",
    candidateRole: "Consultant psychiatrist, rural emergency psychiatry service",
    setting: "Rural emergency department after police attendance",
    stem: `You are the consultant psychiatrist on call for a rural emergency department.

Marlee is a 36-year-old Aboriginal woman brought to ED by police after neighbours reported shouting and smashing sounds from her house. Police say she was distressed, holding a broken picture frame and yelling that "everyone is coming to take my kids again." Her two children are currently with her aunt. Marlee refuses to speak with the mental health nurse and says, "You mob only come when police drag us in."

Marlee has a history of depression, family violence and previous child protection involvement. She says, "Hospitals took my sister away and she never came back right." She denies suicidal intent but says, "If they try to take my babies, I'll fight anyone." The police want to leave because she is now calmer, but ED staff are worried she may abscond.

Her aunt is in the waiting room and says Marlee has not slept for three nights and has been drinking more since a recent family funeral. The ED nurse asks whether Marlee can be assessed involuntarily because she is refusing to engage.`,
    totalMarks: 22,
    signals: [
      { id: "s1", name: "Police-led presentation has activated cultural mistrust", category: "cultural_safety", severity: "critical", clueInStem: "Marlee refuses to speak with the mental health nurse and says, \"You mob only come when police drag us in.\"", whyItMatters: "Missing this signal means the candidate has treated refusal as non-compliance rather than recognising mistrust created by police-led contact with services.", modelWording: "Acknowledge police-related mistrust and use culturally safe engagement because coercive entry to care may intensify Marlee's distress.", keywords: ["Aboriginal health", "police", "mistrust", "cultural safety", "engagement", "refusal"] },
      { id: "s2", name: "Fear of child removal is driving threat and distress", category: "risk_others", severity: "critical", clueInStem: "She denies suicidal intent but says, \"If they try to take my babies, I'll fight anyone.\"", whyItMatters: "Missing this signal means the candidate has accepted denial of suicide risk while overlooking a threat linked to perceived child removal.", modelWording: "Assess risk to others in the context of child-removal fear because the threat is conditional on perceived loss of her children.", keywords: ["child removal", "risk to others", "threat", "family violence", "staff safety", "dynamic risk"] },
      { id: "s3", name: "Children's kinship care needs immediate clarification", category: "child_protection", severity: "important", clueInStem: "Her two children are currently with her aunt.", whyItMatters: "Missing this signal means the candidate has not clarified whether the children are safe tonight while avoiding unnecessary statutory escalation.", modelWording: "Clarify the children's immediate safety and kinship care arrangement because safeguarding should not automatically mean removal.", keywords: ["children", "aunt", "kinship care", "child protection", "safeguarding", "family"] },
      { id: "s4", name: "Institutional trauma is shaping hospital refusal", category: "trauma", severity: "important", clueInStem: "She says, \"Hospitals took my sister away and she never came back right.\"", whyItMatters: "Missing this signal means the candidate has dismissed a trauma narrative that explains fear of hospital assessment and coercion.", modelWording: "Acknowledge hospital-related trauma because dismissing Marlee's fear may re-traumatise her and worsen engagement.", keywords: ["trauma", "hospital mistrust", "family separation", "re-traumatisation", "engagement"] },
      { id: "s5", name: "Depression, family violence and child protection history contextualise risk", category: "diagnosis_formulation", severity: "important", clueInStem: "Marlee has a history of depression, family violence and previous child protection involvement.", whyItMatters: "Missing this signal means the candidate has not formulated the current crisis in relation to known mood, violence and child-protection vulnerabilities.", modelWording: "Integrate depression, family violence and prior child protection involvement because they explain both current risk and service mistrust.", keywords: ["depression", "family violence", "child protection", "formulation", "trauma", "risk"] },
      { id: "s6", name: "Acute home disturbance requires safety assessment", category: "immediate_safety", severity: "important", clueInStem: "Police say she was distressed, holding a broken picture frame and yelling that \"everyone is coming to take my kids again.\"", whyItMatters: "Missing this signal means the candidate has ignored the acute behavioural disturbance and possible access to sharp objects or weapons.", modelWording: "Assess immediate safety from the home disturbance because distress, broken glass and child-removal beliefs may escalate quickly.", keywords: ["broken picture frame", "distress", "home disturbance", "weapons", "safety", "police"] },
      { id: "s7", name: "Aunt's collateral suggests dynamic deterioration", category: "collateral", severity: "important", clueInStem: "Her aunt is in the waiting room and says Marlee has not slept for three nights and has been drinking more since a recent family funeral.", whyItMatters: "Missing this signal means the candidate has not used trusted family collateral showing sleep loss, alcohol escalation and grief-related deterioration.", modelWording: "Use the aunt's collateral to assess sleep deprivation, alcohol use, bereavement and baseline functioning.", keywords: ["aunt", "collateral", "sleep deprivation", "alcohol", "bereavement", "baseline"] },
      { id: "s8", name: "Current calmness does not remove absconding or relapse risk", category: "disposition", severity: "important", clueInStem: "The police want to leave because she is now calmer, but ED staff are worried she may abscond.", whyItMatters: "Missing this signal means the candidate has allowed transient calmness and police availability to replace a clinical risk formulation.", modelWording: "Do not rely on current calmness alone because absconding risk and unresolved dynamic factors still require a safe plan.", keywords: ["calmer", "abscond", "police", "ED", "risk formulation", "disposition"] },
      { id: "s9", name: "Involuntary assessment should follow least restrictive engagement", category: "mental_health_act", severity: "important", clueInStem: "The ED nurse asks whether Marlee can be assessed involuntarily because she is refusing to engage.", whyItMatters: "Missing this signal means the candidate has moved directly from refusal to coercion without considering culturally safe engagement and lawful criteria.", modelWording: "Consider involuntary assessment only if lawful criteria are met after least restrictive culturally safe engagement has been attempted where safe.", keywords: ["involuntary assessment", "least restrictive", "Mental Health Act", "refusal", "cultural safety", "legal criteria"] },
    ],
    priorityOrder: { urgent: ["s1", "s2"], secondary: ["s3", "s4", "s5", "s6", "s7", "s8", "s9"], lowYield: [] },
    modelAnswer: `Marlee's refusal of assessment should be understood through cultural safety, trauma and risk rather than treated as simple non-compliance. She is an Aboriginal woman brought by police, and says, "You mob only come when police drag us in." I would acknowledge that the way she arrived may feel shaming and threatening, introduce myself clearly, reduce crowding, seek Aboriginal liaison or Aboriginal health support, and try to build engagement before escalating coercion.

Cultural safety does not mean ignoring risk. Marlee was distressed at home, holding a broken picture frame and yelling that "everyone is coming to take my kids again." She also says, "If they try to take my babies, I'll fight anyone." I would assess immediate safety, access to weapons or broken glass, intoxication, psychosis, mood symptoms, family violence risk and whether threats are directed at particular people or agencies.

The children's safety must be clarified without automatically framing this as removal. The children are currently with her aunt, so I would check whether the aunt is safe, willing and able to care for them tonight, whether the children witnessed violence or were harmed, and whether child protection consultation is required. I would explain to Marlee that checking the children's safety is not the same as taking them away.

Marlee's history of depression, family violence and previous child protection involvement, and her statement that hospitals took her sister away, help explain the current crisis and service mistrust. Her aunt's collateral that she has not slept for three nights and has been drinking more since a recent funeral suggests grief, sleep deprivation and alcohol-related escalation. These are clinical data, not background colour.

The police wanting to leave because she is calmer should not determine disposition. If she can engage voluntarily with culturally safe supports, her aunt, a child-safety plan and follow-up, that may be the least restrictive option. If she remains acutely disturbed, intoxicated, threatening, psychotic, unable to collaborate or likely to abscond into serious risk, involuntary assessment may be required under the relevant law. I would document the cultural-safety steps attempted, collateral, child-safety arrangements, risk formulation, legal basis and why the final plan is the least restrictive safe option.`,
  },
  {
    id: "CS-002",
    questionNumber: "MEQ-080",
    topic: "cultural_safety",
    difficulty: "consultant",
    title: "Māori Man Admitted Involuntarily with Cultural Formulation Needs",
    candidateRole: "Consultant psychiatrist, acute inpatient unit",
    setting: "Involuntary admission to metropolitan inpatient unit in Aotearoa New Zealand",
    stem: `You are the consultant psychiatrist reviewing Wiremu, a 27-year-old Māori man admitted involuntarily after walking onto a motorway saying he was following messages from his tūpuna.

Wiremu says, "This is not sickness; my ancestors are calling me." He refuses antipsychotic medication and says staff are "cutting me off from my whakapapa." His whānau arrive and ask for a kaumātua and Māori health worker to be involved. The night registrar documented "poor insight, delusional, refusing treatment" but did not speak with whānau.

Nursing staff are concerned because Wiremu is pacing, chanting at night and not eating hospital food. His mother says, "He needs help, but not like this." The team asks whether his beliefs are psychosis, cultural experience or both, and whether involuntary treatment should continue.`,
    totalMarks: 22,
    signals: [
      { id: "s1", name: "Motorway behaviour creates serious safety concern", category: "immediate_safety", severity: "critical", clueInStem: "You are the consultant psychiatrist reviewing Wiremu, a 27-year-old Māori man admitted involuntarily after walking onto a motorway saying he was following messages from his tūpuna.", whyItMatters: "Missing this signal means the candidate has focused on culture alone while underestimating the serious safety behaviour that led to admission.", modelWording: "Reassess risk from the motorway incident because culturally informed care must still address serious foreseeable harm.", keywords: ["motorway", "immediate safety", "risk", "tūpuna", "involuntary admission", "serious harm"] },
      { id: "s2", name: "Ancestral experience requires cultural formulation before diagnosis", category: "diagnosis_formulation", severity: "critical", clueInStem: "Wiremu says, \"This is not sickness; my ancestors are calling me.\"", whyItMatters: "Missing this signal means the candidate has either pathologised a Māori spiritual experience or missed possible psychosis without proper cultural formulation.", modelWording: "Formulate whether the ancestral experience is culturally congruent, psychotic or both by involving whānau and Māori cultural expertise.", keywords: ["cultural formulation", "tūpuna", "psychosis", "spiritual experience", "Māori mental health", "diagnosis"] },
      { id: "s3", name: "Medication refusal is linked to whakapapa and identity", category: "consent_refusal", severity: "important", clueInStem: "He refuses antipsychotic medication and says staff are \"cutting me off from my whakapapa.\"", whyItMatters: "Missing this signal means the candidate has treated refusal as poor insight rather than exploring fear of cultural disconnection.", modelWording: "Explore medication refusal in relation to whakapapa, identity, side effects and illness beliefs before assuming simple non-adherence.", keywords: ["medication refusal", "whakapapa", "identity", "antipsychotic", "engagement", "consent"] },
      { id: "s4", name: "Whānau and kaumātua involvement is clinically necessary", category: "family_carer", severity: "important", clueInStem: "His whānau arrive and ask for a kaumātua and Māori health worker to be involved.", whyItMatters: "Missing this signal means the candidate has treated culturally grounded support as optional rather than central to assessment and care planning.", modelWording: "Involve whānau, a kaumātua and a Māori health worker because they may improve engagement, formulation and safety planning.", keywords: ["whānau", "kaumātua", "Māori health worker", "family", "engagement", "care planning"] },
      { id: "s5", name: "Registrar's formulation is incomplete without whānau collateral", category: "collateral", severity: "important", clueInStem: "The night registrar documented \"poor insight, delusional, refusing treatment\" but did not speak with whānau.", whyItMatters: "Missing this signal means the candidate has accepted a deficit-based formulation without cultural collateral about baseline, meaning and risk.", modelWording: "Obtain whānau collateral because diagnosis, risk and cultural meaning cannot be adequately assessed from a deficit-based note alone.", keywords: ["registrar", "whānau collateral", "poor insight", "delusional", "cultural formulation", "baseline"] },
      { id: "s6", name: "Pacing, chanting and poor intake require practical ward response", category: "physical_health", severity: "important", clueInStem: "Nursing staff are concerned because Wiremu is pacing, chanting at night and not eating hospital food.", whyItMatters: "Missing this signal means the candidate has not addressed sleep, nutrition, hydration and ward distress while debating diagnosis.", modelWording: "Assess sleep, hydration, nutrition and reasons for not eating hospital food because practical ward care may reduce distress.", keywords: ["pacing", "chanting", "not eating", "nutrition", "hydration", "ward care"] },
      { id: "s7", name: "Mother's concern supports help but challenges coercive form", category: "cultural_safety", severity: "important", clueInStem: "His mother says, \"He needs help, but not like this.\"", whyItMatters: "Missing this signal means the candidate has missed the family's nuanced position that help is needed but current care feels culturally unsafe or overly coercive.", modelWording: "Use the mother's feedback to redesign care because whānau support for help may improve a less coercive plan.", keywords: ["mother", "not like this", "whānau", "cultural safety", "coercion", "engagement"] },
      { id: "s8", name: "Ongoing involuntary treatment requires culturally informed review", category: "mental_health_act", severity: "critical", clueInStem: "The team asks whether his beliefs are psychosis, cultural experience or both, and whether involuntary treatment should continue.", whyItMatters: "Missing this signal means the candidate has either continued coercion by inertia or removed it without reassessing risk and legal criteria.", modelWording: "Review involuntary treatment after cultural formulation because compulsion must remain necessary, lawful and least restrictive.", keywords: ["involuntary treatment", "least restrictive", "Mental Health Act", "cultural formulation", "legal criteria", "risk"] },
    ],
    priorityOrder: { urgent: ["s1", "s2", "s8"], secondary: ["s3", "s4", "s5", "s6", "s7"], lowYield: [] },
    modelAnswer: `Wiremu's presentation should not be reduced to either psychosis or culture without proper formulation. He walked onto a motorway saying he was following messages from his tūpuna, which created serious safety concern and justified urgent assessment. At the same time, his statement, "This is not sickness; my ancestors are calling me," requires cultural interpretation before being labelled delusional.

I would involve whānau, a kaumātua and a Māori health worker urgently because they are not optional extras. They can help clarify whether the ancestral experience is culturally congruent, whether the intensity or behaviour is new, whether there are substance or mood factors, and how care can be made safer and more acceptable. The registrar's note of "poor insight, delusional, refusing treatment" without speaking to whānau is an incomplete and culturally unsafe formulation.

Medication refusal also needs exploration. Wiremu says antipsychotic medication is "cutting me off from my whakapapa." I would ask what he fears the medication will do, whether he has side effects, whether any part of the experience is frightening or impairing, and whether a whānau-supported conversation can help treatment feel less like cultural disconnection. If medication remains necessary, it should still be delivered in the least coercive way possible.

The ward-care concerns require action while the formulation is developed. Pacing, chanting at night and not eating hospital food may reflect psychosis, distress, cultural dislocation, unfamiliar food, paranoia, sleep disruption or environmental stress. I would assess hydration, nutrition, sleep, physical health and whether family food or cultural support can reduce distress.

The ongoing involuntary status must be reviewed after cultural formulation, current risk assessment and whānau involvement. His mother says, "He needs help, but not like this," which suggests the family is not denying the need for care but is concerned about how care is being delivered. If risk can be managed voluntarily with Māori health support and whānau involvement, that is preferable. If serious risk persists and legal criteria are met, involuntary treatment may continue, but the reasons and the steps to reduce coercion must be clearly documented.`,
  },
  {
    id: "CS-003",
    questionNumber: "MEQ-081",
    topic: "cultural_safety",
    difficulty: "consultant",
    title: "Afghan Refugee Refusing Medical Treatment in CL Psychiatry",
    candidateRole: "Consultant psychiatrist, consultation-liaison psychiatry service",
    setting: "Metropolitan medical ward",
    stem: `You are the consultant psychiatrist asked to review Ahmad, a 33-year-old Afghan refugee admitted to the medical ward with suspected infective endocarditis related to intravenous heroin use.

Ahmad initially agreed to investigations but now refuses blood cultures, echocardiography and antibiotics. He says in limited English, "No more tests; hospital makes papers for immigration." The medical registrar has been using Ahmad's cousin to interpret because "professional interpreters take too long." Ahmad becomes visibly distressed when security staff stand near the door.

His cousin says Ahmad was detained for months before arriving in Australia and avoids government offices. Ahmad says, "Maybe Allah is punishing me; medicine cannot change this." The infectious diseases team says delayed antibiotics may be life-threatening, and the ward team asks whether he lacks capacity or is simply refusing treatment.`,
    totalMarks: 22,
    signals: [
      { id: "s1", name: "Endocarditis and heroin use require medical and addiction formulation", category: "physical_health", severity: "critical", clueInStem: "You are the consultant psychiatrist asked to review Ahmad, a 33-year-old Afghan refugee admitted to the medical ward with suspected infective endocarditis related to intravenous heroin use.", whyItMatters: "Missing this signal means the candidate has framed the case only as cultural refusal while overlooking life-threatening infection and opioid-related needs.", modelWording: "Integrate medical and addiction formulation because suspected infective endocarditis and intravenous heroin use require urgent coordinated care.", keywords: ["endocarditis", "intravenous heroin", "addiction", "medical ward", "physical health", "opioid use"] },
      { id: "s2", name: "Specific treatment refusals need decision-specific capacity assessment", category: "capacity", severity: "critical", clueInStem: "Ahmad initially agreed to investigations but now refuses blood cultures, echocardiography and antibiotics.", whyItMatters: "Missing this signal means the candidate has treated capacity globally rather than assessing refusal of specific investigations and antibiotics.", modelWording: "Assess capacity decision-specifically for blood cultures, echocardiography and antibiotics because each refusal has different consequences.", keywords: ["capacity", "blood cultures", "echocardiography", "antibiotics", "decision-specific", "refusal"] },
      { id: "s3", name: "Immigration fear may be trauma-based rather than incapacity", category: "trauma", severity: "critical", clueInStem: "He says in limited English, \"No more tests; hospital makes papers for immigration.\"", whyItMatters: "Missing this signal means the candidate has mistaken trauma-related mistrust of institutions for simple incapacity or wilful refusal.", modelWording: "Formulate immigration fear in the context of refugee trauma because mistrust may be understandable and modifiable through explanation.", keywords: ["immigration", "refugee trauma", "mistrust", "detention", "hospital papers", "refusal"] },
      { id: "s4", name: "Family interpreting makes consent and capacity unsafe", category: "cultural_safety", severity: "critical", clueInStem: "The medical registrar has been using Ahmad's cousin to interpret because \"professional interpreters take too long.\"", whyItMatters: "Missing this signal means the candidate has accepted a high-stakes refusal assessment without reliable professional language support.", modelWording: "Use a professional interpreter urgently because cousin interpretation is unsafe for capacity, consent and trauma-sensitive explanation.", keywords: ["professional interpreter", "cousin", "language", "capacity", "consent", "cultural safety"] },
      { id: "s5", name: "Security presence may re-traumatise and worsen refusal", category: "immediate_safety", severity: "important", clueInStem: "Ahmad becomes visibly distressed when security staff stand near the door.", whyItMatters: "Missing this signal means the candidate has not recognised that visible coercion may worsen trauma response and refusal.", modelWording: "Minimise visible security where safe because doorway security may re-traumatise Ahmad and undermine engagement.", keywords: ["security", "door", "distress", "trauma-informed", "coercion", "engagement"] },
      { id: "s6", name: "Detention history explains avoidance of authority", category: "collateral", severity: "important", clueInStem: "His cousin says Ahmad was detained for months before arriving in Australia and avoids government offices.", whyItMatters: "Missing this signal means the candidate has ignored collateral that makes fear of hospital paperwork and authority understandable.", modelWording: "Use detention history to guide engagement because past detention may explain avoidance of officials and hospital documentation.", keywords: ["detention", "government offices", "collateral", "refugee", "authority", "avoidance"] },
      { id: "s7", name: "Spiritual explanatory model requires respectful exploration", category: "diagnosis_formulation", severity: "important", clueInStem: "Ahmad says, \"Maybe Allah is punishing me; medicine cannot change this.\"", whyItMatters: "Missing this signal means the candidate has either dismissed religious meaning or accepted fatalism without assessing understanding and treatability.", modelWording: "Explore Ahmad's religious explanatory model respectfully while explaining how medical treatment can sit alongside faith.", keywords: ["Allah", "spiritual belief", "Islam", "explanatory model", "fatalism", "engagement"] },
      { id: "s8", name: "Life-threatening delay limits time for engagement", category: "consent_refusal", severity: "critical", clueInStem: "The infectious diseases team says delayed antibiotics may be life-threatening, and the ward team asks whether he lacks capacity or is simply refusing treatment.", whyItMatters: "Missing this signal means the candidate has not balanced culturally safe engagement with the urgency of potentially life-saving treatment.", modelWording: "Clarify treatment urgency with infectious diseases because legal options depend on how long engagement can safely continue.", keywords: ["life-threatening", "delayed antibiotics", "infectious diseases", "legal options", "urgency", "capacity"] },
    ],
    priorityOrder: { urgent: ["s2", "s3", "s4", "s8"], secondary: ["s1", "s5", "s6", "s7"], lowYield: [] },
    modelAnswer: `Ahmad's refusal cannot be assessed safely until the communication problem is corrected. He is refusing blood cultures, echocardiography and antibiotics for suspected infective endocarditis, but the registrar has been using his cousin to interpret because "professional interpreters take too long." A professional interpreter is required urgently, by phone or video if needed, because capacity, consent and trauma-sensitive explanation cannot rely on family interpretation in a life-threatening refusal.

His statement, "No more tests; hospital makes papers for immigration," should be formulated in the context of refugee trauma and detention rather than immediately labelled as psychosis or incapacity. His cousin says Ahmad was detained for months before arriving in Australia and avoids government offices, so fear of paperwork and authority may be understandable. I would explain confidentiality, the separation between health care and immigration as accurately as possible, and involve refugee health, social work or bicultural support if available.

The visible security presence is likely worsening engagement. Ahmad becomes distressed when security stand near the door, so I would reduce visible coercion where safe, use one calm clinician, avoid crowding and address pain, withdrawal or fear. His intravenous heroin use also requires addiction input because opioid withdrawal, craving or stigma may be contributing to absconding risk and refusal.

The spiritual statement, "Maybe Allah is punishing me; medicine cannot change this," needs respectful exploration. I would ask what he believes is happening, whether treatment conflicts with faith, whether he wants an imam or trusted religious support, and how antibiotics might be understood as compatible with faith rather than opposing it. Spiritual meaning should inform engagement, not replace capacity assessment.

The medical urgency must be clarified with infectious diseases. Delayed antibiotics may be life-threatening, so the team needs to know how long engagement can safely continue and what the likely consequences are. If Ahmad has capacity after professional interpretation and explanation, he may refuse even serious treatment. If he lacks capacity because trauma, delirium, psychosis, intoxication or withdrawal prevents understanding or weighing, and the risk is imminent, emergency or substitute decision pathways may be needed. I would document interpreter use, decision-specific capacity reasoning, trauma formulation, spiritual supports offered, addiction needs, least restrictive engagement and the legal basis for any treatment against refusal.`,
  },
];
