import type { QuizStem } from "../quizData";

export const DIS_STEMS: QuizStem[] = [
  {
    id: "DIS-001",
    questionNumber: "MEQ-085",
    topic: "discharge_review",
    difficulty: "consultant",
    title: "Forensic Discharge Summary — Do Not Co-Sign",
    candidateRole: "Consultant forensic psychiatrist",
    setting: "Forensic inpatient unit — co-sign review queue",
    stem: `You are the consultant forensic psychiatrist. A discharge summary is in your co-sign queue from Dr Michael Tan, a first-year registrar, for Wayne, a 44-year-old man being discharged after a 12-week admission. Wayne has schizophrenia, cannabis and methamphetamine use, a history of violence towards his mother when unwell, and a prior not guilty by reason of mental illness (NGMI) finding for assault six years ago.

The four-paragraph summary documents: diagnosis (schizophrenia), medication (olanzapine 20mg), and one line: "risk: reduced during admission." It does not mention the NGMI finding, forensic history, substance use, or violence history. There is no risk formulation and no relapse prevention plan. Follow-up reads: "Wayne — please call to arrange follow-up." Wayne's mother has not been notified. No forensic community support or housing is mentioned.

Outline what you would do and why. A list without justification will not be awarded marks.`,
    totalMarks: 22,
    signals: [
      { id: "s1", name: "Co-signature would wrongly endorse an unsafe summary", category: "governance", severity: "critical", clueInStem: "A discharge summary is in your co-sign queue from Dr Michael Tan, a first-year registrar, for Wayne, a 44-year-old man being discharged after a 12-week admission.", whyItMatters: "Missing this signal means the candidate has accepted consultant responsibility for a discharge document that cannot safely guide community care.", modelWording: "Do not co-sign the summary because consultant signature would endorse an unsafe forensic discharge plan.", keywords: ["do not co-sign", "consultant responsibility", "unsafe summary", "forensic discharge", "registrar supervision"] },
      { id: "s2", name: "NGMI and violence history are essential forensic facts", category: "governance", severity: "critical", clueInStem: "Wayne has schizophrenia, cannabis and methamphetamine use, a history of violence towards his mother when unwell, and a prior not guilty by reason of mental illness (NGMI) finding for assault six years ago.", whyItMatters: "Missing this signal means the candidate has allowed the receiving team to lose core information about Wayne's legal history and violence pathway.", modelWording: "Include the NGMI finding and violence history because they are essential to forensic risk formulation and receiving-service safety.", keywords: ["NGMI", "violence history", "forensic history", "assault", "mother", "risk pathway"] },
      { id: "s3", name: "Substance use omission removes a key relapse pathway", category: "substance_use", severity: "critical", clueInStem: "It does not mention the NGMI finding, forensic history, substance use, or violence history.", whyItMatters: "Missing this signal means the candidate has not recognised that cannabis and methamphetamine use may be central to relapse and violence prevention.", modelWording: "Document cannabis and methamphetamine use clearly because substance relapse may reactivate Wayne's psychosis and violence risk.", keywords: ["substance use", "cannabis", "methamphetamine", "relapse", "violence", "forensic risk"] },
      { id: "s4", name: "Reduced inpatient risk is not a community risk formulation", category: "risk_others", severity: "critical", clueInStem: "The four-paragraph summary documents: diagnosis (schizophrenia), medication (olanzapine 20mg), and one line: \"risk: reduced during admission.\"", whyItMatters: "Missing this signal means the candidate has confused controlled inpatient behaviour with risk management after discharge.", modelWording: "Replace 'risk reduced during admission' with a community risk formulation covering static, dynamic and protective factors.", keywords: ["risk formulation", "community risk", "static factors", "dynamic factors", "protective factors", "inpatient behaviour"] },
      { id: "s5", name: "Relapse prevention plan is absent", category: "disposition", severity: "important", clueInStem: "There is no risk formulation and no relapse prevention plan.", whyItMatters: "Missing this signal means the candidate has not required a practical plan for early warning signs, adherence, substance use and escalation.", modelWording: "Add a relapse prevention plan because Wayne needs early warning signs, medication adherence steps, substance-use response and escalation contacts.", keywords: ["relapse prevention", "early warning signs", "adherence", "escalation", "substance relapse"] },
      { id: "s6", name: "Patient-initiated follow-up is unsafe", category: "disposition", severity: "critical", clueInStem: "Follow-up reads: \"Wayne — please call to arrange follow-up.\"", whyItMatters: "Missing this signal means the candidate has accepted passive follow-up for a forensic patient with schizophrenia, substance use and violence history.", modelWording: "Require confirmed assertive follow-up because asking Wayne to call is not a safe forensic discharge plan.", keywords: ["follow-up", "patient initiated", "assertive follow-up", "confirmed appointment", "forensic community"] },
      { id: "s7", name: "Mother is an identifiable victim and possible carer", category: "family_carer", severity: "critical", clueInStem: "Wayne's mother has not been notified.", whyItMatters: "Missing this signal means the candidate has overlooked victim safety, carer planning and relapse monitoring for the person previously harmed.", modelWording: "Clarify lawful notification and involve Wayne's mother where appropriate because she is both a potential carer and prior victim.", keywords: ["mother", "victim safety", "carer", "notification", "violence history", "family"] },
      { id: "s8", name: "Housing and forensic community support are missing", category: "system_pressure", severity: "important", clueInStem: "No forensic community support or housing is mentioned.", whyItMatters: "Missing this signal means the candidate has allowed discharge without the community structure needed to manage forensic relapse risk.", modelWording: "Confirm housing and forensic community support before discharge because risk management depends on stable accommodation and active supervision.", keywords: ["housing", "forensic community", "support", "supervision", "accommodation", "discharge"] },
    ],
    priorityOrder: { urgent: ["s1", "s2", "s3", "s4", "s6", "s7"], secondary: ["s5", "s8"], lowYield: [] },
    modelAnswer: `I would not co-sign this discharge summary. A consultant signature would endorse a document that does not safely communicate Wayne's forensic history, violence pathway, substance-use risks or community plan. I would hold release of the summary and supervise Dr Tan to rewrite it before it is sent.

The omissions are clinically serious. Wayne has schizophrenia, cannabis and methamphetamine use, violence toward his mother when unwell, and a prior NGMI finding for assault. The receiving team needs those facts to understand the relapse and violence pathway. A summary that simply records schizophrenia, olanzapine and "risk: reduced during admission" confuses controlled inpatient behaviour with community risk.

The rewritten summary must include a proper forensic risk formulation. It should cover static factors such as NGMI and violence history, dynamic factors such as psychotic relapse, adherence and substance use, protective factors, warning signs, triggers, and the specific plan if risk escalates. The mother must be considered carefully because she is both a prior victim and possible carer, so lawful notification, consent, victim safety and carer involvement need explicit planning.

The follow-up plan is also unsafe. "Wayne — please call to arrange follow-up" is not acceptable for a forensic discharge. The plan needs confirmed appointments, named forensic community support, medication monitoring, substance-use follow-up, housing arrangements and an after-hours escalation pathway.

I would use this as a supervision and governance issue rather than simply correcting grammar. Dr Tan needs clear feedback about the higher standard for forensic discharge documentation, and the unit should review how such a summary reached the consultant co-sign queue. Discharge should not proceed until the community risk plan is complete and communicated to all relevant services.`,
  },
  {
    id: "DIS-002",
    questionNumber: "MEQ-086",
    topic: "discharge_review",
    difficulty: "consultant",
    title: "Perinatal Discharge Summary — Missing Infant Safety and Relapse Planning",
    candidateRole: "Consultant perinatal psychiatrist",
    setting: "Mother-baby unit — co-sign review queue",
    stem: `A discharge summary for Aisha, a 29-year-old woman, is awaiting your co-signature. Aisha was admitted to the mother-baby unit six weeks ago following a postpartum psychotic episode — her first psychiatric presentation — three weeks after the birth of her daughter Lily. She responded well to olanzapine and is being discharged home with her baby.

The discharge summary reads: "Aisha's mental state has significantly improved. She is currently euthymic with good insight. She is bonding appropriately with Lily. Diagnosis: brief psychotic episode. Plan: continue olanzapine 10mg. Follow up with perinatal outpatient clinic in 4 weeks. GP to monitor."

The summary does not name Lily or include a child safety assessment. There is no documentation of parenting capacity observations during admission. Breastfeeding and olanzapine compatibility is not addressed. There is no relapse prevention plan specific to the perinatal context. There is no mention of what to do if Aisha deteriorates at home.

You note from the referral documentation that Aisha arrived in Australia from Somalia three years ago, has no extended family in Australia, and her husband works long hours and was not involved in the admission.

Outline the problems with this summary and what must happen before discharge. A list without justification will not be awarded marks.`,
    totalMarks: 22,
    signals: [
      { id: "s1", name: "Postpartum psychosis must be named and planned for", category: "diagnosis_formulation", severity: "critical", clueInStem: "Aisha was admitted to the mother-baby unit six weeks ago following a postpartum psychotic episode — her first psychiatric presentation — three weeks after the birth of her daughter Lily.", whyItMatters: "Missing this signal means the candidate has accepted an under-specified diagnosis that fails to convey perinatal relapse risk.", modelWording: "Document postpartum psychosis explicitly because the diagnosis shapes relapse prevention, infant safety and future pregnancy counselling.", keywords: ["postpartum psychosis", "diagnosis", "perinatal", "future pregnancy", "relapse risk"] },
      { id: "s2", name: "Lily is unnamed and infant safety is undocumented", category: "child_protection", severity: "critical", clueInStem: "The summary does not name Lily or include a child safety assessment.", whyItMatters: "Missing this signal means the candidate has failed to document the safety of the vulnerable infant being discharged with Aisha.", modelWording: "Name Lily and document infant safety because mother-baby discharge must explicitly address the baby's wellbeing and safeguards.", keywords: ["Lily", "infant safety", "child safety", "baby", "safeguarding", "mother-baby"] },
      { id: "s3", name: "Parenting capacity observations are absent", category: "risk_vulnerable", severity: "critical", clueInStem: "There is no documentation of parenting capacity observations during admission.", whyItMatters: "Missing this signal means the candidate has accepted a vague bonding statement without evidence of observed caregiving capacity.", modelWording: "Document parenting observations because safe discharge with Lily requires evidence of feeding, settling, responsiveness and supervised care during admission.", keywords: ["parenting capacity", "observations", "bonding", "feeding", "settling", "infant care"] },
      { id: "s4", name: "Olanzapine and breastfeeding discussion is missing", category: "physical_health", severity: "important", clueInStem: "Breastfeeding and olanzapine compatibility is not addressed.", whyItMatters: "Missing this signal means the candidate has not documented maternal medication counselling or infant monitoring related to feeding choice.", modelWording: "Document the olanzapine and breastfeeding risk-benefit discussion because Aisha and Lily need an informed feeding and monitoring plan.", keywords: ["olanzapine", "breastfeeding", "infant monitoring", "risk-benefit", "feeding", "medication"] },
      { id: "s5", name: "Perinatal relapse prevention plan is absent", category: "risk_self", severity: "critical", clueInStem: "There is no relapse prevention plan specific to the perinatal context.", whyItMatters: "Missing this signal means the candidate has not planned for early warning signs and rapid deterioration in the high-risk postnatal period.", modelWording: "Write a perinatal relapse prevention plan because postpartum psychosis can recur rapidly and affects both mother and baby safety.", keywords: ["relapse prevention", "perinatal", "postpartum psychosis", "early warning signs", "crisis plan"] },
      { id: "s6", name: "No deterioration plan for home with baby", category: "disposition", severity: "critical", clueInStem: "There is no mention of what to do if Aisha deteriorates at home.", whyItMatters: "Missing this signal means the candidate has allowed discharge without a contingency plan for deterioration while caring for an infant.", modelWording: "Add a home deterioration plan because Aisha and her family need clear steps if symptoms return while she is with Lily.", keywords: ["deteriorates at home", "contingency", "crisis escalation", "baby", "home safety"] },
      { id: "s7", name: "Four-week follow-up is too delayed", category: "disposition", severity: "important", clueInStem: "Follow up with perinatal outpatient clinic in 4 weeks.", whyItMatters: "Missing this signal means the candidate has accepted routine follow-up for a recent mother-baby discharge after psychosis.", modelWording: "Arrange early perinatal follow-up because four weeks is too delayed after discharge for postpartum psychosis.", keywords: ["four weeks", "follow-up", "perinatal outpatient", "early review", "post-discharge"] },
      { id: "s8", name: "Social isolation and absent husband increase discharge vulnerability", category: "cultural_safety", severity: "important", clueInStem: "Aisha arrived in Australia from Somalia three years ago, has no extended family in Australia, and her husband works long hours and was not involved in the admission.", whyItMatters: "Missing this signal means the candidate has not accounted for limited practical support, migration stress and lack of involved family before discharge with a baby.", modelWording: "Assess culturally safe practical supports because no extended family and an uninvolved working husband increase vulnerability at home.", keywords: ["Somalia", "no extended family", "husband", "support", "migration", "cultural safety"] },
    ],
    priorityOrder: { urgent: ["s1", "s2", "s3", "s5", "s6"], secondary: ["s4", "s7", "s8"], lowYield: [] },
    modelAnswer: `I would not co-sign this discharge summary or allow discharge to proceed until the perinatal and infant-safety gaps are corrected. Aisha was admitted to a mother-baby unit after postpartum psychosis three weeks after Lily's birth, yet the summary calls it a brief psychotic episode and gives a routine plan. The diagnosis should clearly convey postpartum psychosis because it changes relapse planning, infant safety, future pregnancy advice and follow-up intensity.

Lily must be named in the summary and her safety must be explicitly documented. A vague statement that Aisha is bonding appropriately is not enough. The document should include observed parenting capacity during admission, including feeding, settling, responsiveness, supervision needs, sleep arrangements, attachment observations and any child-safety concerns or protective factors.

Medication and feeding also need documentation. Aisha is to continue olanzapine 10 mg, but breastfeeding and olanzapine compatibility are not addressed. The summary should document whether she is breastfeeding, the risk-benefit discussion, her informed decision, and any monitoring needed for Lily.

The discharge plan lacks perinatal relapse prevention. It should list Aisha's early warning signs, sleep-protection plan, medication adherence plan, what her husband should do if symptoms return, emergency contacts, after-hours escalation, and what happens if she deteriorates while alone with Lily. Four-week follow-up is too delayed for recent postpartum psychosis; early community perinatal contact and senior review should be arranged.

The social context makes the plan more vulnerable. Aisha arrived from Somalia three years ago, has no extended family in Australia, and her husband works long hours and was not involved in the admission. I would involve him before discharge, assess culturally appropriate supports, link community maternal-child health and perinatal services, and ensure that the home support plan is practical rather than assumed.`,
  },
  {
    id: "DIS-003",
    questionNumber: "MEQ-087",
    topic: "discharge_review",
    difficulty: "consultant",
    title: "Registrar Discharging High-Risk Patient Without Safety Plan",
    candidateRole: "Consultant psychiatrist supervising inpatient registrar",
    setting: "Acute inpatient psychiatric unit — Tuesday afternoon supervision",
    stem: `You are conducting your weekly supervision session with Dr Priya Sharma, a second-year advanced trainee. She presents a case for discharge planning: Callum, a 29-year-old man admitted three weeks ago following an overdose of 40 paracetamol tablets. He has recurrent major depressive disorder and borderline personality disorder.

Dr Sharma presents a risk assessment of "low to moderate." She tells you: "He's engaged in sessions, his mood is improved, he denies SI, and he wants to go home." She has not contacted Callum's mother, who brought him in and is his emergency contact. She has not developed a written safety plan. She has not arranged community follow-up. She has not reviewed his previous inpatient presentations.

You note from the system that Callum has had four prior admissions in three years, each following a paracetamol overdose. Dr Sharma is also telling you that there is pressure from the NUM because the ward is full and a bed is urgently needed.

Outline how you would respond to this situation. A list without justification will not be awarded marks.`,
    totalMarks: 22,
    signals: [
      { id: "s1", name: "Recent large paracetamol overdose is high risk", category: "risk_self", severity: "critical", clueInStem: "Callum, a 29-year-old man admitted three weeks ago following an overdose of 40 paracetamol tablets.", whyItMatters: "Missing this signal means the candidate has underestimated the index admission that required inpatient care after a potentially lethal overdose.", modelWording: "Treat the index paracetamol overdose as high risk because discharge planning must address method, intent, access and recurrence.", keywords: ["paracetamol overdose", "40 tablets", "index admission", "self-harm", "suicide risk"] },
      { id: "s2", name: "Denial-based low-to-moderate rating is insufficient", category: "risk_self", severity: "critical", clueInStem: "She tells you: \"He's engaged in sessions, his mood is improved, he denies SI, and he wants to go home.\"", whyItMatters: "Missing this signal means the candidate has accepted improvement and denial of suicidal ideation as a complete discharge risk formulation.", modelWording: "Challenge the low-to-moderate rating because engagement, mood improvement and denial of SI do not replace a full risk formulation.", keywords: ["denies SI", "low to moderate", "risk formulation", "mood improved", "wants to go home"] },
      { id: "s3", name: "Mother collateral is missing", category: "collateral", severity: "critical", clueInStem: "She has not contacted Callum's mother, who brought him in and is his emergency contact.", whyItMatters: "Missing this signal means the candidate has not obtained essential information from the person who brought him in and may be part of the home safety plan.", modelWording: "Obtain collateral from Callum's mother because she is the emergency contact, brought him in and may know current triggers and home risks.", keywords: ["mother", "collateral", "emergency contact", "home risk", "family", "support"] },
      { id: "s4", name: "Written safety plan is absent", category: "risk_self", severity: "critical", clueInStem: "She has not developed a written safety plan.", whyItMatters: "Missing this signal means the candidate has considered discharge without a minimum collaborative suicide-prevention tool.", modelWording: "Require a written collaborative safety plan before discharge because recurrent overdose risk needs coping steps, means restriction and crisis contacts.", keywords: ["written safety plan", "collaborative", "means restriction", "crisis contacts", "suicide prevention"] },
      { id: "s5", name: "Community follow-up has not been arranged", category: "disposition", severity: "important", clueInStem: "She has not arranged community follow-up.", whyItMatters: "Missing this signal means the candidate has accepted discharge without continuity during the high-risk transition period.", modelWording: "Confirm community follow-up before discharge because high-risk patients need active post-discharge contact, not vague advice.", keywords: ["community follow-up", "post-discharge", "continuity", "confirmed appointment", "transition"] },
      { id: "s6", name: "Repeated paracetamol overdose pattern was not reviewed", category: "diagnosis_formulation", severity: "critical", clueInStem: "You note from the system that Callum has had four prior admissions in three years, each following a paracetamol overdose.", whyItMatters: "Missing this signal means the candidate has ignored the strongest available evidence of recurrence pattern and method-specific risk.", modelWording: "Review previous admissions because four paracetamol overdoses in three years change the risk formulation and discharge threshold.", keywords: ["four prior admissions", "paracetamol overdose", "recurrence", "pattern", "previous presentations"] },
      { id: "s7", name: "Bed pressure must not determine discharge", category: "system_pressure", severity: "critical", clueInStem: "Dr Sharma is also telling you that there is pressure from the NUM because the ward is full and a bed is urgently needed.", whyItMatters: "Missing this signal means the candidate has allowed ward access pressure to override unresolved suicide-risk planning.", modelWording: "Resist bed-pressure discharge because clinical readiness and safety planning must determine disposition.", keywords: ["bed pressure", "NUM", "ward full", "urgent bed", "system pressure", "discharge"] },
      { id: "s8", name: "Registrar needs supervised formulation, not simple override", category: "governance", severity: "important", clueInStem: "You are conducting your weekly supervision session with Dr Priya Sharma, a second-year advanced trainee.", whyItMatters: "Missing this signal means the candidate has corrected the discharge decision without teaching the trainee how to produce defensible discharge reasoning.", modelWording: "Use supervision to teach defensible discharge formulation because Dr Sharma needs to understand why each missing element matters.", keywords: ["supervision", "advanced trainee", "teaching", "formulation", "discharge reasoning", "governance"] },
    ],
    priorityOrder: { urgent: ["s1", "s2", "s3", "s4", "s6", "s7"], secondary: ["s5", "s8"], lowYield: [] },
    modelAnswer: `I would not authorise Callum's discharge on the information presented. He was admitted after an overdose of 40 paracetamol tablets and has had four prior admissions in three years, each following a paracetamol overdose. That repeated method-specific pattern is central to the risk formulation and makes a simple low-to-moderate rating unsafe.

Dr Sharma's reassuring factors are not irrelevant, but they are incomplete. Engagement in sessions, improved mood, denial of suicidal ideation and wanting to go home do not replace a formulation that integrates prior overdoses, triggers, intent, access to paracetamol, personality vulnerability, supports and the post-discharge period.

Several minimum discharge components are missing. Callum's mother brought him in, is his emergency contact, and has not been contacted. There is no written safety plan, no means-restriction plan and no confirmed community follow-up. These gaps must be addressed before discharge is reconsidered.

Bed pressure from the NUM must be acknowledged but not allowed to determine disposition. If the ward is full and a bed is urgently needed, that should be escalated as a system issue; it is not a clinical reason to discharge a patient whose suicide-risk plan is incomplete.

I would use the supervision session as a teaching moment rather than simply overruling Dr Sharma. We would review the previous admissions together, obtain collateral from Callum's mother, develop a written safety plan with Callum, arrange active community follow-up, prepare GP communication and document the rationale for delaying discharge. The goal is to teach defensible discharge reasoning while protecting the patient.`,
  },
];
