import type { QuizStem } from "../quizData";

export const DOC_STEMS: QuizStem[] = [
  {
    id: "DOC-001",
    questionNumber: "MEQ-082",
    topic: "documentation",
    difficulty: "consultant",
    title: "Inadequate Discharge Summary — First Episode Psychosis",
    candidateRole: "Consultant psychiatrist, inpatient unit",
    setting: "Acute inpatient psychiatric unit, metropolitan hospital",
    stem: `You are the consultant psychiatrist on an acute inpatient unit. You receive a call from Dr Sarah Adeyemi, a GP, who is frustrated. Her patient Reza, a 34-year-old Iranian man, was discharged from your unit five days ago after a four-week admission for first episode schizophrenia. He has just presented to her clinic looking unwell.

Dr Adeyemi tells you: "The discharge summary doesn't tell me his diagnosis — it says 'psychotic disorder under investigation.' No medications, no doses, no follow-up plan, no case manager. I have no idea who to call if he deteriorates tonight."

You check the summary. Three paragraphs, written by the after-hours registrar at 11pm on the day of discharge. No consultant co-signature. Reza's wife called this morning — he has stopped his tablets and has been "acting strangely" since yesterday.

Outline the issues you would identify and the actions you would take. A list without justification will not be awarded marks.`,
    totalMarks: 22,
    signals: [
      { id: "s1", name: "Current deterioration requires same-day clinical review", category: "immediate_safety", severity: "critical", clueInStem: "He has just presented to her clinic looking unwell.", whyItMatters: "Missing this signal means the candidate has treated a deteriorating first-episode psychosis patient five days after discharge as an administrative documentation problem.", modelWording: "Arrange same-day clinical review because Reza is already unwell in the high-risk early post-discharge period.", keywords: ["same-day review", "deterioration", "first episode psychosis", "post-discharge", "urgent", "relapse"] },
      { id: "s2", name: "Medication cessation and strange behaviour suggest relapse", category: "risk_self", severity: "critical", clueInStem: "Reza's wife called this morning — he has stopped his tablets and has been \"acting strangely\" since yesterday.", whyItMatters: "Missing this signal means the candidate has not recognised that non-adherence plus behavioural change may indicate early relapse requiring urgent intervention.", modelWording: "Treat medication cessation and strange behaviour as possible relapse because first-episode psychosis can deteriorate rapidly after discharge.", keywords: ["stopped tablets", "acting strangely", "relapse", "wife collateral", "adherence", "risk"] },
      { id: "s3", name: "Discharge summary omitted essential clinical information", category: "governance", severity: "critical", clueInStem: "Dr Adeyemi tells you: \"The discharge summary doesn't tell me his diagnosis — it says 'psychotic disorder under investigation.' No medications, no doses, no follow-up plan, no case manager. I have no idea who to call if he deteriorates tonight.\"", whyItMatters: "Missing this signal means the candidate has not identified that the summary failed to provide the GP with the minimum information needed for safe shared care.", modelWording: "Send a corrected discharge addendum today because the GP lacks diagnosis, medication, follow-up, case-manager and escalation information.", keywords: ["discharge summary", "diagnosis", "medications", "follow-up", "case manager", "addendum", "GP"] },
      { id: "s4", name: "After-hours summary without consultant co-signature is a supervision failure", category: "governance", severity: "important", clueInStem: "Three paragraphs, written by the after-hours registrar at 11pm on the day of discharge. No consultant co-signature.", whyItMatters: "Missing this signal means the candidate has accepted an unsupervised after-hours discharge document for a complex first-episode psychosis admission.", modelWording: "Review consultant oversight because an after-hours registrar summary for first-episode psychosis required senior review and co-signature.", keywords: ["after-hours registrar", "consultant co-signature", "supervision", "discharge", "governance"] },
      { id: "s5", name: "First-episode schizophrenia discharge needs relapse and recovery planning", category: "diagnosis_formulation", severity: "important", clueInStem: "Her patient Reza, a 34-year-old Iranian man, was discharged from your unit five days ago after a four-week admission for first episode schizophrenia.", whyItMatters: "Missing this signal means the candidate has not recognised that first-episode schizophrenia discharge requires clear diagnosis, psychoeducation, early relapse signs and recovery planning.", modelWording: "Provide first-episode psychosis-specific discharge information because Reza and his GP need relapse indicators, adherence plan and recovery supports.", keywords: ["first episode schizophrenia", "relapse plan", "psychoeducation", "recovery", "early intervention"] },
      { id: "s6", name: "GP escalation pathway was absent", category: "mdt_conflict", severity: "important", clueInStem: "I have no idea who to call if he deteriorates tonight.", whyItMatters: "Missing this signal means the candidate has not repaired the immediate interface failure between inpatient psychiatry, GP and community services.", modelWording: "Give Dr Adeyemi a named contact and after-hours escalation pathway because she is managing a deteriorating patient tonight.", keywords: ["GP", "escalation", "after-hours", "named contact", "community team", "interface"] },
      { id: "s7", name: "Wife's collateral requires active carer engagement", category: "family_carer", severity: "important", clueInStem: "Reza's wife called this morning — he has stopped his tablets and has been \"acting strangely\" since yesterday.", whyItMatters: "Missing this signal means the candidate has not used family collateral as a safety signal or involved the wife in relapse planning where appropriate.", modelWording: "Contact Reza's wife with consent or within safety limits because her collateral may guide relapse assessment and adherence support.", keywords: ["wife", "collateral", "family", "carer", "relapse plan", "adherence"] },
    ],
    priorityOrder: { urgent: ["s1", "s2", "s3"], secondary: ["s4", "s5", "s6", "s7"], lowYield: [] },
    modelAnswer: `This is an immediate clinical safety issue as well as a documentation failure. Reza is five days post-discharge after a first-episode schizophrenia admission, has presented to his GP looking unwell, and his wife reports that he has stopped his tablets and has been "acting strangely" since yesterday. I would arrange same-day community mental health review or direct assessment, clarify current risk, medication adherence, psychotic symptoms and supports, and give the GP clear escalation advice for tonight.

The discharge summary has failed minimum standards for safe shared care. Dr Adeyemi says it does not give a diagnosis, medications, doses, follow-up plan, case manager or emergency contact. I would call her, acknowledge the failure, provide the missing information verbally, and send a consultant-reviewed addendum the same day with working diagnosis, admission course, risk formulation, medication plan, side effects, relapse indicators, follow-up arrangements, case-manager details and after-hours contact pathway.

The supervision failure also needs review. The summary was only three paragraphs, written by an after-hours registrar at 11 pm on the day of discharge, with no consultant co-signature. That is not adequate for a complex first-episode psychosis discharge. I would ensure the corrected document is consultant reviewed and then examine the unit process that allowed an incomplete discharge summary to leave the hospital.

Reza's wife should not be treated as background information. Her call is important collateral that may indicate relapse, and she may be central to adherence support and early warning signs if Reza consents or if limited safety-related contact is justified. I would ensure she knows how to seek help if he deteriorates.

The governance response should include feedback to the registrar, audit of discharge summaries for high-risk psychiatric discharges, a requirement for consultant review of first-episode psychosis summaries, and a process that prevents discharge without named follow-up and escalation details. The purpose is not to blame the after-hours registrar alone, but to restore continuity and prevent another unsafe handover.`,
  },
  {
    id: "DOC-002",
    questionNumber: "MEQ-083",
    topic: "documentation",
    difficulty: "consultant",
    title: "Capacity Assessment Documentation — Life-Sustaining Treatment Refusal",
    candidateRole: "Consultation-liaison consultant psychiatrist",
    setting: "General medical ward, metropolitan hospital",
    stem: `You are the consultation-liaison consultant. During your ward round you review the previous day's notes. You find an entry from your registrar, Dr Claire Wu, following a bedside consultation for Mrs Irene Papageorgiou, a 78-year-old Greek-born woman who has been in Australia for 50 years and is fluent in English. Mrs Papageorgiou has metastatic bowel cancer and has refused her third cycle of chemotherapy.

Dr Wu's capacity assessment note reads in full: "Seen and assessed. Patient appears to understand her diagnosis. She said she doesn't want more chemo as she's tired of being sick. She seems to have capacity. Discussed with oncology — treatment will not proceed. Impression: capacity intact. Plan: discharge to palliative care."

No formal four-domain assessment is documented. The note does not state what information was provided to the patient, whether she retained and understood it, what the consequences of refusal were explained to be, or whether her decision is consistent with her values. There is no mention of the patient's cultural or spiritual background. The oncology team has proceeded with discharge planning on the basis of this note.

Outline the issues with this documentation and what you would do. A list without justification will not be awarded marks.`,
    totalMarks: 20,
    signals: [
      { id: "s1", name: "Chemotherapy refusal is a high-stakes capacity decision", category: "capacity", severity: "critical", clueInStem: "Mrs Papageorgiou has metastatic bowel cancer and has refused her third cycle of chemotherapy.", whyItMatters: "Missing this signal means the candidate has treated a potentially life-shortening refusal as a routine note rather than a high-stakes decision requiring defensible documentation.", modelWording: "Treat refusal of chemotherapy for metastatic bowel cancer as a high-stakes decision requiring detailed decision-specific capacity assessment.", keywords: ["chemotherapy refusal", "metastatic bowel cancer", "capacity", "life-sustaining", "high-stakes"] },
      { id: "s2", name: "Vague capacity conclusion is not legally defensible", category: "capacity", severity: "critical", clueInStem: "Dr Wu's capacity assessment note reads in full: \"Seen and assessed. Patient appears to understand her diagnosis. She said she doesn't want more chemo as she's tired of being sick. She seems to have capacity. Discussed with oncology — treatment will not proceed. Impression: capacity intact. Plan: discharge to palliative care.\"", whyItMatters: "Missing this signal means the candidate has accepted impressions such as appears and seems as if they demonstrate the capacity test.", modelWording: "Rewrite the capacity opinion with evidence because 'appears' and 'seems' do not show how capacity was assessed.", keywords: ["seems to have capacity", "appears", "capacity intact", "evidence", "documentation"] },
      { id: "s3", name: "Four-domain assessment is absent", category: "capacity", severity: "critical", clueInStem: "No formal four-domain assessment is documented.", whyItMatters: "Missing this signal means the candidate has not required documentation of understanding, retention, weighing and communication for a life-limiting refusal.", modelWording: "Document the four domains explicitly because capacity cannot be inferred from a global impression.", keywords: ["four-domain", "understanding", "retention", "weighing", "communication", "capacity"] },
      { id: "s4", name: "Information and consequences of refusal were not documented", category: "consent_refusal", severity: "critical", clueInStem: "The note does not state what information was provided to the patient, whether she retained and understood it, what the consequences of refusal were explained to be, or whether her decision is consistent with her values.", whyItMatters: "Missing this signal means the candidate has no basis to know whether Mrs Papageorgiou's refusal was informed and values-congruent.", modelWording: "Document the information provided, consequences of refusal and values-based weighing because informed refusal depends on these elements.", keywords: ["information provided", "consequences", "retained", "understood", "values", "informed refusal"] },
      { id: "s5", name: "Cultural and spiritual context was omitted", category: "cultural_safety", severity: "important", clueInStem: "There is no mention of the patient's cultural or spiritual background.", whyItMatters: "Missing this signal means the candidate has not explored values, faith, family expectations or cultural meaning relevant to a major end-of-life decision.", modelWording: "Explore cultural and spiritual context because values may shape refusal, palliative preferences and desired family involvement.", keywords: ["cultural", "spiritual", "values", "Greek", "end of life", "family"] },
      { id: "s6", name: "Greek background should be explored without stereotyping", category: "cultural_safety", severity: "important", clueInStem: "a 78-year-old Greek-born woman who has been in Australia for 50 years and is fluent in English.", whyItMatters: "Missing this signal means the candidate has either ignored cultural context because she speaks English or assumed culture without asking her values.", modelWording: "Ask Mrs Papageorgiou what matters to her because being Greek-born and fluent in English does not remove the need for individual cultural formulation.", keywords: ["Greek-born", "fluent English", "cultural formulation", "values", "individualised", "spiritual"] },
      { id: "s7", name: "Discharge planning is proceeding on inadequate documentation", category: "disposition", severity: "critical", clueInStem: "The oncology team has proceeded with discharge planning on the basis of this note.", whyItMatters: "Missing this signal means the candidate has allowed a major treatment and disposition decision to proceed on an inadequate capacity record.", modelWording: "Pause discharge planning until capacity is properly assessed and documented because oncology is relying on an unsafe note.", keywords: ["discharge planning", "oncology", "pause", "unsafe note", "palliative care", "documentation"] },
      { id: "s8", name: "Registrar needs supervision on capacity documentation", category: "governance", severity: "important", clueInStem: "You find an entry from your registrar, Dr Claire Wu, following a bedside consultation for Mrs Irene Papageorgiou, a 78-year-old Greek-born woman who has been in Australia for 50 years and is fluent in English.", whyItMatters: "Missing this signal means the candidate has corrected the immediate note without addressing the training and supervision failure that produced it.", modelWording: "Supervise Dr Wu directly because capacity documentation for life-sustaining treatment refusal requires a higher standard.", keywords: ["registrar", "supervision", "Dr Wu", "teaching", "capacity documentation", "governance"] },
    ],
    priorityOrder: { urgent: ["s1", "s2", "s3", "s4", "s7"], secondary: ["s5", "s6", "s8"], lowYield: [] },
    modelAnswer: `This note is not an adequate capacity assessment for a high-stakes refusal. Mrs Papageorgiou has metastatic bowel cancer and has refused her third cycle of chemotherapy, so the decision may affect prognosis, symptom burden and timing of palliative care. A global statement that she appears to understand and seems to have capacity is not legally or clinically defensible.

I would pause reliance on the note and speak with oncology. The oncology team has proceeded with discharge planning on the basis of this documentation, but the current record does not show what information was provided, what consequences of refusal were explained, whether she retained and understood the information, or how she weighed the decision against her values. Discharge to palliative care should not proceed as if capacity has been properly established until the assessment is completed.

I would reassess Mrs Papageorgiou personally or supervise a proper reassessment the same day. The note should document the specific decision, the information given about diagnosis, prognosis, chemotherapy benefits and burdens, alternatives and consequences of refusal, and evidence for understanding, retention, weighing and communication. It should also record whether the decision is stable and consistent with her values.

Cultural and spiritual context should be explored without stereotyping. Mrs Papageorgiou is Greek-born, has lived in Australia for 50 years and is fluent in English, so language may not be the issue, but culture, faith, family expectations and views of dying or palliative care may still matter. The task is to ask what matters to her, not to assume what a Greek background means.

Dr Wu needs direct supervision and feedback. I would explain that capacity documentation for life-sustaining or life-shortening treatment decisions requires more than an impression, and I would review the corrected note with her. If capacity is confirmed, Mrs Papageorgiou's refusal should be respected; if capacity is not established, oncology needs a lawful decision-making pathway before treatment is stopped or discharge proceeds.`,
  },
  {
    id: "DOC-003",
    questionNumber: "MEQ-084",
    topic: "documentation",
    difficulty: "consultant",
    title: "Mental Health Act Documentation — Inadequate Legal Justification",
    candidateRole: "Consultant psychiatrist, acute inpatient unit supervisor",
    setting: "Acute inpatient psychiatric unit",
    stem: `You are the supervising consultant on an acute inpatient unit. A registrar, Dr James Park, asks you to review Mental Health Act paperwork he has completed for Sofia, a 28-year-old Aboriginal woman detained overnight after she attempted to leave the ward saying staff were "poisoning my baby through the breast milk."

The MHA form reads in full: "Psychotic. Risk to infant. Needs admission. Detained under s.26."

There is no description of the specific behaviour observed, no record of Sofia's own account of her beliefs, no documentation of less restrictive alternatives considered, no capacity reasoning, and no reference to the cultural context. Sofia is breastfeeding her three-day-old infant. She has repeatedly asked for her aunt to be called. The nurses tell you the aunt has not been contacted.

You also note that the infant has not been seen by the paediatric team and no child protection notification has been made.

Outline the problems with this documentation and what must happen now. A list without justification will not be awarded marks.`,
    totalMarks: 22,
    signals: [
      { id: "s1", name: "Bare MHA labels do not evidence legal criteria", category: "mental_health_act", severity: "critical", clueInStem: "The MHA form reads in full: \"Psychotic. Risk to infant. Needs admission. Detained under s.26.\"", whyItMatters: "Missing this signal means the candidate has accepted labels as if they justify involuntary detention under statute.", modelWording: "Rewrite the MHA form with factual criteria because diagnostic labels and risk labels do not justify detention.", keywords: ["MHA", "legal criteria", "detained", "bare labels", "documentation", "statutory"] },
      { id: "s2", name: "Sofia's behaviour and own account were not documented", category: "governance", severity: "critical", clueInStem: "There is no description of the specific behaviour observed, no record of Sofia's own account of her beliefs, no documentation of less restrictive alternatives considered, no capacity reasoning, and no reference to the cultural context.", whyItMatters: "Missing this signal means the candidate has not required the facts needed to connect mental state, behaviour and statutory criteria.", modelWording: "Document Sofia's observed behaviour and own words because the form must show the factual basis for detention and risk.", keywords: ["specific behaviour", "own account", "beliefs", "documentation", "facts", "risk reasoning"] },
      { id: "s3", name: "Breast-milk poisoning belief creates specific infant risk", category: "risk_vulnerable", severity: "critical", clueInStem: "A registrar, Dr James Park, asks you to review Mental Health Act paperwork he has completed for Sofia, a 28-year-old Aboriginal woman detained overnight after she attempted to leave the ward saying staff were \"poisoning my baby through the breast milk.\"", whyItMatters: "Missing this signal means the candidate has treated infant risk generically rather than recognising the specific delusional content involving feeding and infant care.", modelWording: "Assess infant risk from the breast-milk poisoning belief because it directly affects feeding, mother-infant contact and supervision needs.", keywords: ["breast milk", "poisoning", "infant risk", "mother-infant", "feeding", "psychosis"] },
      { id: "s4", name: "Capacity reasoning is absent", category: "capacity", severity: "critical", clueInStem: "There is no description of the specific behaviour observed, no record of Sofia's own account of her beliefs, no documentation of less restrictive alternatives considered, no capacity reasoning, and no reference to the cultural context.", whyItMatters: "Missing this signal means the candidate has not documented how Sofia's mental state affects her ability to understand, appreciate and weigh admission and infant-care decisions.", modelWording: "Add capacity reasoning because detention and treatment planning require evidence of how psychosis affects understanding, appreciation and weighing.", keywords: ["capacity reasoning", "understanding", "weighing", "appreciation", "admission", "infant care"] },
      { id: "s5", name: "Least restrictive alternatives were not considered", category: "mental_health_act", severity: "important", clueInStem: "There is no description of the specific behaviour observed, no record of Sofia's own account of her beliefs, no documentation of less restrictive alternatives considered, no capacity reasoning, and no reference to the cultural context.", whyItMatters: "Missing this signal means the candidate has not shown why voluntary care, family support or maternity-linked care were insufficient before detention.", modelWording: "Document less restrictive alternatives because compulsory admission must be necessary and not merely convenient.", keywords: ["least restrictive", "voluntary", "alternatives", "family support", "detention", "MHA"] },
      { id: "s6", name: "Aboriginal aunt request was ignored", category: "cultural_safety", severity: "critical", clueInStem: "She has repeatedly asked for her aunt to be called. The nurses tell you the aunt has not been contacted.", whyItMatters: "Missing this signal means the candidate has missed a culturally important nominated support that may reduce distress and coercion.", modelWording: "Contact Sofia's aunt urgently because her nominated support is clinically and culturally important for engagement and least restrictive care.", keywords: ["aunt", "Aboriginal", "cultural safety", "family support", "engagement", "least restrictive"] },
      { id: "s7", name: "Paediatric review and child protection were omitted", category: "child_protection", severity: "critical", clueInStem: "You also note that the infant has not been seen by the paediatric team and no child protection notification has been made.", whyItMatters: "Missing this signal means the candidate has not acted on infant safety in a three-day-old baby exposed to possible maternal psychosis and feeding disruption.", modelWording: "Arrange paediatric review and consider child protection notification because the infant's safety and feeding need immediate assessment.", keywords: ["paediatrics", "child protection", "infant", "three-day-old", "safeguarding", "notification"] },
      { id: "s8", name: "Registrar requires supervised correction before reliance on the form", category: "governance", severity: "important", clueInStem: "A registrar, Dr James Park, asks you to review Mental Health Act paperwork he has completed for Sofia, a 28-year-old Aboriginal woman detained overnight after she attempted to leave the ward saying staff were \"poisoning my baby through the breast milk.\"", whyItMatters: "Missing this signal means the candidate has allowed defective legal documentation to remain in use without correcting the supervision failure.", modelWording: "Supervise Dr Park to rewrite the form because the current paperwork should not be relied on for continued detention.", keywords: ["registrar", "supervision", "rewrite", "MHA paperwork", "legal rights", "governance"] },
    ],
    priorityOrder: { urgent: ["s1", "s2", "s3", "s4", "s6", "s7"], secondary: ["s5", "s8"], lowYield: [] },
    modelAnswer: `This Mental Health Act form is not legally defensible as written. The words "Psychotic. Risk to infant. Needs admission. Detained under s.26" are labels, not evidence. The form must document the specific behaviour observed, Sofia's own account, the statutory criteria, the risk reasoning, capacity reasoning and why less restrictive alternatives were insufficient.

The clinical risk is specific, not generic. Sofia attempted to leave the ward saying staff were "poisoning my baby through the breast milk." That belief has direct implications for breastfeeding, infant nutrition, mother-infant contact, supervision and treatment planning. The documentation must explain this pathway clearly rather than simply writing risk to infant.

The infant's safety needs immediate action. The baby is three days old, has not been reviewed by paediatrics, and no child protection notification has been made. I would arrange paediatric review, assess feeding and hydration, clarify safe mother-infant contact, and consult or notify child protection according to local thresholds.

The cultural safety failure is also immediate. Sofia is an Aboriginal woman who has repeatedly asked for her aunt to be called, and the aunt has not been contacted. I would contact the aunt urgently and involve Aboriginal liaison or cultural support where available. This is not separate from legal care; it may reduce distress, improve engagement and support a less restrictive plan.

I would not approve the registrar's form in its current state. I would supervise Dr Park to rewrite it with factual observations, Sofia's words, capacity reasoning, infant-safety plan, cultural-support steps, less restrictive alternatives, and the rationale for detention if it remains necessary. The purpose is to protect Sofia's legal rights, the infant's safety and the service's ability to justify compulsory care.`,
  },
];
