import type { QuizStem } from "../quizData";

export const GOV_STEMS: QuizStem[] = [
  {
    id: "GOV-001",
    questionNumber: "MEQ-068",
    topic: "governance",
    difficulty: "consultant",
    title: "Impaired Colleague and Mandatory Reporting",
    candidateRole: "Consultant psychiatrist, clinical director of mental health",
    setting: "Public mental health service",
    stem: `You are the clinical director of a public mental health service.

A senior registrar tells you confidentially that Dr Lane, a consultant psychiatrist, appeared intoxicated during an after-hours shift and gave confusing verbal orders for rapid tranquillisation. Nursing staff say Dr Lane smelled of alcohol and later wrote incomplete notes. One nurse says, "I was scared to question him because he is the consultant."

Dr Lane calls you the next morning and says, "I had one drink at dinner and people are exaggerating because they don't like me." He asks you not to escalate because he is going through a divorce. The hospital executive wants the matter handled quietly to avoid reputational damage.

You must decide how to respond while ensuring patient safety, fairness to Dr Lane and compliance with professional obligations.`,
    totalMarks: 22,
    signals: [
      { id: "s1", name: "Possible intoxication while practising creates immediate patient risk", category: "immediate_safety", severity: "critical", clueInStem: "A senior registrar tells you confidentially that Dr Lane, a consultant psychiatrist, appeared intoxicated during an after-hours shift and gave confusing verbal orders for rapid tranquillisation.", whyItMatters: "Missing this signal means the candidate has not protected patients from possible impaired practice during high-risk after-hours care.", modelWording: "Prioritise patient safety by assessing Dr Lane's fitness for duty and preventing further unsupervised clinical practice until the concern is clarified.", keywords: ["impaired colleague", "fitness for duty", "patient safety", "intoxication", "clinical duties", "risk"] },
      { id: "s2", name: "Confusing rapid tranquillisation orders require patient review", category: "governance", severity: "critical", clueInStem: "A senior registrar tells you confidentially that Dr Lane, a consultant psychiatrist, appeared intoxicated during an after-hours shift and gave confusing verbal orders for rapid tranquillisation.", whyItMatters: "Missing this signal means the candidate has not checked whether sedation-related orders placed patients at risk.", modelWording: "Review affected patients and medication records because confusing rapid tranquillisation orders may have created clinical harm.", keywords: ["rapid tranquillisation", "sedation", "orders", "patient review", "clinical harm"] },
      { id: "s3", name: "Hierarchy prevented staff from speaking up", category: "mdt_conflict", severity: "important", clueInStem: "One nurse says, \"I was scared to question him because he is the consultant.\"", whyItMatters: "Missing this signal means the candidate has not addressed a safety culture where staff feel unable to challenge a consultant.", modelWording: "Support staff who raised concerns and address hierarchy-related barriers because fear of questioning consultants suppresses safety escalation.", keywords: ["speaking up", "hierarchy", "staff safety", "nursing concerns", "clinical governance"] },
      { id: "s4", name: "Executive reputation pressure must not suppress reporting", category: "system_pressure", severity: "important", clueInStem: "The hospital executive wants the matter handled quietly to avoid reputational damage.", whyItMatters: "Missing this signal means the candidate has allowed organisational reputation to override patient safety and professional obligations.", modelWording: "Resist pressure to minimise the incident because reputational concern cannot override governance review or reporting duties.", keywords: ["executive pressure", "reputation", "governance process", "transparency", "professional duty"] },
      { id: "s5", name: "Dr Lane requires procedural fairness and support", category: "ethics", severity: "important", clueInStem: "Dr Lane calls you the next morning and says, \"I had one drink at dinner and people are exaggerating because they don't like me.\"", whyItMatters: "Missing this signal means the candidate has either condemned Dr Lane without inquiry or allowed his explanation to end a serious concern.", modelWording: "Ensure procedural fairness while separating support for Dr Lane from patient safety and reporting duties.", keywords: ["procedural fairness", "natural justice", "colleague support", "non-punitive", "confidentiality"] },
      { id: "s6", name: "Incomplete notes threaten continuity and audit trail", category: "governance", severity: "important", clueInStem: "Nursing staff say Dr Lane smelled of alcohol and later wrote incomplete notes.", whyItMatters: "Missing this signal means the candidate has not secured the clinical record needed for safe follow-up and review.", modelWording: "Secure relevant notes, medication records and incident reports because incomplete documentation increases clinical and medico-legal risk.", keywords: ["documentation", "incident report", "sedation orders", "medication record", "audit trail"] },
      { id: "s7", name: "Personal stress may indicate impairment support needs", category: "ethics", severity: "important", clueInStem: "He asks you not to escalate because he is going through a divorce.", whyItMatters: "Missing this signal means the candidate has ignored a possible wellbeing contributor while still needing to prevent personal circumstances being used to avoid escalation.", modelWording: "Offer appropriate wellbeing and impairment support because divorce may be relevant to functioning but does not remove safety obligations.", keywords: ["divorce", "wellbeing", "impairment pathway", "support", "occupational health", "fitness for work"] },
    ],
    priorityOrder: { urgent: ["s1", "s2"], secondary: ["s3", "s4", "s5", "s6", "s7"], lowYield: [] },
    modelAnswer: `This is a patient-safety and professional-governance concern before it is a collegial dispute. Dr Lane reportedly appeared intoxicated while working after hours and gave confusing rapid tranquillisation orders, so I would first protect patients by ensuring he is not providing further unsupervised care until fitness for duty is clarified. I would also review patients affected by his orders, including medication charts, observations and any adverse outcomes.

The incomplete notes and the reports from nursing staff must be secured as part of a factual review. I would not allow retrospective alteration of the record, but appropriate addenda and incident reporting should occur. The nurse's statement that she was scared to question him because he is the consultant also requires action, because hierarchy that prevents escalation is itself a safety risk.

Dr Lane is entitled to procedural fairness. His account that he had one drink and that people are exaggerating should be heard, but it cannot end the inquiry. I would meet him, state the concerns factually, offer occupational health or impairment-pathway support, and recognise the stress of his divorce while making clear that support does not replace patient-safety action.

The hospital executive's wish to handle the matter quietly to avoid reputational damage must not determine the response. I would follow governance processes, consider mandatory notification obligations depending on the facts and jurisdiction, and document the rationale for actions taken. The consultant task is to hold patient safety, natural justice, staff support and professional obligations together.`,
  },
  {
    id: "GOV-002",
    questionNumber: "MEQ-069",
    topic: "governance",
    difficulty: "consultant",
    title: "Serious Medication Error and Open Disclosure",
    candidateRole: "Consultant psychiatrist, inpatient unit clinical lead",
    setting: "Acute psychiatric inpatient ward",
    stem: `You are the consultant psychiatrist leading an acute inpatient ward.

A 54-year-old woman, Helen, was inadvertently given clozapine 300 mg at night instead of quetiapine 300 mg due to a medication chart transcription error. She became hypotensive, fell overnight and sustained a fractured wrist. The night nurse says, "I thought pharmacy had checked it." The registrar says he copied the medication list from a previous discharge summary without confirming it.

Helen's daughter arrives angry and says, "No one told us this was your mistake." The hospital risk manager asks you to prepare for open disclosure but warns that "we should avoid admitting liability." Staff are distressed and blaming each other.

You are asked to manage the immediate clinical consequences and lead the incident response.`,
    totalMarks: 22,
    signals: [
      { id: "s1", name: "Wrong clozapine administration caused immediate harm", category: "immediate_safety", severity: "critical", clueInStem: "A 54-year-old woman, Helen, was inadvertently given clozapine 300 mg at night instead of quetiapine 300 mg due to a medication chart transcription error.", whyItMatters: "Missing this signal means the candidate has not recognised a high-risk antipsychotic medication error requiring urgent clinical response.", modelWording: "Prioritise Helen's clinical stabilisation because she received clozapine instead of quetiapine and may have ongoing adverse effects.", keywords: ["medication error", "clozapine", "quetiapine", "clinical review", "adverse event"] },
      { id: "s2", name: "Hypotension and fracture require medical management", category: "physical_health", severity: "critical", clueInStem: "She became hypotensive, fell overnight and sustained a fractured wrist.", whyItMatters: "Missing this signal means the candidate has focused on incident process before treating the patient's actual injury and physiological risk.", modelWording: "Arrange urgent medical review, observations, falls management and fracture care because the error has already caused physical harm.", keywords: ["hypotension", "fractured wrist", "fall", "medical review", "observations"] },
      { id: "s3", name: "Family has not received timely open disclosure", category: "governance", severity: "critical", clueInStem: "Helen's daughter arrives angry and says, \"No one told us this was your mistake.\"", whyItMatters: "Missing this signal means the candidate has not addressed the communication failure that compounds harm and undermines trust.", modelWording: "Conduct timely open disclosure with Helen and her daughter because they deserve a factual explanation, apology and plan.", keywords: ["open disclosure", "apology", "transparency", "family communication", "adverse event"] },
      { id: "s4", name: "Pharmacy-check assumption shows failed safety barriers", category: "governance", severity: "important", clueInStem: "The night nurse says, \"I thought pharmacy had checked it.\"", whyItMatters: "Missing this signal means the candidate has blamed one person rather than examining the failed prescribing, pharmacy and administration checks.", modelWording: "Review the checking system because assuming pharmacy had checked the chart shows unclear medication-safety ownership.", keywords: ["systems error", "root cause analysis", "medication safety", "transcription error", "blame culture"] },
      { id: "s5", name: "Registrar copied medication list without reconciliation", category: "governance", severity: "important", clueInStem: "The registrar says he copied the medication list from a previous discharge summary without confirming it.", whyItMatters: "Missing this signal means the candidate has not identified unsafe medication reconciliation and prescribing practice requiring supervision.", modelWording: "Review registrar prescribing practice and supervision because copying an old medication list without confirmation is unsafe reconciliation.", keywords: ["supervision", "prescribing safety", "medication reconciliation", "registrar", "remediation"] },
      { id: "s6", name: "Liability concern must not prevent honest disclosure", category: "ethics", severity: "important", clueInStem: "The hospital risk manager asks you to prepare for open disclosure but warns that \"we should avoid admitting liability.\"", whyItMatters: "Missing this signal means the candidate has allowed legal anxiety to dilute honest patient-centred disclosure.", modelWording: "Provide factual disclosure and apology without speculation because avoiding liability does not mean avoiding truth.", keywords: ["liability", "truthfulness", "ethics", "open disclosure", "factual communication"] },
      { id: "s7", name: "Staff blame requires just-culture containment", category: "mdt_conflict", severity: "important", clueInStem: "Staff are distressed and blaming each other.", whyItMatters: "Missing this signal means the candidate has not contained team distress or prevented blame from blocking learning.", modelWording: "Support staff debriefing and psychological safety while maintaining accountability because blame will impair incident learning.", keywords: ["staff debrief", "psychological safety", "team conflict", "accountability", "patient safety"] },
    ],
    priorityOrder: { urgent: ["s1", "s2", "s3"], secondary: ["s4", "s5", "s6", "s7"], lowYield: [] },
    modelAnswer: `Helen's case is a serious medication error with actual harm. She received clozapine instead of quetiapine, then became hypotensive, fell and sustained a fractured wrist. I would first ensure medical review, observations, falls management, fracture care, monitoring for ongoing adverse effects and correction of the medication chart so the error is not repeated.

Helen and her daughter require timely open disclosure. The daughter's statement, "No one told us this was your mistake," shows that communication has already failed. I would explain the known facts, apologise for the error and harm, outline the immediate clinical plan and describe the review process without speculating beyond what is known.

The risk manager's advice to avoid admitting liability should not become avoidance of honesty. Open disclosure can be factual and careful while still being transparent. Patients and families should not receive vague or defensive language after a clear medication error.

The review must examine systems as well as individual practice. The nurse thought pharmacy had checked the chart, and the registrar copied a previous medication list without confirming it. Staff are distressed and blaming each other, so I would use a just-culture approach that addresses prescribing supervision, medication reconciliation, pharmacy and nursing checks, documentation and staff support.`,
  },
  {
    id: "GOV-003",
    questionNumber: "MEQ-070",
    topic: "governance",
    difficulty: "consultant",
    title: "Executive Pressure to Discharge Unsafe Patient",
    candidateRole: "Consultant psychiatrist, acute inpatient unit",
    setting: "Overcrowded metropolitan inpatient service",
    stem: `You are the consultant psychiatrist on an acute inpatient unit during severe bed pressure.

Tariq is a 32-year-old man with schizoaffective disorder admitted after threatening his ex-partner while believing she was "infected by demons." He remains guarded, intermittently hostile and has refused family meetings. Yesterday he told a nurse, "When I leave, I know where she lives."

The hospital executive director phones you and says, "We need this bed today; ED is breaching targets and he is no longer floridly psychotic." The bed manager suggests discharge to temporary accommodation with crisis follow-up. The registrar is uncomfortable but says, "Maybe we can document that he denies intent."

Tariq's ex-partner has an active family violence order and has not been contacted because staff are unsure about confidentiality.`,
    totalMarks: 22,
    signals: [
      { id: "s1", name: "Direct threat identifies a foreseeable victim", category: "risk_others", severity: "critical", clueInStem: "Yesterday he told a nurse, \"When I leave, I know where she lives.\"", whyItMatters: "Missing this signal means the candidate has treated a specific threat toward an identifiable ex-partner as routine discharge uncertainty.", modelWording: "Treat the statement as a specific dynamic risk to an identifiable person because Tariq has named access to the ex-partner after discharge.", keywords: ["specific threat", "identifiable victim", "violence risk", "dynamic risk", "duty to protect", "family violence"] },
      { id: "s2", name: "Executive pressure is compromising clinical independence", category: "system_pressure", severity: "critical", clueInStem: "The hospital executive director phones you and says, \"We need this bed today; ED is breaching targets and he is no longer floridly psychotic.\"", whyItMatters: "Missing this signal means the candidate has allowed access targets to replace a clinical violence-risk formulation.", modelWording: "Maintain clinical independence and refuse discharge if risk cannot be safely managed despite executive pressure to free the bed.", keywords: ["executive pressure", "bed pressure", "clinical independence", "unsafe discharge", "risk management"] },
      { id: "s3", name: "Denial of intent would be false reassurance", category: "risk_others", severity: "important", clueInStem: "The registrar is uncomfortable but says, \"Maybe we can document that he denies intent.\"", whyItMatters: "Missing this signal means the candidate has accepted a denial-based discharge rationale despite recent threats and guarded hostility.", modelWording: "Do not rely on denial of intent because recent threats, guardedness and family violence context indicate ongoing risk.", keywords: ["denial of intent", "contextual risk", "guardedness", "violence formulation", "discharge risk"] },
      { id: "s4", name: "Family violence order requires victim-safety planning", category: "risk_vulnerable", severity: "important", clueInStem: "Tariq's ex-partner has an active family violence order and has not been contacted because staff are unsure about confidentiality.", whyItMatters: "Missing this signal means the candidate has ignored a legal marker of risk and failed to consider lawful victim protection.", modelWording: "Consider family violence liaison and lawful information sharing because an active order and direct threat create victim-safety obligations.", keywords: ["family violence", "victim safety", "information sharing", "confidentiality", "protective action"] },
      { id: "s5", name: "Temporary accommodation plan does not manage the violence pathway", category: "disposition", severity: "important", clueInStem: "The bed manager suggests discharge to temporary accommodation with crisis follow-up.", whyItMatters: "Missing this signal means the candidate has accepted a generic discharge plan that does not address access to the ex-partner, treatment adherence or police liaison.", modelWording: "Reject generic temporary accommodation unless it specifically manages victim access, treatment engagement and family violence safety.", keywords: ["temporary accommodation", "crisis follow-up", "discharge planning", "violence risk", "treatment adherence"] },
      { id: "s6", name: "Ongoing guarded hostility indicates unresolved dynamic risk", category: "diagnosis_formulation", severity: "important", clueInStem: "He remains guarded, intermittently hostile and has refused family meetings.", whyItMatters: "Missing this signal means the candidate has accepted that he is no longer floridly psychotic without assessing ongoing hostility, secrecy and lack of collaboration.", modelWording: "Reassess current mental state and engagement because guarded hostility and refusal of family meetings make risk less manageable.", keywords: ["guarded", "hostile", "family meetings", "dynamic risk", "engagement", "formulation"] },
      { id: "s7", name: "Documentation must record pressure and protective actions", category: "governance", severity: "important", clueInStem: "The hospital executive director phones you and says, \"We need this bed today; ED is breaching targets and he is no longer floridly psychotic.\"", whyItMatters: "Missing this signal means the candidate has not created a defensible record of clinical reasoning under organisational pressure.", modelWording: "Document the executive pressure, risk formulation and protective actions because the rationale will need to withstand governance scrutiny.", keywords: ["documentation", "targets", "defensible decision", "governance", "adverse outcome", "clinical reasoning"] },
    ],
    priorityOrder: { urgent: ["s1", "s2"], secondary: ["s3", "s4", "s5", "s6", "s7"], lowYield: [] },
    modelAnswer: `Tariq should not be discharged simply because the hospital needs the bed. He told a nurse, "When I leave, I know where she lives," which is a direct threat toward an identifiable ex-partner. This must be read with his recent psychotic belief that she was "infected by demons," his guarded hostility and his refusal of family meetings.

The executive pressure is clear. ED targets and bed pressure are real service problems, but they do not remove the consultant's obligation to make an independent clinical decision. No longer being floridly psychotic is not the same as being safe for discharge when a specific family-violence threat remains.

The registrar's suggestion to document denial of intent is unsafe reasoning. Denial does not override a direct threat, particularly when the patient is guarded and there is an active family violence order. I would supervise the registrar to document a formulation rather than a single reassuring phrase.

Temporary accommodation with crisis follow-up is inadequate unless it manages the violence pathway: distance from the ex-partner, transport, police or family-violence liaison, medication adherence and what happens if he disengages. My documentation would record the executive pressure, confidentiality reasoning, victim-safety steps and why the chosen disposition is the least restrictive safe option.`,
  },
  {
    id: "GOV-004",
    questionNumber: "MEQ-071",
    topic: "governance",
    difficulty: "consultant",
    title: "Registrar Working Beyond Competence",
    candidateRole: "Consultant psychiatrist, training supervisor and unit consultant",
    setting: "Regional inpatient and emergency psychiatry service",
    stem: `You are the consultant psychiatrist supervising a Stage 1 registrar in a regional service.

Over two weeks, several nurses report that the registrar has been making independent decisions overnight without calling for help, including discharging a suicidal patient from ED and prescribing rapid tranquillisation without physical observations. The registrar says, "I thought consultants expected us to cope independently."

Last night a patient required ICU transfer after oversedation. The registrar did not call you until after the transfer and later documented, "Consultant aware," although you had not been contacted. The NUM says staff have lost confidence and now bypass the registrar.

The director of training asks you to manage the patient safety issue while supporting the registrar's training.`,
    totalMarks: 22,
    signals: [
      { id: "s1", name: "Oversedation with ICU transfer requires immediate safety response", category: "immediate_safety", severity: "critical", clueInStem: "Last night a patient required ICU transfer after oversedation.", whyItMatters: "Missing this signal means the candidate has not recognised actual harm requiring urgent review of affected patients and current registrar duties.", modelWording: "Prioritise patient safety by reviewing the adverse event and restricting independent high-risk decisions until competence is assured.", keywords: ["patient harm", "ICU transfer", "oversedation", "scope of practice", "patient safety", "supervision"] },
      { id: "s2", name: "False consultant-aware documentation is a professionalism concern", category: "governance", severity: "critical", clueInStem: "The registrar did not call you until after the transfer and later documented, \"Consultant aware,\" although you had not been contacted.", whyItMatters: "Missing this signal means the candidate has minimised an inaccurate record that misrepresents consultant involvement after serious harm.", modelWording: "Address the inaccurate documentation directly because 'Consultant aware' was false and creates medico-legal and professionalism risk.", keywords: ["false documentation", "professionalism", "medico-legal", "clinical record", "governance", "integrity"] },
      { id: "s3", name: "Registrar misunderstood escalation expectations", category: "governance", severity: "important", clueInStem: "The registrar says, \"I thought consultants expected us to cope independently.\"", whyItMatters: "Missing this signal means the candidate has not addressed a supervision culture that may have discouraged appropriate escalation.", modelWording: "Clarify supervision expectations and escalation thresholds because a Stage 1 registrar should not infer independence for high-risk decisions.", keywords: ["supervision", "escalation thresholds", "Stage 1 registrar", "training", "after-hours", "competence"] },
      { id: "s4", name: "Rapid tranquillisation without observations is unsafe practice", category: "physical_health", severity: "important", clueInStem: "Over two weeks, several nurses report that the registrar has been making independent decisions overnight without calling for help, including discharging a suicidal patient from ED and prescribing rapid tranquillisation without physical observations.", whyItMatters: "Missing this signal means the candidate has not addressed a medication-safety breach that may have contributed to serious harm.", modelWording: "Review rapid tranquillisation practice and embed mandatory physical monitoring because sedation without observations is unsafe.", keywords: ["rapid tranquillisation", "physical observations", "sedation safety", "monitoring", "medication safety"] },
      { id: "s5", name: "Pattern of independent high-risk decisions shows scope problem", category: "governance", severity: "critical", clueInStem: "Over two weeks, several nurses report that the registrar has been making independent decisions overnight without calling for help, including discharging a suicidal patient from ED and prescribing rapid tranquillisation without physical observations.", whyItMatters: "Missing this signal means the candidate has treated the ICU transfer as a single error rather than part of repeated unsafe independent practice.", modelWording: "Review the two-week pattern of independent decisions because repeated high-risk actions suggest a scope-of-practice and supervision failure.", keywords: ["pattern", "independent decisions", "overnight", "suicidal discharge", "scope", "competence"] },
      { id: "s6", name: "Team bypassing the registrar fragments care", category: "mdt_conflict", severity: "important", clueInStem: "The NUM says staff have lost confidence and now bypass the registrar.", whyItMatters: "Missing this signal means the candidate has not restored clear roles after the MDT lost confidence in the registrar.", modelWording: "Restore team safety by clarifying roles, escalation pathways and supervised decision-making arrangements.", keywords: ["team confidence", "bypassing", "MDT", "role clarity", "communication", "safety culture"] },
      { id: "s7", name: "Training support must be paired with patient protection", category: "ethics", severity: "important", clueInStem: "The director of training asks you to manage the patient safety issue while supporting the registrar's training.", whyItMatters: "Missing this signal means the candidate has either punished the registrar without remediation or prioritised training over patient safety.", modelWording: "Develop a remediation and supervision plan because the registrar needs support while patients are protected from unsafe independent practice.", keywords: ["remediation", "training support", "fairness", "competence", "supervision plan", "education"] },
    ],
    priorityOrder: { urgent: ["s1", "s2", "s5"], secondary: ["s3", "s4", "s6", "s7"], lowYield: [] },
    modelAnswer: `This requires immediate patient-safety action and a supervision response. A patient required ICU transfer after oversedation, so I would first review that patient and any others affected by recent overnight decisions. I would temporarily restrict the registrar from independent high-risk after-hours decisions until competence and supervision arrangements are clarified.

The issue is a pattern, not one isolated error. Nurses have reported independent overnight decisions over two weeks, including discharge of a suicidal patient and rapid tranquillisation without physical observations. That suggests a scope-of-practice and supervision failure.

The documentation issue is serious. The registrar wrote "Consultant aware" although I had not been contacted. I would require correction through a proper addendum and address it as a professionalism and governance concern.

The registrar's belief that consultants expected independent coping suggests unsafe escalation culture. I would set mandatory escalation thresholds, meet the NUM to restore role clarity, and develop a remediation plan with closer supervision, case review, prescribing teaching and observed assessments. Supporting training must occur alongside protecting patients.`,
  },
  {
    id: "GOV-005",
    questionNumber: "MEQ-072",
    topic: "governance",
    difficulty: "consultant",
    title: "Coronial Inquiry and Defensible Documentation",
    candidateRole: "Consultant psychiatrist, community mental health team clinical lead",
    setting: "Community mental health service after patient death",
    stem: `You are the consultant psychiatrist clinical lead of a community mental health team.

Daniel, a 41-year-old man with recurrent depression and alcohol dependence, died by suicide two days after discharge from crisis team follow-up. The file notes state "denies suicidal ideation, low risk," but there is no documented formulation. His partner had phoned the team the day before death saying, "He has given away his tools and keeps saying we'll be better off without him."

A junior clinician documented the call as "partner anxious" and no senior review occurred. The family has requested records and says, "You ignored our warning." The service manager tells you a coronial investigation is likely and asks you to review the case.

Staff are distressed and worried about blame. You must lead the immediate response, documentation review and service learning process.`,
    totalMarks: 22,
    signals: [
      { id: "s1", name: "Partner reported preparatory behaviour and burdensomeness", category: "collateral", severity: "critical", clueInStem: "His partner had phoned the team the day before death saying, \"He has given away his tools and keeps saying we'll be better off without him.\"", whyItMatters: "Missing this signal means the candidate has not recognised family collateral describing dynamic warning signs immediately before death.", modelWording: "Identify the partner's collateral as significant dynamic risk because giving away tools and burdensomeness required senior review.", keywords: ["collateral warning", "preparatory behaviour", "burdensomeness", "suicide risk", "senior review", "family call"] },
      { id: "s2", name: "Denial-based low-risk note was not a formulation", category: "governance", severity: "critical", clueInStem: "The file notes state \"denies suicidal ideation, low risk,\" but there is no documented formulation.", whyItMatters: "Missing this signal means the candidate has accepted a risk label that failed to reconcile denial with behaviour, collateral and context.", modelWording: "Critique the denial-based low-risk note because defensible documentation requires synthesis of collateral, behaviour and context.", keywords: ["risk formulation", "denial of suicidal ideation", "documentation", "defensibility", "coronial inquiry", "low risk"] },
      { id: "s3", name: "Death occurred in high-risk post-discharge period", category: "disposition", severity: "critical", clueInStem: "Daniel, a 41-year-old man with recurrent depression and alcohol dependence, died by suicide two days after discharge from crisis team follow-up.", whyItMatters: "Missing this signal means the candidate has not linked the death to the need to review transition planning after crisis-team discharge.", modelWording: "Review the crisis-team discharge plan because death two days later occurred during a high-risk transition period.", keywords: ["post-discharge", "crisis team", "transition", "suicide", "follow-up", "disposition"] },
      { id: "s4", name: "Partner's warning was minimised by junior triage", category: "governance", severity: "important", clueInStem: "A junior clinician documented the call as \"partner anxious\" and no senior review occurred.", whyItMatters: "Missing this signal means the candidate has not identified the triage and escalation failure that converted warning information into reassurance.", modelWording: "Review escalation processes because documenting the caller as anxious without senior review minimised clinically significant warning signs.", keywords: ["senior review", "escalation failure", "service process", "clinical governance", "risk call"] },
      { id: "s5", name: "Family requires compassionate response and postvention", category: "family_carer", severity: "important", clueInStem: "The family has requested records and says, \"You ignored our warning.\"", whyItMatters: "Missing this signal means the candidate has focused on defensibility rather than family distress, communication and postvention duties.", modelWording: "Provide compassionate family contact and explain the review process because the family experienced their warning as ignored.", keywords: ["postvention", "family communication", "open disclosure", "complaint", "bereavement", "transparency"] },
      { id: "s6", name: "Coronial process requires record preservation and factual review", category: "governance", severity: "important", clueInStem: "The service manager tells you a coronial investigation is likely and asks you to review the case.", whyItMatters: "Missing this signal means the candidate has not protected the integrity of records and review processes once coronial scrutiny is likely.", modelWording: "Preserve records and coordinate information release through legal and governance processes because coronial investigation is likely.", keywords: ["coronial investigation", "records request", "preserve records", "legal process", "documentation review"] },
      { id: "s7", name: "Staff distress requires just-culture leadership", category: "mdt_conflict", severity: "important", clueInStem: "Staff are distressed and worried about blame.", whyItMatters: "Missing this signal means the candidate has not supported staff while still requiring honest analysis of decision-making and systems failures.", modelWording: "Use a just-culture approach because staff need support while the service examines documentation, escalation and discharge processes.", keywords: ["just culture", "staff support", "blame", "debrief", "systems learning", "psychological safety"] },
    ],
    priorityOrder: { urgent: ["s1", "s2", "s3"], secondary: ["s4", "s5", "s6", "s7"], lowYield: [] },
    modelAnswer: `Daniel's death must be managed as a serious incident with likely external scrutiny. He died two days after discharge from crisis team follow-up, so the review must examine the discharge plan, transition supports, alcohol-risk management and follow-up arrangements.

The partner's phone call was clinically important. She said he had given away his tools and kept saying they would be better off without him. That collateral should have been treated as dynamic risk information requiring senior review, not recorded simply as an anxious family call.

The file note "denies suicidal ideation, low risk" is not a defensible formulation. It does not integrate family collateral, recurrent depression, alcohol dependence, recent crisis-team discharge or behavioural warning signs. The review should identify this as a documentation and formulation failure rather than pretending risk assessment was adequate because denial was recorded.

The family require compassionate contact, explanation of the review process and appropriate postvention support. Records should be preserved and any release managed through governance and legal channels because a coronial investigation is likely. Staff are distressed and worried about blame, so I would lead a just-culture review that supports them while still examining escalation, documentation and discharge-process failures honestly.`,
  },
];
