import type { QuizStem } from "../quizData";

export const OA_STEMS: QuizStem[] = [
  {
    id: "OA-001",
    questionNumber: "MEQ-100",
    topic: "old_age",
    difficulty: "consultant",
    title: "Dementia, driving, EPOA conflict and elder financial abuse",
    candidateRole: "Consultant old age psychiatrist, memory clinic",
    setting: "Outpatient memory clinic with family meeting",
    stem: `You are the consultant old age psychiatrist reviewing Mrs Chen, an 82-year-old Mandarin-speaking woman with moderate dementia.

Her daughter, who holds enduring power of attorney, asks you to write a letter saying Mrs Chen lacks capacity so the family can sell her car and transfer the house "before the nursing home takes everything." Mrs Chen says through her son, who is interpreting, "My daughter only wants my money." The son says his sister has recently changed bank access and stopped Mrs Chen attending mah-jong with friends.

Mrs Chen was reported to police after reversing into a parked car and driving away. She says, "I have driven for fifty years; no doctor can take my keys." The GP has asked for advice about driving, finances and whether elder abuse is occurring.`,
    totalMarks: 22,
    signals: [
      { id: "s1", name: "Mandarin language need requires professional interpretation", category: "cultural_safety", severity: "critical", clueInStem: "You are the consultant old age psychiatrist reviewing Mrs Chen, an 82-year-old Mandarin-speaking woman with moderate dementia.", whyItMatters: "Missing this signal means capacity, abuse and driving assessment may be invalid because language need is central.", modelWording: "Use a professional Mandarin interpreter because decision-making and abuse concerns cannot be assessed reliably through family.", keywords: ["Mandarin", "interpreter", "capacity", "elder abuse"] },
      { id: "s2", name: "EPOA request creates financial conflict of interest", category: "risk_vulnerable", severity: "critical", clueInStem: "Her daughter, who holds enduring power of attorney, asks you to write a letter saying Mrs Chen lacks capacity so the family can sell her car and transfer the house \"before the nursing home takes everything.\"", whyItMatters: "Missing this signal means the clinician may be used to facilitate asset transfer rather than independent capacity assessment.", modelWording: "Maintain independence and assess for financial abuse because the EPOA request is linked to selling assets.", keywords: ["EPOA", "financial abuse", "assets", "capacity letter"] },
      { id: "s3", name: "Son interpreting is conflicted collateral", category: "collateral", severity: "important", clueInStem: "Mrs Chen says through her son, who is interpreting, \"My daughter only wants my money.\"", whyItMatters: "Missing this signal means a family member involved in the dispute controls Mrs Chen's voice.", modelWording: "Interview Mrs Chen separately with an interpreter because son-mediated interpretation is conflicted in a financial dispute.", keywords: ["son interpreting", "conflict", "separate interview"] },
      { id: "s4", name: "Bank access change may indicate financial abuse", category: "risk_vulnerable", severity: "critical", clueInStem: "The son says his sister has recently changed bank access and stopped Mrs Chen attending mah-jong with friends.", whyItMatters: "Missing this signal means possible financial control and coercive isolation remain unassessed.", modelWording: "Investigate changed bank access because it may indicate financial exploitation or coercive control.", keywords: ["bank access", "financial abuse", "coercive control"] },
      { id: "s5", name: "Loss of mah-jong may be coercive social isolation", category: "family_carer", severity: "important", clueInStem: "The son says his sister has recently changed bank access and stopped Mrs Chen attending mah-jong with friends.", whyItMatters: "Missing this signal means the plan may protect finances while ignoring social participation and autonomy.", modelWording: "Assess loss of mah-jong access because social restriction may be elder abuse or an avoidable consequence of safety concerns.", keywords: ["mah-jong", "social isolation", "autonomy"] },
      { id: "s6", name: "Driving incident creates public safety risk", category: "risk_others", severity: "critical", clueInStem: "Mrs Chen was reported to police after reversing into a parked car and driving away.", whyItMatters: "Missing this signal means driving risk to Mrs Chen and the public is not managed.", modelWording: "Advise immediate driving-risk action because reversing into a parked car and leaving indicates unsafe driving.", keywords: ["driving", "police", "parked car", "public safety"] },
      { id: "s7", name: "Driving capacity is decision-specific", category: "capacity", severity: "important", clueInStem: "She says, \"I have driven for fifty years; no doctor can take my keys.\"", whyItMatters: "Missing this signal means the candidate may confuse long experience or strong preference with driving capacity.", modelWording: "Assess driving decision-making separately because long driving history does not remove current dementia-related safety risk.", keywords: ["driving capacity", "keys", "decision-specific"] },
      { id: "s8", name: "GP asks for several distinct opinions", category: "governance", severity: "important", clueInStem: "The GP has asked for advice about driving, finances and whether elder abuse is occurring.", whyItMatters: "Missing this signal means the response may collapse driving, finances and abuse into one global incapacity opinion.", modelWording: "Separate advice on driving, finances and elder abuse because each requires different evidence and action.", keywords: ["GP", "driving", "finances", "elder abuse"] },
    ],
    priorityOrder: { urgent: ["s1", "s2", "s4", "s6"], secondary: ["s3", "s5", "s7", "s8"], lowYield: [] },
    modelAnswer: `Mrs Chen's case is not a request for a simple dementia letter. It requires separate assessment of language, decision-specific capacity, driving risk, family conflict and possible elder financial abuse. I would arrange a professional Mandarin interpreter and interview Mrs Chen separately because using her son as interpreter is unsafe in a family dispute about money and control.

The daughter's request is a red flag. She holds enduring power of attorney and wants a letter saying Mrs Chen lacks capacity so the family can sell the car and transfer the house "before the nursing home takes everything." That may reflect anxiety about aged-care costs, but it may also represent financial conflict of interest or exploitation. I would not provide a global incapacity letter to facilitate asset transfer.

The son's information that bank access has been changed and that Mrs Chen has been stopped from attending mah-jong must be investigated. Those facts may indicate financial control and social isolation, although there may also be safety explanations. The goal is to protect Mrs Chen while preserving autonomy and cultural/social connection where possible.

Driving risk needs immediate action. Mrs Chen reversed into a parked car and drove away, and her statement that she has driven for fifty years does not answer current fitness to drive. I would advise cessation pending formal assessment or licensing review and notify relevant authorities if required.

My opinion would be limited and evidence-based. I would separately address driving capacity, financial decision-making, accommodation or health decisions, and elder-abuse concerns. I would communicate with the GP, involve social work or elder-abuse services if indicated, and document interpreter use, separate interview, family conflict, capacity domains and the limits of any letter.`,
  },
  {
    id: "OA-002",
    questionNumber: "MEQ-101",
    topic: "old_age",
    difficulty: "consultant",
    title: "Delirium missed as dementia and anticholinergic burden",
    candidateRole: "Consultant old age psychiatrist, consultation-liaison service",
    setting: "General medical ward",
    stem: `You are the old age psychiatry consultant asked to review Mr Patel, a 78-year-old man admitted with urinary retention and falls.

The ward team says he has "just got dementia" because he is confused and pulling at lines. His daughter says, "Dad was doing his own shopping last week." Medication chart shows oxybutynin, amitriptyline, diazepam and PRN promethazine. Overnight he became agitated and was physically restrained after trying to leave.

Mr Patel speaks Gujarati at home but has been assessed only in English. His wife is distressed and says, "He thinks the nurses are thieves." The medical registrar asks for risperidone to settle him so investigations can proceed.`,
    totalMarks: 22,
    signals: [
      { id: "s1", name: "Urinary retention and falls suggest medical delirium context", category: "physical_health", severity: "critical", clueInStem: "You are the old age psychiatry consultant asked to review Mr Patel, a 78-year-old man admitted with urinary retention and falls.", whyItMatters: "Missing this signal means the candidate has not linked confusion to acute medical precipitants.", modelWording: "Treat urinary retention and falls as delirium precipitants because reversible medical causes must be addressed first.", keywords: ["urinary retention", "falls", "delirium"] },
      { id: "s2", name: "Dementia label ignores acute functional change", category: "diagnosis_formulation", severity: "critical", clueInStem: "The ward team says he has \"just got dementia\" because he is confused and pulling at lines.", whyItMatters: "Missing this signal means acute delirium may be mislabelled as dementia and undertreated.", modelWording: "Challenge the dementia label because acute confusion and line-pulling require delirium assessment.", keywords: ["just got dementia", "confused", "pulling lines"] },
      { id: "s3", name: "Daughter collateral establishes recent baseline", category: "collateral", severity: "critical", clueInStem: "His daughter says, \"Dad was doing his own shopping last week.\"", whyItMatters: "Missing this signal means the strongest evidence of acute change is ignored.", modelWording: "Use the daughter's collateral because independent shopping last week strongly supports acute delirium over dementia progression.", keywords: ["daughter", "shopping last week", "baseline"] },
      { id: "s4", name: "Anticholinergic and sedative burden is high", category: "physical_health", severity: "critical", clueInStem: "Medication chart shows oxybutynin, amitriptyline, diazepam and PRN promethazine.", whyItMatters: "Missing this signal means deliriogenic medication burden remains untreated.", modelWording: "Review and reduce anticholinergic and sedative burden because these medicines can worsen delirium, falls and retention.", keywords: ["oxybutynin", "amitriptyline", "diazepam", "promethazine"] },
      { id: "s5", name: "Physical restraint may worsen delirium and harm", category: "ethics", severity: "important", clueInStem: "Overnight he became agitated and was physically restrained after trying to leave.", whyItMatters: "Missing this signal means restrictive practice may continue without review of necessity and harm.", modelWording: "Minimise restraint because physical restraint can worsen delirium, injury and fear unless strictly necessary.", keywords: ["restraint", "agitated", "trying to leave"] },
      { id: "s6", name: "Gujarati language need invalidates English-only assessment", category: "cultural_safety", severity: "critical", clueInStem: "Mr Patel speaks Gujarati at home but has been assessed only in English.", whyItMatters: "Missing this signal means cognition and distress may be inaccurately assessed.", modelWording: "Use a professional Gujarati interpreter because English-only assessment may exaggerate confusion and fear.", keywords: ["Gujarati", "English", "interpreter"] },
      { id: "s7", name: "Theft belief may reflect delirium and fear", category: "diagnosis_formulation", severity: "important", clueInStem: "His wife is distressed and says, \"He thinks the nurses are thieves.\"", whyItMatters: "Missing this signal means paranoia may be treated as primary psychosis rather than delirium-related misinterpretation.", modelWording: "Formulate the theft belief as possible delirium-related misinterpretation worsened by language and unfamiliar care.", keywords: ["nurses are thieves", "delirium", "misinterpretation"] },
      { id: "s8", name: "Risperidone request should not substitute for delirium care", category: "consent_refusal", severity: "important", clueInStem: "The medical registrar asks for risperidone to settle him so investigations can proceed.", whyItMatters: "Missing this signal means antipsychotic sedation may be used for convenience rather than severe distress or safety.", modelWording: "Use risperidone only cautiously if severe distress or danger persists because investigations alone are not a sufficient indication for sedation.", keywords: ["risperidone", "settle him", "investigations"] },
    ],
    priorityOrder: { urgent: ["s1", "s2", "s3", "s4", "s6"], secondary: ["s5", "s7", "s8"], lowYield: [] },
    modelAnswer: `Mr Patel should be treated as having delirium until proven otherwise, not as someone who has simply developed dementia. He was admitted with urinary retention and falls, is now confused and pulling at lines, and his daughter says he was doing his own shopping last week. That acute change from baseline is the core diagnostic clue.

The medication chart is a major contributor. Oxybutynin, amitriptyline, diazepam and PRN promethazine create a heavy anticholinergic and sedative burden in an older person with urinary retention and falls. I would ask the medical team to review and reduce deliriogenic medicines while treating pain, infection, constipation, dehydration, hypoxia and electrolyte causes.

The assessment has been linguistically unsafe. Mr Patel speaks Gujarati at home but has been assessed only in English. A professional Gujarati interpreter is required to assess cognition, distress, pain, fear and capacity. His wife and daughter can provide baseline and reassurance, but they should not replace professional interpretation.

The restraint episode needs review. Physical restraint after trying to leave may sometimes be necessary briefly, but it can worsen delirium, fear and injury. His belief that nurses are thieves may be delirium-related misinterpretation amplified by language barriers and unfamiliar care.

The request for risperidone to settle him should be reframed. Antipsychotics may be used in delirium only for severe distress or immediate safety risk after treating causes and using non-pharmacological care. If needed, use the lowest effective dose, monitor falls, sedation and QTc, and review daily.`,
  },
  {
    id: "OA-003",
    questionNumber: "MEQ-102",
    topic: "old_age",
    difficulty: "consultant",
    title: "CALD resident with BPSD, restraint and cultural safety",
    candidateRole: "Consultant old age psychiatrist, residential aged care outreach",
    setting: "Residential aged care facility behaviour review",
    stem: `You are the consultant old age psychiatrist visiting a residential aged care facility.

Mrs Nguyen is an 85-year-old Vietnamese-speaking woman with dementia who has been calling out at night, pushing away staff during personal care and refusing meals. Staff say, "She is aggressive and needs chemical restraint." Her daughter says, "She was a midwife in Vietnam and would be ashamed being washed by male carers."

Mrs Nguyen has been given PRN quetiapine most nights for two weeks. She has bruising on both wrists, and the facility manager says this occurred because "staff had to hold her for hygiene." No interpreter has been used. The GP asks you to approve regular antipsychotic medication because staffing levels are low.`,
    totalMarks: 22,
    signals: [
      { id: "s1", name: "Calling out, care refusal and meal refusal need unmet-need formulation", category: "diagnosis_formulation", severity: "critical", clueInStem: "Mrs Nguyen is an 85-year-old Vietnamese-speaking woman with dementia who has been calling out at night, pushing away staff during personal care and refusing meals.", whyItMatters: "Missing this signal means behaviours are labelled aggression without assessing pain, fear, hunger, sleep, delirium or communication needs.", modelWording: "Formulate behaviours as communication of unmet need because dementia behaviours often reflect distress rather than deliberate aggression.", keywords: ["BPSD", "calling out", "refusing meals", "personal care"] },
      { id: "s2", name: "Chemical restraint framing is unsafe", category: "ethics", severity: "critical", clueInStem: "Staff say, \"She is aggressive and needs chemical restraint.\"", whyItMatters: "Missing this signal means sedating medication may be used for control rather than treatment.", modelWording: "Reject chemical restraint as a rationale because antipsychotics require a clinical indication, consent and review.", keywords: ["chemical restraint", "aggressive", "antipsychotic"] },
      { id: "s3", name: "Personal care distress has cultural and gender meaning", category: "cultural_safety", severity: "critical", clueInStem: "Her daughter says, \"She was a midwife in Vietnam and would be ashamed being washed by male carers.\"", whyItMatters: "Missing this signal means culturally inappropriate personal care continues to trigger distress.", modelWording: "Use the daughter's biography to redesign care because female carers, privacy and explanation may reduce distress.", keywords: ["midwife", "Vietnam", "male carers", "modesty"] },
      { id: "s4", name: "Frequent PRN quetiapine requires medication review", category: "physical_health", severity: "important", clueInStem: "Mrs Nguyen has been given PRN quetiapine most nights for two weeks.", whyItMatters: "Missing this signal means repeated sedative use may continue without target symptoms, benefit or adverse-effect monitoring.", modelWording: "Review PRN quetiapine use because most-night administration for two weeks resembles regular chemical restraint without clear review.", keywords: ["quetiapine", "PRN", "two weeks", "medication review"] },
      { id: "s5", name: "Wrist bruising after being held is safeguarding concern", category: "risk_vulnerable", severity: "critical", clueInStem: "She has bruising on both wrists, and the facility manager says this occurred because \"staff had to hold her for hygiene.\"", whyItMatters: "Missing this signal means restraint-related injury or elder abuse may be normalised as difficult care.", modelWording: "Investigate wrist bruising as possible restraint-related harm because holding for hygiene may be excessive or unsafe.", keywords: ["bruising", "wrists", "hold her", "hygiene", "safeguarding"] },
      { id: "s6", name: "No interpreter has been used", category: "cultural_safety", severity: "important", clueInStem: "No interpreter has been used.", whyItMatters: "Missing this signal means distress, preferences and consent are being inferred without communication access.", modelWording: "Use a Vietnamese interpreter because communication failure can drive refusal, fear and mislabelling of behaviour.", keywords: ["interpreter", "Vietnamese", "communication"] },
      { id: "s7", name: "Low staffing is not an antipsychotic indication", category: "system_pressure", severity: "important", clueInStem: "The GP asks you to approve regular antipsychotic medication because staffing levels are low.", whyItMatters: "Missing this signal means workforce shortage is medicalised through sedating medication.", modelWording: "Separate staffing pressure from prescribing because low staffing cannot justify regular antipsychotic use.", keywords: ["staffing levels", "regular antipsychotic", "GP", "system pressure"] },
    ],
    priorityOrder: { urgent: ["s1", "s2", "s3", "s5"], secondary: ["s4", "s6", "s7"], lowYield: [] },
    modelAnswer: `Mrs Nguyen's behaviour should not be accepted at face value as aggression requiring sedation. Calling out at night, pushing staff away during personal care and refusing meals require an unmet-need formulation. Pain, delirium, hunger, fear, sleep disruption, language barriers and culturally inappropriate care all need assessment.

The daughter's information is central. Mrs Nguyen was a midwife in Vietnam and would be ashamed being washed by male carers. That reframes the personal care behaviour as distress around modesty, gender and dignity, not simply aggression. The care plan should prioritise female carers, privacy, explanation before touch and culturally familiar routines.

The request for chemical restraint is not acceptable as a prescribing rationale. Quetiapine has been given most nights for two weeks, which requires review of target symptoms, benefit, consent, adverse effects, falls, sedation and whether this has become de facto regular restraint.

Bruising on both wrists after staff held her for hygiene is a safeguarding concern. I would review incident reports, examine the injury pattern, speak with staff and family, and consider aged-care safeguarding or regulatory pathways if restraint-related harm or neglect is suspected.

No interpreter has been used, so the behavioural assessment is incomplete. I would arrange Vietnamese interpretation, gather life-history information from the daughter and build a non-pharmacological behaviour support plan. Low staffing should be escalated as a governance issue, not treated with regular antipsychotic medication.`,
  },
  {
    id: "OA-004",
    questionNumber: "MEQ-103",
    topic: "old_age",
    difficulty: "consultant",
    title: "Late-life depression, ECT consent and carer burnout",
    candidateRole: "Consultant old age psychiatrist, inpatient unit",
    setting: "Older adult psychiatric inpatient unit",
    stem: `You are the consultant old age psychiatrist reviewing Mr O'Brien, a 75-year-old man with severe melancholic depression and psychotic guilt.

He has lost 12 kg, is refusing food and says, "I deserve to die because I ruined my family." The team recommends ECT. Mr O'Brien says, "Do whatever my wife says; I cannot think." His wife says, "I want him better, but I can't be responsible for signing his brain away."

His adult son says ECT is "barbaric" and threatens media involvement. Mr O'Brien is Catholic and asks whether ECT is punishment. The registrar asks whether consent can be obtained from his wife because the situation is urgent.`,
    totalMarks: 22,
    signals: [
      { id: "s1", name: "Severe psychotic depression carries nutritional and suicide risk", category: "risk_self", severity: "critical", clueInStem: "You are the consultant old age psychiatrist reviewing Mr O'Brien, a 75-year-old man with severe melancholic depression and psychotic guilt.", whyItMatters: "Missing this signal means ECT is discussed without recognising the severity and urgency of the illness.", modelWording: "Treat psychotic melancholic depression as high risk because it can rapidly cause self-neglect, suicide and physical decline.", keywords: ["psychotic depression", "melancholic", "risk", "ECT"] },
      { id: "s2", name: "Weight loss and food refusal need urgent physical care", category: "physical_health", severity: "critical", clueInStem: "He has lost 12 kg, is refusing food and says, \"I deserve to die because I ruined my family.\"", whyItMatters: "Missing this signal means physical deterioration from depression-related food refusal is not managed.", modelWording: "Arrange urgent medical and nutritional support because 12 kg weight loss and food refusal create serious morbidity.", keywords: ["lost 12 kg", "refusing food", "nutrition"] },
      { id: "s3", name: "Guilt statement suggests psychotic depressive cognition", category: "diagnosis_formulation", severity: "important", clueInStem: "He has lost 12 kg, is refusing food and says, \"I deserve to die because I ruined my family.\"", whyItMatters: "Missing this signal means nihilistic or guilt delusions may be missed when assessing risk and consent.", modelWording: "Assess psychotic guilt and suicidality because the belief that he deserves death may distort treatment decisions.", keywords: ["deserve to die", "guilt", "psychosis", "suicide"] },
      { id: "s4", name: "ECT consent capacity cannot be delegated to wife", category: "capacity", severity: "critical", clueInStem: "Mr O'Brien says, \"Do whatever my wife says; I cannot think.\"", whyItMatters: "Missing this signal means the clinician may treat spouse preference as consent instead of assessing Mr O'Brien's decision-making.", modelWording: "Assess ECT capacity specifically because saying his wife should decide and that he cannot think suggests impaired decision-making.", keywords: ["ECT", "capacity", "wife", "cannot think"] },
      { id: "s5", name: "Wife is distressed by substitute decision burden", category: "family_carer", severity: "important", clueInStem: "His wife says, \"I want him better, but I can't be responsible for signing his brain away.\"", whyItMatters: "Missing this signal means the wife may be left feeling personally responsible for a legally and clinically complex treatment.", modelWording: "Support his wife and explain the legal pathway because she should not be made solely responsible for ECT authorisation.", keywords: ["wife", "signing his brain away", "ECT", "family support"] },
      { id: "s6", name: "Son's ECT misinformation and media threat need containment", category: "governance", severity: "important", clueInStem: "His adult son says ECT is \"barbaric\" and threatens media involvement.", whyItMatters: "Missing this signal means misinformation or reputational fear may delay urgent effective treatment.", modelWording: "Address the son's concerns with accurate ECT information while documenting clearly and seeking governance support if media threats escalate.", keywords: ["barbaric", "media", "ECT misinformation", "governance"] },
      { id: "s7", name: "Catholic punishment concern needs spiritual formulation", category: "cultural_safety", severity: "important", clueInStem: "Mr O'Brien is Catholic and asks whether ECT is punishment.", whyItMatters: "Missing this signal means religious guilt may be dismissed rather than understood as part of depression and engagement.", modelWording: "Offer spiritual support and explain ECT as treatment because Catholic guilt and punishment concerns may be illness-amplified.", keywords: ["Catholic", "punishment", "chaplain", "ECT"] },
      { id: "s8", name: "Urgency does not remove ECT legal safeguards", category: "consent_refusal", severity: "critical", clueInStem: "The registrar asks whether consent can be obtained from his wife because the situation is urgent.", whyItMatters: "Missing this signal means urgent need may bypass jurisdiction-specific ECT consent safeguards.", modelWording: "Clarify ECT legal requirements because urgency does not allow informal spouse consent if statutory safeguards apply.", keywords: ["registrar", "wife consent", "urgent", "legal safeguards"] },
    ],
    priorityOrder: { urgent: ["s1", "s2", "s4", "s8"], secondary: ["s3", "s5", "s6", "s7"], lowYield: [] },
    modelAnswer: `Mr O'Brien is severely unwell with melancholic depression and psychotic guilt. He has lost 12 kg, is refusing food and says, "I deserve to die because I ruined my family." This creates urgent psychiatric and physical risk, including malnutrition, self-neglect and suicide risk. ECT is clinically appropriate to consider urgently.

Consent cannot simply be obtained from his wife because he says, "Do whatever my wife says; I cannot think." That statement raises concern about impaired capacity, not valid delegation. I would assess his capacity to consent to ECT specifically, including understanding, retention, weighing, communication and the effect of psychotic guilt on decision-making.

His wife needs support, not the burden of feeling she is signing his brain away. Her views about his values and wishes are important, but the legal pathway for ECT must be followed if he lacks capacity. The registrar should be taught that urgency does not remove statutory safeguards.

The son's view that ECT is barbaric and his media threat require calm communication, not avoidance of necessary care. I would offer a family meeting to explain ECT, benefits, cognitive risks, alternatives and monitoring, while documenting the clinical reasoning and involving governance support if needed.

Mr O'Brien's Catholic concern that ECT is punishment should be explored. It may reflect spiritual distress and psychotic guilt. I would offer chaplaincy and explain that ECT is treatment, not punishment. The final plan should protect autonomy, legal safeguards, physical safety and family trust.`,
  },
  {
    id: "OA-005",
    questionNumber: "MEQ-104",
    topic: "old_age",
    difficulty: "consultant",
    title: "End-of-life refusal, family conflict and capacity",
    candidateRole: "Consultant old age psychiatrist, consultation-liaison service",
    setting: "Palliative oncology ward",
    stem: `You are the old age psychiatrist asked to assess Mrs Davies, an 80-year-old woman with metastatic ovarian cancer and bowel obstruction.

The surgical team offers high-risk palliative surgery, but Mrs Davies says, "I have had enough; I want comfort care only." Her son says, "She is depressed and you must make her have the operation." Her daughter says their mother has always valued independence and previously said she would not want burdensome treatment.

Mrs Davies is mildly drowsy on opioids but can describe the surgery, the possibility of dying without it and says, "More days in ICU is not living." The family asks you to declare her incapable because they cannot agree. Mrs Davies is a devout Buddhist and asks to speak with her monk before finalising decisions.`,
    totalMarks: 22,
    signals: [
      { id: "s1", name: "Refusal concerns high-risk palliative surgery", category: "capacity", severity: "critical", clueInStem: "The surgical team offers high-risk palliative surgery, but Mrs Davies says, \"I have had enough; I want comfort care only.\"", whyItMatters: "Missing this signal means the candidate has not recognised a high-stakes but potentially valid end-of-life refusal.", modelWording: "Assess capacity for the specific palliative-surgery decision because a capacitous person may refuse life-prolonging treatment.", keywords: ["palliative surgery", "comfort care", "capacity", "refusal"] },
      { id: "s2", name: "Son's depression claim may pressure invalid override", category: "family_carer", severity: "important", clueInStem: "Her son says, \"She is depressed and you must make her have the operation.\"", whyItMatters: "Missing this signal means family distress may be mistaken for evidence of incapacity.", modelWording: "Screen for depression without assuming refusal is depressive because the son's distress does not determine capacity.", keywords: ["son", "depressed", "operation", "family pressure"] },
      { id: "s3", name: "Daughter collateral supports values-consistent refusal", category: "collateral", severity: "important", clueInStem: "Her daughter says their mother has always valued independence and previously said she would not want burdensome treatment.", whyItMatters: "Missing this signal means prior values supporting refusal are ignored.", modelWording: "Use daughter collateral about independence and burdensome treatment because it may show the refusal is values-consistent.", keywords: ["daughter", "independence", "burdensome treatment", "values"] },
      { id: "s4", name: "Opioid drowsiness should be optimised but not equated with incapacity", category: "physical_health", severity: "important", clueInStem: "Mrs Davies is mildly drowsy on opioids but can describe the surgery, the possibility of dying without it and says, \"More days in ICU is not living.\"", whyItMatters: "Missing this signal means mild sedation may be overused to invalidate a decision or ignored when timing assessment.", modelWording: "Optimise alertness for assessment because opioid drowsiness may affect but does not prove incapacity.", keywords: ["opioids", "drowsy", "capacity", "alertness"] },
      { id: "s5", name: "She can describe surgery and death risk", category: "capacity", severity: "critical", clueInStem: "Mrs Davies is mildly drowsy on opioids but can describe the surgery, the possibility of dying without it and says, \"More days in ICU is not living.\"", whyItMatters: "Missing this signal means evidence of understanding and values-based weighing is not recognised.", modelWording: "Document her understanding and weighing because describing surgery and death risk supports capacity if consistent and uncoerced.", keywords: ["describe surgery", "dying", "ICU", "weighing"] },
      { id: "s6", name: "Family disagreement is not incapacity", category: "ethics", severity: "critical", clueInStem: "The family asks you to declare her incapable because they cannot agree.", whyItMatters: "Missing this signal means capacity assessment is misused to resolve family conflict.", modelWording: "Refuse to use capacity assessment to settle family disagreement because incapacity must be based on Mrs Davies' decision-making, not relatives' conflict.", keywords: ["family disagreement", "declare incapable", "ethics", "capacity"] },
      { id: "s7", name: "Buddhist spiritual support may aid decision-making", category: "cultural_safety", severity: "important", clueInStem: "Mrs Davies is a devout Buddhist and asks to speak with her monk before finalising decisions.", whyItMatters: "Missing this signal means spiritual support relevant to end-of-life values may be overlooked.", modelWording: "Facilitate contact with her monk because culturally safe decision support can help finalise a values-congruent plan.", keywords: ["Buddhist", "monk", "spiritual", "end of life"] },
    ],
    priorityOrder: { urgent: ["s1", "s5", "s6"], secondary: ["s2", "s3", "s4", "s7"], lowYield: [] },
    modelAnswer: `Mrs Davies may have a valid capacitous refusal of high-risk palliative surgery. She says, "I have had enough; I want comfort care only," and can describe the surgery and the possibility of dying without it. A capacitous adult may refuse life-prolonging treatment, even if the family disagrees.

The opioid issue requires nuance. She is mildly drowsy on opioids, so I would optimise pain relief and timing of assessment, but mild drowsiness does not prove incapacity. Her statement, "More days in ICU is not living," shows values-based weighing of survival time against treatment burden.

The son's belief that she is depressed and must be made to have surgery should prompt screening for depression, delirium and demoralisation, but it should not be accepted as evidence of incapacity. The daughter's collateral that her mother has always valued independence and previously rejected burdensome treatment supports the possibility that this refusal is consistent with long-held values.

The family's request to declare her incapable because they cannot agree is the ethical hinge. Capacity assessment is not a tool to solve family conflict. If Mrs Davies has capacity, her decision stands; if she lacks capacity, substitute decision-making should be guided by her values and prior wishes.

Her request to speak with her monk is clinically relevant. I would facilitate that if time allows, clarify surgical urgency, and document capacity findings, opioid and delirium considerations, depression screen, values, family views, spiritual support and the final goals-of-care plan.`,
  },
];
