import type { QuizStem } from "../quizData";

export const PER_STEMS: QuizStem[] = [
  {
    id: "PER-001",
    questionNumber: "MEQ-091",
    topic: "perinatal",
    difficulty: "consultant",
    title: "Postpartum Psychosis — Discharge Summary Missing Child Safety",
    candidateRole: "Consultant perinatal psychiatrist, mother-baby unit",
    setting: "Mother-baby unit, metropolitan hospital — co-sign review",
    stem: `You are the consultant perinatal psychiatrist. A discharge summary for Aisha, a 29-year-old Somali-Australian woman, is awaiting your co-signature. Aisha was admitted six weeks ago following a postpartum psychotic episode — her first psychiatric presentation — three weeks after the birth of her daughter Lily. She responded well to olanzapine and is being discharged home with her baby.

The discharge summary reads: "Aisha's mental state has significantly improved. She is currently euthymic with good insight. She is bonding appropriately with Lily. Diagnosis: brief psychotic episode. Plan: continue olanzapine 10mg. Follow up with perinatal outpatient clinic in 4 weeks. GP to monitor."

The summary does not name Lily or include a child safety assessment. Breastfeeding and olanzapine compatibility is not addressed. There is no relapse prevention plan specific to the perinatal context and no contingency plan if Aisha deteriorates at home.

You note from the referral documentation that Aisha arrived in Australia from Somalia three years ago, has no extended family in Australia, and her husband works long hours and was not involved in the admission. The registrar who wrote the summary asks you to co-sign so Aisha can go home today.`,
    totalMarks: 22,
    signals: [
      { id: "s1", name: "Consultant should not co-sign an unsafe perinatal discharge", category: "governance", severity: "critical", clueInStem: "A discharge summary for Aisha, a 29-year-old Somali-Australian woman, is awaiting your co-signature.", whyItMatters: "Missing this signal means the candidate has accepted consultant responsibility for a discharge document that omits perinatal and infant-safety essentials.", modelWording: "Refuse to co-sign until the summary and discharge plan are corrected because consultant signature would endorse unsafe perinatal care.", keywords: ["co-sign", "consultant responsibility", "discharge summary", "perinatal", "unsafe"] },
      { id: "s2", name: "Postpartum psychosis must be named explicitly", category: "diagnosis_formulation", severity: "critical", clueInStem: "Aisha was admitted six weeks ago following a postpartum psychotic episode — her first psychiatric presentation — three weeks after the birth of her daughter Lily.", whyItMatters: "Missing this signal means the summary under-communicates the diagnosis and relapse implications of a recent postpartum psychotic episode.", modelWording: "Name postpartum psychosis clearly because it shapes relapse prevention, infant safety, future pregnancy counselling and follow-up intensity.", keywords: ["postpartum psychosis", "diagnosis", "relapse", "future pregnancy", "perinatal"] },
      { id: "s3", name: "Brief psychotic episode label minimises perinatal risk", category: "diagnosis_formulation", severity: "important", clueInStem: "Diagnosis: brief psychotic episode.", whyItMatters: "Missing this signal means the candidate has accepted a generic diagnostic label that may mislead the GP and community team about postpartum-specific risk.", modelWording: "Correct the diagnosis wording because a generic brief psychotic episode label does not communicate postpartum psychosis risk.", keywords: ["brief psychotic episode", "diagnosis", "postpartum", "risk communication"] },
      { id: "s4", name: "Lily is unnamed and child safety is undocumented", category: "child_protection", severity: "critical", clueInStem: "The summary does not name Lily or include a child safety assessment.", whyItMatters: "Missing this signal means the baby being discharged from a mother-baby unit has no documented safety assessment.", modelWording: "Name Lily and document child safety because discharge home with a baby requires explicit infant-safety reasoning.", keywords: ["Lily", "child safety", "infant", "safeguarding", "baby"] },
      { id: "s5", name: "Breastfeeding and olanzapine discussion is missing", category: "physical_health", severity: "important", clueInStem: "Breastfeeding and olanzapine compatibility is not addressed.", whyItMatters: "Missing this signal means Aisha and Lily leave without documented counselling about medication, feeding choice and infant monitoring.", modelWording: "Document the olanzapine and breastfeeding discussion because Aisha needs informed medication and feeding guidance.", keywords: ["olanzapine", "breastfeeding", "infant monitoring", "medication", "feeding"] },
      { id: "s6", name: "Perinatal relapse and home deterioration plans are absent", category: "risk_self", severity: "critical", clueInStem: "There is no relapse prevention plan specific to the perinatal context and no contingency plan if Aisha deteriorates at home.", whyItMatters: "Missing this signal means the family and services have no plan for early warning signs or deterioration while Aisha is caring for Lily.", modelWording: "Write a perinatal relapse and contingency plan because postpartum psychosis can recur rapidly and affects both mother and infant safety.", keywords: ["relapse prevention", "contingency", "deteriorates at home", "early warning", "perinatal"] },
      { id: "s7", name: "Four-week follow-up is too delayed", category: "disposition", severity: "important", clueInStem: "Follow up with perinatal outpatient clinic in 4 weeks.", whyItMatters: "Missing this signal means the candidate has accepted routine follow-up after a high-risk mother-baby discharge.", modelWording: "Arrange earlier perinatal follow-up because four weeks is too delayed after postpartum psychosis discharge.", keywords: ["four weeks", "follow-up", "perinatal outpatient", "early review"] },
      { id: "s8", name: "Migration isolation and absent partner involvement increase vulnerability", category: "cultural_safety", severity: "important", clueInStem: "Aisha arrived in Australia from Somalia three years ago, has no extended family in Australia, and her husband works long hours and was not involved in the admission.", whyItMatters: "Missing this signal means the discharge plan assumes support that the stem says may not exist.", modelWording: "Assess culturally safe practical supports because migration isolation and limited partner involvement increase discharge vulnerability.", keywords: ["Somalia", "no extended family", "husband", "social isolation", "cultural safety"] },
      { id: "s9", name: "Same-day discharge pressure should not override safety", category: "system_pressure", severity: "important", clueInStem: "The registrar who wrote the summary asks you to co-sign so Aisha can go home today.", whyItMatters: "Missing this signal means time pressure has replaced completion of perinatal discharge safeguards.", modelWording: "Pause same-day discharge if safeguards are incomplete because speed cannot override infant safety and relapse planning.", keywords: ["go home today", "pressure", "discharge", "safeguards", "registrar"] },
    ],
    priorityOrder: { urgent: ["s1", "s2", "s4", "s6"], secondary: ["s3", "s5", "s7", "s8", "s9"], lowYield: [] },
    modelAnswer: `I would not co-sign the summary or allow discharge to proceed on the current documentation. Aisha was admitted after a postpartum psychotic episode three weeks after Lily's birth, yet the summary calls it a brief psychotic episode and gives a routine plan. That wording fails to communicate the perinatal diagnosis, relapse risk, infant-safety implications and need for close follow-up.

Lily must be named and her safety explicitly documented. A vague statement that Aisha is bonding appropriately is not enough for a mother-baby discharge. The corrected summary should include parenting observations from admission, feeding and settling, responsiveness, supervision needs, protective factors and any safeguarding concerns or child protection involvement.

The medication and feeding plan is also incomplete. Aisha is to continue olanzapine 10 mg, but breastfeeding and olanzapine compatibility are not addressed. I would document the risk-benefit discussion, Aisha's feeding decision and any monitoring needed for Lily.

The discharge plan must include perinatal relapse prevention and a home contingency plan. It should list early warning signs, sleep-protection arrangements, medication adherence, what her husband should do if symptoms return, emergency contacts, after-hours escalation and what happens if she deteriorates while alone with Lily. Four-week follow-up is too delayed; early perinatal community contact and senior review should be arranged.

The social and cultural context makes discharge more vulnerable. Aisha arrived from Somalia three years ago, has no extended family in Australia, and her husband works long hours and was not involved in the admission. I would involve him before discharge, assess culturally appropriate supports, link maternal-child health and community perinatal services, and supervise the registrar to rewrite the summary before any co-signature occurs.`,
  },
  {
    id: "PER-002",
    questionNumber: "MEQ-092",
    topic: "perinatal",
    difficulty: "consultant",
    title: "Antenatal Depression — Medication, Foetal Risk and Domestic Violence",
    candidateRole: "Consultant psychiatrist, perinatal mental health service",
    setting: "Perinatal outpatient clinic, metropolitan hospital",
    stem: `You are the consultant psychiatrist in a perinatal mental health service. You are reviewing Mei, a 32-year-old Chinese-Australian woman referred by her obstetrician at 18 weeks gestation. She has a history of recurrent major depressive disorder and was stable on sertraline 100mg before conception. She stopped sertraline at six weeks gestation "because I read online it harms the baby."

Mei reports worsening low mood, inability to sleep, poor appetite and passive suicidal ideation: "Sometimes I think everyone would be better off without me." Her husband has accompanied her today but sits with his arms crossed and answers questions directed at Mei before she can respond. When Mei is seen alone, she becomes tearful and quietly discloses that her husband has been "pushing and grabbing" her during arguments since the pregnancy began. She asks you not to document this.

The obstetrician's referral letter notes the foetus has mild growth restriction on the last scan. Mei's mother, who is visiting from China, is the only local support and speaks no English.`,
    totalMarks: 25,
    signals: [
      { id: "s1", name: "Sertraline cessation was based on pregnancy medication misinformation", category: "consent_refusal", severity: "critical", clueInStem: "She stopped sertraline at six weeks gestation \"because I read online it harms the baby.\"", whyItMatters: "Missing this signal means the candidate has not corrected the misinformation driving untreated recurrent depression in pregnancy.", modelWording: "Provide balanced medication counselling because Mei stopped effective sertraline based on online fear rather than informed risk-benefit advice.", keywords: ["sertraline", "pregnancy", "misinformation", "risk-benefit", "antidepressant"] },
      { id: "s2", name: "Worsening depression and passive suicidal ideation require risk assessment", category: "risk_self", severity: "critical", clueInStem: "Mei reports worsening low mood, inability to sleep, poor appetite and passive suicidal ideation: \"Sometimes I think everyone would be better off without me.\"", whyItMatters: "Missing this signal means the candidate has normalised antenatal depression despite suicidal thinking and functional deterioration.", modelWording: "Assess suicide risk directly because passive suicidal ideation in untreated antenatal depression can escalate and affects maternal-foetal safety.", keywords: ["passive suicidal ideation", "antenatal depression", "sleep", "appetite", "risk assessment"] },
      { id: "s3", name: "Husband's controlling behaviour requires seeing Mei alone", category: "trauma", severity: "critical", clueInStem: "Her husband has accompanied her today but sits with his arms crossed and answers questions directed at Mei before she can respond.", whyItMatters: "Missing this signal means the candidate has missed a coercive-control cue that could prevent disclosure of violence and risk.", modelWording: "Ensure private time with Mei because her husband's controlling behaviour makes his collateral unreliable and may suppress disclosure.", keywords: ["coercive control", "husband", "answers questions", "seen alone", "family violence"] },
      { id: "s4", name: "Physical violence in pregnancy needs safety planning", category: "immediate_safety", severity: "critical", clueInStem: "When Mei is seen alone, she becomes tearful and quietly discloses that her husband has been \"pushing and grabbing\" her during arguments since the pregnancy began.", whyItMatters: "Missing this signal means the candidate has not acted on family violence occurring during pregnancy.", modelWording: "Assess family violence severity and safety because pushing and grabbing during pregnancy threatens Mei and the foetus.", keywords: ["pushing and grabbing", "family violence", "pregnancy", "safety plan", "foetus"] },
      { id: "s5", name: "Request not to document creates a safety-confidentiality tension", category: "ethics", severity: "important", clueInStem: "She asks you not to document this.", whyItMatters: "Missing this signal means the candidate has either breached trust insensitively or agreed to omit clinically relevant safety information.", modelWording: "Explain documentation limits sensitively because clinically relevant violence information cannot simply be omitted from the record.", keywords: ["not document", "confidentiality", "documentation", "safety", "ethics"] },
      { id: "s6", name: "Foetal growth restriction increases urgency of coordinated care", category: "risk_vulnerable", severity: "important", clueInStem: "The obstetrician's referral letter notes the foetus has mild growth restriction on the last scan.", whyItMatters: "Missing this signal means the candidate has not linked maternal depression, poor appetite and violence stress with foetal wellbeing concerns.", modelWording: "Coordinate with obstetrics because foetal growth restriction increases the urgency of treating depression and addressing violence.", keywords: ["foetal growth restriction", "obstetrician", "foetal wellbeing", "coordination", "pregnancy"] },
      { id: "s7", name: "Mother may be support but needs interpreter and assessment", category: "family_carer", severity: "important", clueInStem: "Mei's mother, who is visiting from China, is the only local support and speaks no English.", whyItMatters: "Missing this signal means the candidate has assumed support without assessing language barriers, safety and family attitudes.", modelWording: "Assess Mei's mother as a possible support with a professional interpreter because her role may be protective or complicated by stigma and language barriers.", keywords: ["mother", "China", "no English", "support", "interpreter", "family"] },
      { id: "s8", name: "Chinese-Australian identity requires individual cultural formulation", category: "cultural_safety", severity: "important", clueInStem: "You are reviewing Mei, a 32-year-old Chinese-Australian woman referred by her obstetrician at 18 weeks gestation.", whyItMatters: "Missing this signal means the candidate may ignore or stereotype cultural beliefs about depression, medication, pregnancy and domestic violence.", modelWording: "Explore Mei's cultural beliefs individually because cultural safety requires curiosity without assumptions about her Chinese-Australian background.", keywords: ["Chinese-Australian", "cultural safety", "pregnancy", "medication beliefs", "stigma"] },
    ],
    priorityOrder: { urgent: ["s2", "s3", "s4"], secondary: ["s1", "s5", "s6", "s7", "s8"], lowYield: [] },
    modelAnswer: `Mei's immediate risks are antenatal depression, suicidal ideation and family violence. She reports worsening low mood, poor sleep, poor appetite and the thought that everyone would be better off without her. I would assess suicidal intent, plans, means, protective factors, attachment to the pregnancy, capacity to safety plan and whether she needs urgent crisis or inpatient care.

The consultation behaviour strongly suggests coercive control. Her husband answers questions directed at Mei, and she discloses only when seen alone that he has been pushing and grabbing her during arguments since the pregnancy began. I would continue to see her alone, assess violence frequency, escalation, injuries, strangulation, threats, access to weapons, immediate safety and safe ways to contact her. I would involve family violence services and consider reporting duties according to jurisdiction and risk.

Mei's request not to document the violence needs careful handling. I would explain that I cannot omit clinically relevant safety information, but I would discuss how it is documented, who can access it, and how to reduce risk from disclosure. Preserving trust matters, but safety information cannot be erased.

Her medication decision also needs correction. She stopped sertraline because she read online that it harms the baby, yet she has recurrent major depression and is now unwell. I would provide balanced advice about sertraline and the risks of untreated depression, including sleep disruption, poor nutrition, suicide risk and possible effects on foetal wellbeing. Restarting sertraline should be discussed with obstetric coordination.

The foetus has mild growth restriction, so obstetric liaison is important. Mei's mother is the only local support and speaks no English, so I would assess her role with a professional interpreter rather than assuming she can provide safety. I would also explore Mei's Chinese-Australian cultural beliefs about depression, medication, pregnancy and violence without stereotyping, and build a plan with obstetrics, GP, perinatal mental health, social work and family violence supports.`,
  },
  {
    id: "PER-003",
    questionNumber: "MEQ-093",
    topic: "perinatal",
    difficulty: "consultant",
    title: "Perinatal OCD — Intrusive Thoughts About Harming Infant",
    candidateRole: "Consultant psychiatrist, perinatal mental health outpatient service",
    setting: "Perinatal outpatient clinic",
    stem: `You are the consultant psychiatrist in a perinatal mental health service. You are reviewing Grace, a 27-year-old first-time mother referred by her GP at six weeks postpartum. Her baby son Oliver is with her in the clinic.

Grace is tearful and has been reluctant to speak. She eventually discloses that she has been having intrusive thoughts about harming Oliver — specifically about dropping him or stabbing him with kitchen knives. She says, "I would never do it. These thoughts terrify me. I spend hours checking on him to make sure he is okay. I have hidden all the sharp objects in the house." She has not told her husband because "he will think I am a monster and take Oliver away."

Her GP's referral letter notes she had significant health anxiety before the pregnancy and took fluoxetine for two years in her mid-twenties. The GP writes: "please assess — very worried she may be at risk of harming the baby."

Grace has not slept more than two to three hours per night since the birth. She appears anxious and exhausted but her mental state is otherwise unremarkable. She is breastfeeding and is highly distressed by the prospect of medication.`,
    totalMarks: 22,
    signals: [
      { id: "s1", name: "Intrusive harm thoughts need OCD formulation", category: "diagnosis_formulation", severity: "critical", clueInStem: "She eventually discloses that she has been having intrusive thoughts about harming Oliver — specifically about dropping him or stabbing him with kitchen knives.", whyItMatters: "Missing this signal means the candidate has not recognised the content requiring differentiation between perinatal OCD, psychosis and genuine intent.", modelWording: "Formulate the intrusive harm thoughts carefully because perinatal OCD commonly presents with unwanted infant-harm obsessions.", keywords: ["intrusive thoughts", "perinatal OCD", "Oliver", "harm thoughts", "differential"] },
      { id: "s2", name: "Ego-dystonic distress and checking favour OCD", category: "diagnosis_formulation", severity: "critical", clueInStem: "She says, \"I would never do it. These thoughts terrify me. I spend hours checking on him to make sure he is okay. I have hidden all the sharp objects in the house.\"", whyItMatters: "Missing this signal means the candidate has misclassified protective checking and avoidance as evidence of dangerousness rather than OCD.", modelWording: "Identify ego-dystonic distress, checking and avoidance because these features support perinatal OCD rather than infanticidal intent.", keywords: ["ego-dystonic", "checking", "avoidance", "sharp objects", "OCD", "not intent"] },
      { id: "s3", name: "Shame is preventing partner support", category: "family_carer", severity: "important", clueInStem: "She has not told her husband because \"he will think I am a monster and take Oliver away.\"", whyItMatters: "Missing this signal means Grace remains isolated by shame and fear despite a potentially protective partner role.", modelWording: "Offer partner psychoeducation with Grace's consent because accurate understanding may reduce shame and improve support.", keywords: ["husband", "monster", "shame", "support", "psychoeducation"] },
      { id: "s4", name: "Past health anxiety and fluoxetine response inform treatment", category: "collateral", severity: "important", clueInStem: "Her GP's referral letter notes she had significant health anxiety before the pregnancy and took fluoxetine for two years in her mid-twenties.", whyItMatters: "Missing this signal means the candidate has ignored prior anxiety vulnerability and a potentially useful medication history.", modelWording: "Use the GP history to guide treatment because prior health anxiety and fluoxetine exposure support an OCD-spectrum formulation.", keywords: ["health anxiety", "fluoxetine", "GP", "history", "treatment"] },
      { id: "s5", name: "GP concern needs education without unnecessary child protection escalation", category: "child_protection", severity: "important", clueInStem: "The GP writes: \"please assess — very worried she may be at risk of harming the baby.\"", whyItMatters: "Missing this signal means the candidate has either ignored infant safety or traumatised Grace by treating ego-dystonic OCD as a child protection emergency.", modelWording: "Educate the GP about perinatal OCD because unwanted intrusive thoughts with protective behaviour usually do not equal intent to harm.", keywords: ["GP", "risk of harming", "child protection", "education", "OCD"] },
      { id: "s6", name: "Severe sleep deprivation is maintaining symptoms", category: "physical_health", severity: "important", clueInStem: "Grace has not slept more than two to three hours per night since the birth.", whyItMatters: "Missing this signal means the candidate has not addressed a modifiable postpartum driver of anxiety, obsessionality and exhaustion.", modelWording: "Prioritise sleep restoration because two to three hours per night can worsen intrusive thoughts and functioning.", keywords: ["sleep deprivation", "postpartum", "two to three hours", "anxiety", "OCD"] },
      { id: "s7", name: "Otherwise unremarkable mental state reduces psychosis concern", category: "diagnosis_formulation", severity: "important", clueInStem: "She appears anxious and exhausted but her mental state is otherwise unremarkable.", whyItMatters: "Missing this signal means the candidate has not used the absence of psychotic features to refine risk and avoid over-pathologising.", modelWording: "Exclude psychosis explicitly because an otherwise unremarkable mental state supports OCD when harm thoughts are unwanted and distressing.", keywords: ["mental state", "unremarkable", "psychosis", "risk formulation", "OCD"] },
      { id: "s8", name: "Breastfeeding medication fear requires informed choice", category: "consent_refusal", severity: "important", clueInStem: "She is breastfeeding and is highly distressed by the prospect of medication.", whyItMatters: "Missing this signal means the candidate has pushed or avoided medication without addressing Grace's breastfeeding-specific fears.", modelWording: "Discuss medication and psychological options collaboratively because breastfeeding concerns require accurate information and respect for Grace's preferences.", keywords: ["breastfeeding", "medication", "SSRI", "informed choice", "CBT"] },
    ],
    priorityOrder: { urgent: ["s1", "s2"], secondary: ["s3", "s4", "s5", "s6", "s7", "s8"], lowYield: [] },
    modelAnswer: `Grace's presentation is most consistent with perinatal OCD, not postpartum psychosis or high-risk infanticidal intent. She has intrusive thoughts about dropping or stabbing Oliver, but she says, "I would never do it," the thoughts terrify her, she checks on him for hours and she has hidden sharp objects. The distress, ego-dystonic quality, checking and avoidance are diagnostic clues.

I would still assess risk carefully. I would ask about intent, urges, command hallucinations, delusional beliefs, depression, suicidality, dissociation, substance use, actual caregiving, and whether Oliver is safe today. Her mental state is otherwise unremarkable apart from anxiety and exhaustion, which further supports OCD rather than psychosis.

The GP's concern is understandable but needs correction. Ego-dystonic intrusive thoughts in a mother who is actively protecting her baby usually do not meet a child protection threshold by themselves. Unnecessary child protection escalation could reinforce Grace's fear that she is a monster and damage engagement, although infant safety still needs to be checked and documented.

Treatment should include psychoeducation and CBT with exposure and response prevention where available. Severe sleep deprivation is maintaining symptoms, so I would develop a sleep plan with partner involvement if Grace agrees. Her past health anxiety and previous fluoxetine treatment are relevant to formulation and medication discussion.

Grace is breastfeeding and distressed by the prospect of medication, so I would provide accurate information about SSRI options and breastfeeding without pressuring her. With her consent, I would involve her husband in psychoeducation, because his understanding may reduce shame and increase practical support. Follow-up should be close until symptoms, sleep and confidence in caring for Oliver improve.`,
  },
  {
    id: "PER-004",
    questionNumber: "MEQ-094",
    topic: "perinatal",
    difficulty: "consultant",
    title: "Bipolar Disorder in Pregnancy — Medication Dilemma and Consent",
    candidateRole: "Consultant psychiatrist, perinatal mental health service",
    setting: "Perinatal outpatient clinic, 14 weeks gestation",
    stem: `You are the consultant psychiatrist in a perinatal mental health service. You are reviewing Natasha, a 34-year-old woman at 14 weeks gestation with a 10-year history of bipolar I disorder. She has had three severe manic episodes, one of which required a forensic psychiatric admission after she assaulted a family member. She has been stable on lithium 800mg daily for four years.

Natasha tells you she stopped lithium four weeks ago "because I read that it causes heart defects." She has not told her obstetrician. She says, "I feel completely fine. I don't think I need medication in pregnancy." Her partner is visibly worried and says, "Last time she stopped lithium without telling anyone, she was manic within six weeks. I can't go through that again."

An urgent FBC and lithium level are pending. The obstetrician calls while you are in the consultation and says, "If she is on lithium we need to know — there are cardiac screening implications."`,
    totalMarks: 25,
    signals: [
      { id: "s1", name: "Severe bipolar history makes relapse high consequence", category: "diagnosis_formulation", severity: "critical", clueInStem: "She has had three severe manic episodes, one of which required a forensic psychiatric admission after she assaulted a family member.", whyItMatters: "Missing this signal means the candidate has treated medication refusal as low risk despite a history of severe mania and violence.", modelWording: "Formulate relapse as high consequence because Natasha's prior mania included forensic admission after assault.", keywords: ["bipolar I", "mania", "forensic admission", "assault", "relapse risk"] },
      { id: "s2", name: "Stopping lithium after four years of stability is time-sensitive", category: "immediate_safety", severity: "critical", clueInStem: "She has been stable on lithium 800mg daily for four years.", whyItMatters: "Missing this signal means the candidate has not recognised that ceasing a long-effective mood stabiliser may destabilise pregnancy rapidly.", modelWording: "Treat lithium cessation as urgent because four years of stability on lithium suggests it was a key relapse-prevention treatment.", keywords: ["lithium", "stable", "four years", "cessation", "relapse"] },
      { id: "s3", name: "Lithium teratogenicity fear needs balanced consent", category: "consent_refusal", severity: "critical", clueInStem: "Natasha tells you she stopped lithium four weeks ago \"because I read that it causes heart defects.\"", whyItMatters: "Missing this signal means the candidate has allowed online fear to drive a high-risk medication decision without balanced counselling.", modelWording: "Correct misinformation with balanced counselling because lithium risks must be weighed against relapse and pregnancy safety risks.", keywords: ["heart defects", "lithium", "pregnancy", "consent", "risk-benefit"] },
      { id: "s4", name: "Obstetrician has not been informed of lithium exposure and cessation", category: "mdt_conflict", severity: "critical", clueInStem: "She has not told her obstetrician.", whyItMatters: "Missing this signal means the candidate has not repaired a communication gap that affects foetal screening and maternal relapse planning.", modelWording: "Facilitate communication with obstetrics because the team needs accurate lithium exposure and cessation history for safe antenatal care.", keywords: ["obstetrician", "communication", "lithium exposure", "cardiac screening", "antenatal"] },
      { id: "s5", name: "Feeling fine may reflect limited early insight", category: "capacity", severity: "important", clueInStem: "She says, \"I feel completely fine. I don't think I need medication in pregnancy.\"", whyItMatters: "Missing this signal means the candidate has accepted current wellbeing as evidence that relapse prevention is unnecessary.", modelWording: "Assess understanding and weighing because feeling well now does not remove high relapse risk after lithium cessation.", keywords: ["feel fine", "insight", "capacity", "medication refusal", "relapse prevention"] },
      { id: "s6", name: "Partner collateral gives a prior relapse timeline", category: "collateral", severity: "critical", clueInStem: "Her partner is visibly worried and says, \"Last time she stopped lithium without telling anyone, she was manic within six weeks. I can't go through that again.\"", whyItMatters: "Missing this signal means the candidate has ignored the clearest case-specific predictor of imminent relapse and carer strain.", modelWording: "Use the partner's collateral because previous mania within six weeks of stopping lithium makes the current four-week cessation urgent.", keywords: ["partner", "six weeks", "collateral", "relapse timeline", "carer distress"] },
      { id: "s7", name: "Pending bloods should inform safe lithium planning", category: "physical_health", severity: "important", clueInStem: "An urgent FBC and lithium level are pending.", whyItMatters: "Missing this signal means the candidate has not integrated physical monitoring into medication decision-making.", modelWording: "Review pending investigations because restarting or adjusting lithium requires safe baseline and monitoring information.", keywords: ["FBC", "lithium level", "monitoring", "bloods", "physical health"] },
      { id: "s8", name: "Foetal cardiac screening implications require coordinated plan", category: "risk_vulnerable", severity: "important", clueInStem: "The obstetrician calls while you are in the consultation and says, \"If she is on lithium we need to know — there are cardiac screening implications.\"", whyItMatters: "Missing this signal means the candidate has not linked medication history to foetal cardiac screening and obstetric coordination.", modelWording: "Coordinate foetal cardiac screening with obstetrics because lithium exposure history affects antenatal monitoring.", keywords: ["cardiac screening", "foetal", "obstetrician", "lithium", "coordination"] },
      { id: "s9", name: "Advance relapse plan is needed before crisis", category: "mental_health_act", severity: "important", clueInStem: "Last time she stopped lithium without telling anyone, she was manic within six weeks. I can't go through that again.", whyItMatters: "Missing this signal means the candidate waits for relapse rather than planning early warning signs and preferred responses while Natasha is well.", modelWording: "Develop an advance relapse plan now because planning is safer before mania impairs insight and consent.", keywords: ["advance plan", "early warning signs", "mania", "pregnancy", "Mental Health Act"] },
    ],
    priorityOrder: { urgent: ["s1", "s2", "s3", "s4", "s6"], secondary: ["s5", "s7", "s8", "s9"], lowYield: [] },
    modelAnswer: `Natasha's lithium cessation is a time-sensitive perinatal relapse risk. She has bipolar I disorder with three severe manic episodes, including a forensic admission after assaulting a family member, and she had been stable on lithium 800 mg for four years. Stopping the medication four weeks ago removes a treatment that appears central to her stability.

Her decision was made on incomplete risk information. She stopped lithium because she read that it causes heart defects, so I would provide balanced counselling about lithium exposure, foetal cardiac screening, the risk of relapse if untreated, and the risks of acute mania in pregnancy. The aim is not to frighten her into treatment, but to support genuinely informed consent.

The partner's collateral is highly important. He says that last time she stopped lithium without telling anyone, she was manic within six weeks, and he cannot go through that again. That gives a case-specific relapse timeline and shows carer distress. Natasha's statement that she feels completely fine should not be treated as reassurance that medication is unnecessary.

The obstetrician needs accurate information. Natasha has not told obstetrics, and the obstetrician is explicitly asking because there are cardiac screening implications. I would seek Natasha's consent to communicate the medication history, cessation, relapse risk and current plan to obstetrics today, and I would coordinate foetal cardiac screening and medication monitoring.

Pending FBC and lithium level should be reviewed as part of safe prescribing. If Natasha agrees, restarting lithium with careful monitoring may be the most protective option; if she refuses, I would discuss alternatives and their limitations. I would also develop an advance relapse plan while she is well, including early warning signs, partner involvement, rapid review, preferred treatments and what would happen if mania impaired her capacity or safety during pregnancy.`,
  },
];
