import type { QuizStem } from "../quizData";

export const PSY_STEMS: QuizStem[] = [
  {
    id: "PSY-001",
    questionNumber: "MEQ-076",
    topic: "psychotherapy",
    difficulty: "consultant",
    title: "Splitting and Chronic Suicidality on an Inpatient Unit",
    candidateRole: "Consultant psychiatrist, acute inpatient unit",
    setting: "Metropolitan acute psychiatric inpatient ward",
    stem: `You are the consultant psychiatrist on an acute inpatient unit.

Alicia is a 29-year-old woman with a diagnosis of borderline personality disorder, recurrent non-suicidal self-injury, trauma history, and multiple previous admissions. She was admitted voluntarily five days ago after telling the crisis team she would overdose if left alone. Since admission, she has formed a close relationship with one junior nurse and refuses to speak to other staff, saying, "She is the only one who actually cares whether I live or die."

Over the weekend, Alicia cut her forearm superficially after being told that leave would not be approved. She then told the night registrar, "If you discharge me, my blood is on your hands." The registrar extended admission and placed her on constant observations. The nursing team is now divided: some staff feel she is "too risky to discharge," while others say the admission is "just reinforcing her behaviour."

The bed manager is requesting discharge because three people are waiting in ED. Alicia's mother rings the ward repeatedly, saying, "Every time you send her home she gets worse." The treating psychologist says prolonged admission may undermine the community DBT plan. The junior registrar asks you whether the safest option is to keep Alicia admitted until she denies suicidal thoughts.`,
    totalMarks: 22,
    signals: [
      { id: "s1", name: "Acute self-harm must be separated from baseline chronic risk", category: "risk_self", severity: "critical", clueInStem: "Over the weekend, Alicia cut her forearm superficially after being told that leave would not be approved.", whyItMatters: "Missing this signal means the candidate has not distinguished chronic non-suicidal self-injury from acute escalation triggered by ward limits.", modelWording: "Differentiate acute-on-chronic risk by assessing intent, escalation, function of cutting, access to means and response to limit-setting.", keywords: ["chronic suicidality", "dynamic risk", "acute escalation", "NSSI", "leave refusal", "risk formulation"] },
      { id: "s2", name: "Discharge threat should not determine admission length alone", category: "risk_self", severity: "critical", clueInStem: "She then told the night registrar, \"If you discharge me, my blood is on your hands.\"", whyItMatters: "Missing this signal means the candidate has allowed a high-emotion threat to drive open-ended admission without a structured risk formulation.", modelWording: "Assess the discharge threat seriously while avoiding reactive admission decisions based only on the wording of the threat.", keywords: ["discharge threat", "blood on your hands", "reactive admission", "dynamic risk", "suicide risk"] },
      { id: "s3", name: "Idealisation of one nurse is dividing care", category: "mdt_conflict", severity: "critical", clueInStem: "Since admission, she has formed a close relationship with one junior nurse and refuses to speak to other staff, saying, \"She is the only one who actually cares whether I live or die.\"", whyItMatters: "Missing this signal means the candidate has not recognised splitting and special-role dependency that can fragment inpatient care.", modelWording: "Recognise splitting and idealisation by moving care from one junior nurse to a consistent team-based plan.", keywords: ["splitting", "idealisation", "team division", "junior nurse", "consistent boundaries", "BPD"] },
      { id: "s4", name: "Constant observations may become reactive containment", category: "disposition", severity: "important", clueInStem: "The registrar extended admission and placed her on constant observations.", whyItMatters: "Missing this signal means the candidate has accepted observation escalation without clarifying its purpose, review point or possible iatrogenic effect.", modelWording: "Review the rationale for constant observations because observation should be time-limited, purposeful and linked to dynamic risk.", keywords: ["constant observations", "observation rationale", "reactive containment", "review", "risk management"] },
      { id: "s5", name: "Team polarisation needs consultant containment", category: "mdt_conflict", severity: "important", clueInStem: "The nursing team is now divided: some staff feel she is \"too risky to discharge,\" while others say the admission is \"just reinforcing her behaviour.\"", whyItMatters: "Missing this signal means the candidate has allowed staff fear and therapeutic nihilism to replace a shared formulation.", modelWording: "Contain team polarisation by validating staff anxiety, challenging dismissive language and creating one agreed care plan.", keywords: ["team polarisation", "therapeutic nihilism", "staff fear", "reinforcing behaviour", "consultant leadership"] },
      { id: "s6", name: "Bed pressure must not be the discharge rationale", category: "system_pressure", severity: "important", clueInStem: "The bed manager is requesting discharge because three people are waiting in ED.", whyItMatters: "Missing this signal means the candidate has allowed access pressure to contaminate a complex risk and psychotherapy-informed discharge decision.", modelWording: "Acknowledge bed pressure while ensuring any discharge is based on clinical formulation, safety planning and continuity of care.", keywords: ["bed pressure", "ED waiting", "system pressure", "defensible discharge", "access block"] },
      { id: "s7", name: "Mother's repeated calls reflect carer anxiety and risk history", category: "family_carer", severity: "important", clueInStem: "Alicia's mother rings the ward repeatedly, saying, \"Every time you send her home she gets worse.\"", whyItMatters: "Missing this signal means the candidate has either dismissed family anxiety or allowed it to drive indefinite admission without a shared plan.", modelWording: "Engage Alicia's mother with consent because carer anxiety and past deterioration need to be incorporated into a realistic safety plan.", keywords: ["mother", "carer anxiety", "family", "safety plan", "psychoeducation", "discharge history"] },
      { id: "s8", name: "Denial of suicidal thoughts is not the sole discharge criterion", category: "ethics", severity: "important", clueInStem: "The junior registrar asks you whether the safest option is to keep Alicia admitted until she denies suicidal thoughts.", whyItMatters: "Missing this signal means the candidate has treated denial of suicidal thoughts as the endpoint rather than assessing function, supports and dynamic risk.", modelWording: "Correct the registrar's discharge threshold because safety depends on formulation, collaboration and supports, not simply denial of suicidal thoughts.", keywords: ["denial", "suicidal thoughts", "discharge criteria", "risk formulation", "registrar supervision"] },
    ],
    priorityOrder: { urgent: ["s1", "s2", "s3"], secondary: ["s4", "s5", "s6", "s7", "s8"], lowYield: [] },
    modelAnswer: `Alicia's presentation needs an acute-on-chronic formulation rather than a simple decision to admit or discharge. She has chronic non-suicidal self-injury and multiple previous admissions, but she also cut her forearm after a leave refusal and then told the registrar, "If you discharge me, my blood is on your hands." I would take the threat seriously while assessing intent, planning, access to means, intoxication, mental state change, supports and whether this is an escalation from her baseline pattern.

The interpersonal dynamics on the ward are central. Alicia has idealised one junior nurse as the only person who cares whether she lives or dies and refuses to speak to other staff. That creates splitting, staff anxiety and inconsistent care. I would move the plan from one special relationship to a team-based approach with consistent language, agreed limits and predictable contact.

The current admission may be helpful only if it has clear goals. Constant observations and extended admission should be reviewed for their purpose, duration and effect. The nursing team is polarised between seeing Alicia as too risky to discharge and seeing admission as simply reinforcing behaviour. Both positions contain partial truths, so the consultant task is to contain the team, challenge dismissive language and create a shared formulation.

The community DBT plan matters because prolonged admission may undermine the treatment intended to help Alicia manage crises outside hospital. I would liaise with the psychologist, crisis team and community supports to plan a brief, goal-directed step-down with a written safety plan, means restriction, distress-tolerance strategies, follow-up and clear return criteria.

Bed pressure and family pressure must both be acknowledged without allowing either to determine the clinical decision. Alicia's mother repeatedly says she gets worse after discharge, so I would involve her with Alicia's consent, validate her fear and explain that indefinite admission does not remove chronic risk. I would also correct the junior registrar's idea that Alicia must remain admitted until she denies suicidal thoughts; discharge should be based on dynamic risk, collaboration, supports and continuity, not on a single denial-based threshold.`,
  },
  {
    id: "PSY-002",
    questionNumber: "MEQ-077",
    topic: "psychotherapy",
    difficulty: "consultant",
    title: "Dependency and Failed Engagement in Community BPD Care",
    candidateRole: "Consultant psychiatrist, community mental health team",
    setting: "Urban community mental health service",
    stem: `You are the consultant psychiatrist supervising a community mental health team.

Nathan is a 35-year-old man with borderline personality disorder, alcohol misuse, childhood trauma and repeated crisis presentations. He has missed four psychology appointments but sends multiple late-night emails to his care coordinator saying, "You are the only person stopping me from ending it." When the care coordinator does not respond immediately, Nathan presents to ED stating he has been abandoned by the team.

The care coordinator feels overwhelmed and says she is receiving emails on her personal phone. A junior registrar suggests discharging Nathan from the service because "he is not engaging." The psychologist is reluctant to offer therapy until Nathan is more stable and abstinent from alcohol. Nathan's GP says he is prescribing diazepam "because the mental health team won't help him."

At review, Nathan says, "If you put limits on contact, that proves you don't care." He denies current suicidal intent but says he may drink and cut himself if left alone. The team asks you to decide whether to close his file, increase contact, or refer him back to ED-based crisis care.`,
    totalMarks: 22,
    signals: [
      { id: "s1", name: "Missed appointments and crisis contact require formulation", category: "diagnosis_formulation", severity: "critical", clueInStem: "He has missed four psychology appointments but sends multiple late-night emails to his care coordinator saying, \"You are the only person stopping me from ending it.\"", whyItMatters: "Missing this signal means the candidate has labelled non-attendance as non-engagement rather than formulating attachment fear and crisis-driven contact.", modelWording: "Formulate missed appointments and late-night emails as attachment insecurity and affect dysregulation rather than simple non-compliance.", keywords: ["engagement", "attachment insecurity", "non-attendance", "late-night emails", "formulation", "BPD"] },
      { id: "s2", name: "Single-clinician rescue dynamic creates unsafe dependency", category: "ethics", severity: "critical", clueInStem: "He has missed four psychology appointments but sends multiple late-night emails to his care coordinator saying, \"You are the only person stopping me from ending it.\"", whyItMatters: "Missing this signal means the candidate has allowed one clinician to become the perceived suicide-prevention object for Nathan.", modelWording: "Shift care to a team-based frame because dependency on one care coordinator creates burnout and unsafe crisis expectations.", keywords: ["dependency", "rescue dynamic", "care coordinator", "team-based care", "boundary setting"] },
      { id: "s3", name: "Personal phone contact is a governance boundary breach", category: "governance", severity: "important", clueInStem: "The care coordinator feels overwhelmed and says she is receiving emails on her personal phone.", whyItMatters: "Missing this signal means the candidate has not addressed communication outside service systems that increases staff and medico-legal risk.", modelWording: "Stop personal phone contact and replace it with documented service-based communication boundaries.", keywords: ["personal phone", "communication boundaries", "staff safety", "governance", "medico-legal"] },
      { id: "s4", name: "ED presentations after delayed replies show abandonment sensitivity", category: "risk_self", severity: "important", clueInStem: "When the care coordinator does not respond immediately, Nathan presents to ED stating he has been abandoned by the team.", whyItMatters: "Missing this signal means the candidate has not linked crisis escalation to perceived abandonment and inconsistent response patterns.", modelWording: "Address abandonment-triggered ED use by creating predictable response times and a written crisis plan.", keywords: ["abandonment", "ED presentation", "crisis use", "response times", "safety plan"] },
      { id: "s5", name: "Discharge for non-engagement would repeat abandonment", category: "disposition", severity: "important", clueInStem: "A junior registrar suggests discharging Nathan from the service because \"he is not engaging.\"", whyItMatters: "Missing this signal means the candidate has accepted abrupt closure that is likely to intensify abandonment fears and crisis use.", modelWording: "Avoid abrupt discharge for non-engagement because closure should follow formulation, engagement repair and transition planning.", keywords: ["discharge", "not engaging", "abandonment", "transition", "service closure"] },
      { id: "s6", name: "Therapy should be staged rather than indefinitely deferred", category: "system_pressure", severity: "important", clueInStem: "The psychologist is reluctant to offer therapy until Nathan is more stable and abstinent from alcohol.", whyItMatters: "Missing this signal means the candidate has accepted a stability threshold that may indefinitely exclude Nathan from evidence-based therapy.", modelWording: "Offer staged therapy engagement because waiting for full stability and abstinence may prevent access to needed treatment.", keywords: ["therapy access", "staged therapy", "DBT", "stability", "alcohol", "engagement"] },
      { id: "s7", name: "Diazepam with alcohol misuse increases risk", category: "substance_use", severity: "important", clueInStem: "Nathan's GP says he is prescribing diazepam \"because the mental health team won't help him.\"", whyItMatters: "Missing this signal means the candidate has not addressed benzodiazepine prescribing that may increase overdose, dependence and disinhibition.", modelWording: "Liaise with the GP to rationalise diazepam because alcohol misuse and crisis self-harm make benzodiazepines high-risk.", keywords: ["diazepam", "alcohol misuse", "benzodiazepine", "overdose", "disinhibition", "GP liaison"] },
      { id: "s8", name: "Limits must be validated and maintained", category: "risk_self", severity: "important", clueInStem: "At review, Nathan says, \"If you put limits on contact, that proves you don't care.\"", whyItMatters: "Missing this signal means the candidate has either surrendered boundaries to fear or imposed limits without addressing the attachment meaning.", modelWording: "Validate Nathan's fear while maintaining limits because predictable boundaries are part of safe care, not rejection.", keywords: ["limits", "validation", "boundaries", "safe care", "not rejection", "attachment"] },
    ],
    priorityOrder: { urgent: ["s1", "s2"], secondary: ["s3", "s4", "s5", "s6", "s7", "s8"], lowYield: [] },
    modelAnswer: `Nathan should not be framed as simply not engaging. He misses psychology appointments but sends multiple late-night emails saying, "You are the only person stopping me from ending it," and presents to ED when the care coordinator does not respond immediately. That pattern needs formulation as attachment insecurity, affect dysregulation and fear of abandonment, not as grounds for abrupt service discharge.

The care arrangement is unsafe because one clinician has become the rescue figure. The care coordinator is overwhelmed and receiving emails on her personal phone, which bypasses service governance and creates unrealistic expectations, staff burnout and medico-legal risk. I would move communication to service channels, document response times and ensure risk is held by the team rather than one clinician.

Boundaries must be therapeutic rather than punitive. Nathan says, "If you put limits on contact, that proves you don't care." I would validate the fear behind that statement while explaining that predictable limits are part of safe care. The plan should specify how to seek help, what responses can be expected, and when ED is appropriate.

I would not close his file because he is not engaging, and I would not simply increase unstructured contact. Both responses may reinforce the cycle. The better plan is structured care: scheduled appointments, staged psychological engagement, crisis plan, team formulation, clear communication limits and review of acute risk when he says he may drink and cut himself if left alone.

The system around Nathan also needs repair. The psychologist's requirement that he be more stable and abstinent before therapy may exclude him from the very treatment he needs, so staged engagement should be considered. The GP's diazepam prescribing because the mental health team will not help creates overdose, alcohol-interaction and dependence risks, so I would liaise urgently with the GP and offer a safer shared plan.`,
  },
  {
    id: "PSY-003",
    questionNumber: "MEQ-078",
    topic: "psychotherapy",
    difficulty: "consultant",
    title: "Chronic NSSI, ED Access Block and Therapeutic Nihilism",
    candidateRole: "Consultant psychiatrist, emergency psychiatry service",
    setting: "Busy metropolitan emergency department, Friday evening",
    stem: `You are the consultant psychiatrist covering a busy metropolitan emergency department on a Friday evening.

Jordan is a 26-year-old non-binary person with complex trauma, borderline personality disorder and chronic non-suicidal self-injury. They present after cutting their thigh with a razor following an argument with their partner. The wound requires suturing but is not life-threatening. Jordan says, "Cutting is the only way I stop myself from doing something worse."

Jordan has presented to ED twelve times in the past three months. The ED consultant says, "We can't keep admitting them every time they cut." A psychiatry registrar says Jordan is "low risk because it's superficial." The mental health nurse says staff are frustrated because Jordan often refuses discharge plans but later complains that nobody helps.

Jordan says, "If you send me home tonight, I'll just cut deeper." There are no psychiatric beds available, and the ED executive is calling hourly about mental health access block. Jordan's partner is in the waiting room and says they are exhausted and cannot provide supervision tonight.`,
    totalMarks: 22,
    signals: [
      { id: "s1", name: "Respectful care must recognise Jordan's identity and trauma", category: "cultural_safety", severity: "important", clueInStem: "Jordan is a 26-year-old non-binary person with complex trauma, borderline personality disorder and chronic non-suicidal self-injury.", whyItMatters: "Missing this signal means the candidate may reproduce invalidation by overlooking identity, trauma history and respectful language in crisis care.", modelWording: "Use respectful gender-affirming and trauma-informed engagement because invalidation can worsen distress and disengagement.", keywords: ["non-binary", "trauma-informed", "respectful language", "identity", "engagement"] },
      { id: "s2", name: "Self-harm function should guide crisis planning", category: "diagnosis_formulation", severity: "critical", clueInStem: "Jordan says, \"Cutting is the only way I stop myself from doing something worse.\"", whyItMatters: "Missing this signal means the candidate has treated cutting only as behaviour rather than understanding the function Jordan is describing.", modelWording: "Explore the function of cutting because Jordan is describing self-harm as affect regulation and prevention of something worse.", keywords: ["function of self-harm", "affect regulation", "distress tolerance", "something worse", "safety planning"] },
      { id: "s3", name: "Threat to cut deeper may indicate acute escalation", category: "risk_self", severity: "critical", clueInStem: "Jordan says, \"If you send me home tonight, I'll just cut deeper.\"", whyItMatters: "Missing this signal means the candidate has assumed chronic NSSI is static despite a stated escalation in lethality tonight.", modelWording: "Differentiate chronic NSSI from acute escalation by assessing intent, lethality, access to razors and ability to collaborate tonight.", keywords: ["acute escalation", "cut deeper", "NSSI", "lethality", "dynamic risk", "self-harm"] },
      { id: "s4", name: "Superficial wound is not a sufficient risk formulation", category: "risk_self", severity: "critical", clueInStem: "A psychiatry registrar says Jordan is \"low risk because it's superficial.\"", whyItMatters: "Missing this signal means the candidate has accepted wound depth as a false proxy for suicide or self-harm risk.", modelWording: "Correct the superficial-wound reasoning because risk depends on intent, escalation, function, supports and access to means.", keywords: ["superficial", "wound severity", "risk formulation", "intent", "poor proxy"] },
      { id: "s5", name: "ED therapeutic nihilism needs containment", category: "mdt_conflict", severity: "important", clueInStem: "The ED consultant says, \"We can't keep admitting them every time they cut.\"", whyItMatters: "Missing this signal means the candidate has allowed staff frustration to become the clinical rationale for discharge.", modelWording: "Address ED therapeutic nihilism by validating frustration while keeping decisions formulation-based and respectful.", keywords: ["therapeutic nihilism", "ED frustration", "BPD", "invalidation", "discharge pressure"] },
      { id: "s6", name: "Repeated ED use shows failed crisis system", category: "system_pressure", severity: "important", clueInStem: "Jordan has presented to ED twelve times in the past three months.", whyItMatters: "Missing this signal means the candidate has treated each presentation as isolated rather than recognising an ineffective crisis pathway.", modelWording: "Review the repeated ED pattern because twelve presentations in three months indicates the current crisis plan is not working.", keywords: ["repeated presentations", "crisis plan", "ED use", "system failure", "continuity"] },
      { id: "s7", name: "Partner cannot be used as tonight's supervision plan", category: "family_carer", severity: "important", clueInStem: "Jordan's partner is in the waiting room and says they are exhausted and cannot provide supervision tonight.", whyItMatters: "Missing this signal means the candidate has built discharge safety around a carer who explicitly cannot provide it.", modelWording: "Do not rely on partner supervision tonight because the partner is exhausted and has stated they cannot provide supervision.", keywords: ["partner", "exhausted", "cannot supervise", "carer burnout", "discharge safety"] },
      { id: "s8", name: "Access block must not override clinical reasoning", category: "system_pressure", severity: "important", clueInStem: "There are no psychiatric beds available, and the ED executive is calling hourly about mental health access block.", whyItMatters: "Missing this signal means the candidate has allowed lack of beds and executive pressure to replace an individual risk and care formulation.", modelWording: "Escalate access block while documenting independent clinical reasoning because bed unavailability is not a risk-management plan.", keywords: ["access block", "no beds", "executive pressure", "clinical reasoning", "least restrictive"] },
    ],
    priorityOrder: { urgent: ["s2", "s3", "s4"], secondary: ["s1", "s5", "s6", "s7", "s8"], lowYield: [] },
    modelAnswer: `Jordan's presentation needs respectful, trauma-informed and gender-affirming engagement from the outset. They are a non-binary person with complex trauma, borderline personality disorder and chronic non-suicidal self-injury, so invalidating or dismissive responses are likely to worsen distress and disengagement. The assessment should use their affirmed language and focus on function, safety and collaboration.

The wound requiring suturing but not being life-threatening does not make Jordan low risk. The registrar's statement that they are "low risk because it's superficial" is unsafe because wound depth is a poor proxy for intent, escalation or future risk. Jordan says, "Cutting is the only way I stop myself from doing something worse," so I would ask what the something worse is, how cutting functions, whether suicidal intent is present and whether the current episode differs from baseline.

The acute risk may be escalating tonight. Jordan says, "If you send me home tonight, I'll just cut deeper." That must be assessed as a possible increase in lethality, access to razors, distress and inability to collaborate, not dismissed because of repeated presentations. The fact that they have presented twelve times in three months shows the current crisis pathway is not working and needs review.

The ED team's countertransference must be contained. The ED consultant says, "We can't keep admitting them every time they cut," and staff are frustrated that Jordan refuses discharge plans but later complains that nobody helps. I would validate staff frustration while reframing the task as structured, boundaried and formulation-based care rather than reflexive admission or rejection.

Discharge cannot rely on Jordan's partner tonight because the partner is exhausted and explicitly says they cannot provide supervision. A safe plan would require wound care, removal of razors where possible, a written crisis plan, distress-tolerance strategies, specific follow-up, and an after-hours pathway that does not depend on an unavailable carer.

The lack of psychiatric beds and hourly executive calls about access block are real system pressures, but they are not a clinical risk plan. If acute risk cannot be safely managed at home, I would escalate access issues and consider short-stay or crisis stabilisation. If discharge is clinically appropriate, I would document why, what supports are in place, how means are managed and how Jordan can access help without repeated invalidating ED cycles.`,
  },
];
