import type { QuizStem } from "../quizData";

export const QA_STEMS: QuizStem[] = [
  {
    id: "QA-001",
    questionNumber: "MEQ-053",
    topic: "quality_assurance",
    difficulty: "consultant",
    title: "Lithium Toxicity Missed After Dose Increase",
    candidateRole: "Director of psychiatry reviewing a serious clinical incident",
    setting: "Community mental health service and Emergency Department interface",
    stem: `You are the director of psychiatry for a metropolitan community mental health service. A serious incident notification arrives on Monday morning. Priya, a 58-year-old woman with bipolar disorder, was admitted to ICU overnight with lithium toxicity and acute kidney injury.

Two weeks earlier, her lithium dose had been increased after she reported poor sleep and irritability. The clinic note states: "dose increased; pathology form given." There is no documented lithium level, renal function result, or plan for who would check the bloods. Five days later, Priya's daughter phoned the clinic saying her mother had "vomiting, tremor and seemed confused." The call was documented by an administrative officer and forwarded to the duty inbox. No clinician reviewed it until Friday afternoon.

On Friday evening, Priya presented to ED after a fall. ED documented dehydration and confusion but discharged her with "viral gastroenteritis" and GP follow-up. Her daughter has now made a complaint saying, "I told your service she was getting toxic and no one listened." Staff are anxious that the incident will be blamed on one junior doctor.`,
    totalMarks: 25,
    signals: [
      {
        id: "s1",
        name: "Lithium monitoring failure after dose increase",
        category: "physical_health",
        severity: "critical",
        clueInStem: "dose increased; pathology form given",
        whyItMatters: "A lithium dose increase requires clear monitoring responsibility, not merely handing out a pathology form. This is a foreseeable medication safety failure.",
        relatedRisk: "Lithium toxicity can cause delirium, falls, renal injury, seizures and death.",
        relatedSystem: "The service lacked a reliable closed-loop pathology monitoring process.",
        modelWording: "The phrase 'dose increased; pathology form given' signals unsafe lithium monitoring because there is no documented level, renal function check, or responsible clinician.",
        keywords: ["lithium", "dose increase", "bloods", "level", "renal", "pathology", "monitoring", "toxicity"],
      },
      {
        id: "s2",
        name: "Red-flag toxicity symptoms not escalated",
        category: "governance",
        severity: "critical",
        clueInStem: "vomiting, tremor and seemed confused",
        whyItMatters: "Vomiting, tremor and confusion after lithium dose change are toxicity red flags requiring same-day clinical review.",
        relatedRisk: "Delay allowed progression to ICU-level toxicity and acute kidney injury.",
        relatedSystem: "Administrative triage of clinical risk without escalation is a governance failure.",
        modelWording: "The daughter's report of 'vomiting, tremor and confusion' should have triggered urgent lithium toxicity assessment and medical review.",
        keywords: ["vomiting", "tremor", "confus", "red flag", "escalat", "urgent review", "toxicity", "daughter phoned"],
      },
      {
        id: "s3",
        name: "Duty inbox system failure",
        category: "system_pressure",
        severity: "critical",
        clueInStem: "forwarded to the duty inbox. No clinician reviewed it until Friday afternoon",
        whyItMatters: "A high-risk clinical message sitting in an inbox for days is a system design failure, not simply individual oversight.",
        relatedSystem: "Requires review of triage protocols, inbox ownership, escalation thresholds and audit trail.",
        modelWording: "The duty inbox delay shows a failed escalation system; the review must examine inbox ownership and clinical triage processes.",
        keywords: ["duty inbox", "no clinician", "delay", "system", "triage", "escalation", "workflow", "ownership"],
      },
      {
        id: "s4",
        name: "ED diagnostic anchoring despite dehydration and confusion",
        category: "mdt_conflict",
        severity: "important",
        clueInStem: "ED documented dehydration and confusion but discharged her with \"viral gastroenteritis\"",
        whyItMatters: "ED discharge despite dehydration and confusion in a lithium-treated patient suggests cross-service communication and diagnostic anchoring failure.",
        relatedSystem: "Requires joint mental health-ED review rather than blaming one service.",
        modelWording: "The ED finding of dehydration and confusion should have triggered lithium toxicity consideration and liaison with psychiatry.",
        keywords: ["ED", "dehydration", "confusion", "viral gastroenteritis", "anchoring", "liaison", "cross-service"],
      },
      {
        id: "s5",
        name: "Open disclosure to daughter",
        category: "family_carer",
        severity: "important",
        clueInStem: "I told your service she was getting toxic and no one listened",
        whyItMatters: "The daughter gave accurate risk information that was not acted on. She requires timely open disclosure and acknowledgement.",
        relatedSystem: "Family concerns must be treated as clinical data within safety systems.",
        modelWording: "The daughter's complaint requires open disclosure, apology for communication failure, and explanation of the review process.",
        keywords: ["daughter", "complaint", "open disclosure", "apology", "family concern", "not listened", "carer"],
      },
      {
        id: "s6",
        name: "Avoid scapegoating junior doctor",
        category: "governance",
        severity: "important",
        clueInStem: "Staff are anxious that the incident will be blamed on one junior doctor",
        whyItMatters: "Quality review should identify system contributors and supervision gaps, not simply individual blame.",
        relatedSystem: "A just-culture review supports learning while still addressing accountability.",
        modelWording: "The review should use a just-culture approach: examine system design, supervision and accountability without scapegoating a junior doctor.",
        keywords: ["junior doctor", "blamed", "just culture", "system contributors", "supervision", "accountability"],
      },
    ],
    priorityOrder: {
      urgent: ["s1", "s2", "s3"],
      secondary: ["s4", "s5", "s6"],
      lowYield: [],
    },
    modelAnswer: `This is a serious medication safety incident requiring immediate clinical governance response. The lithium dose increase was not safely monitored: "pathology form given" is not a monitoring plan. The daughter's report of vomiting, tremor and confusion was a lithium toxicity red flag and should have triggered same-day review. The duty inbox delay indicates a system failure in triage, ownership and escalation.

I would ensure Priya's current medical care is safe, notify senior service leadership, complete incident reporting and begin open disclosure with the daughter. The review should include community psychiatry, ED, administration and pharmacy because the failure crossed service boundaries. It should not be framed as one junior doctor's error; it requires a just-culture review of lithium monitoring, inbox processes, supervision, documentation and ED-psychiatry communication.`,
  },
  {
    id: "QA-002",
    questionNumber: "MEQ-054",
    topic: "quality_assurance",
    difficulty: "consultant",
    title: "Clozapine Neutropenia Alert Not Acted On",
    candidateRole: "Consultant psychiatrist leading a medication safety review",
    setting: "Public community clozapine clinic",
    stem: `You are the consultant psychiatrist responsible for a community clozapine clinic. A pharmacy manager contacts you because Daniel, a 36-year-old man with treatment-resistant schizophrenia, was dispensed clozapine for seven days despite a pathology alert stating "red result — neutrophils below threshold."

The clozapine nurse was on leave. The covering nurse documented "bloods uploaded; pharmacy to confirm." The junior registrar signed the script remotely from another site and did not review the pathology system. The pharmacist says the electronic system displayed a red warning, but the clinic had previously told the pharmacy to "continue dispensing unless psychiatry phones to stop."

Daniel presented to ED three days later with fever and mouth ulcers. His mother says she had called the clinic twice reporting he was "shivering and not eating." Both calls were documented as "mother anxious; reassure." The service manager asks whether this can be managed as a pharmacy error to avoid a formal serious incident review.`,
    totalMarks: 25,
    signals: [
      {
        id: "s1",
        name: "Critical clozapine red result ignored",
        category: "physical_health",
        severity: "critical",
        clueInStem: "red result — neutrophils below threshold",
        whyItMatters: "A neutrophil result below threshold is a critical clozapine safety trigger requiring immediate clinical action.",
        relatedRisk: "Risk of agranulocytosis, sepsis and death.",
        relatedSystem: "Requires robust clozapine monitoring governance and stop-dispense escalation.",
        modelWording: "The 'red result — neutrophils below threshold' is the central safety signal; clozapine should not continue without urgent review.",
        keywords: ["clozapine", "neutrophil", "red result", "below threshold", "agranulocytosis", "blood", "stop", "alert"],
      },
      {
        id: "s2",
        name: "Unsafe remote prescribing without pathology review",
        category: "governance",
        severity: "critical",
        clueInStem: "registrar signed the script remotely from another site and did not review the pathology system",
        whyItMatters: "Clozapine prescribing requires confirmation of safe blood monitoring; remote signing without pathology review is unsafe.",
        relatedSystem: "Highlights supervision, prescribing authority and electronic safety workflow failures.",
        modelWording: "The registrar's remote signature without pathology review is a prescribing governance failure requiring supervision review.",
        keywords: ["registrar", "remote", "signed", "did not review", "pathology", "prescribing", "supervision"],
      },
      {
        id: "s3",
        name: "Ambiguous pharmacy-clinic stop rule",
        category: "system_pressure",
        severity: "critical",
        clueInStem: "continue dispensing unless psychiatry phones to stop",
        whyItMatters: "This reverses the safety default. For clozapine red results, the default should be stop/escalate unless explicitly cleared.",
        relatedSystem: "Requires shared protocol between pharmacy and psychiatry.",
        modelWording: "The instruction to 'continue dispensing unless psychiatry phones to stop' is an unsafe system rule for clozapine red alerts.",
        keywords: ["continue dispensing", "phones to stop", "pharmacy", "protocol", "default", "dispense", "red warning"],
      },
      {
        id: "s4",
        name: "Fever and mouth ulcers as infection red flags",
        category: "immediate_safety",
        severity: "critical",
        clueInStem: "fever and mouth ulcers",
        whyItMatters: "Fever and mouth ulcers in a patient on clozapine after low neutrophils indicate possible severe infection and require urgent medical treatment.",
        relatedRisk: "Possible neutropenic sepsis.",
        modelWording: "Fever and mouth ulcers in the context of clozapine neutropenia should be treated as possible neutropenic sepsis.",
        keywords: ["fever", "mouth ulcers", "infection", "sepsis", "neutropenic", "urgent medical"],
      },
      {
        id: "s5",
        name: "Carer escalation dismissed",
        category: "family_carer",
        severity: "important",
        clueInStem: "mother called the clinic twice reporting he was \"shivering and not eating\"",
        whyItMatters: "The mother provided clinically important deterioration information that was minimised.",
        relatedSystem: "Carer calls need clinical triage criteria rather than reassurance by default.",
        modelWording: "The mother's reports of shivering and not eating were clinical deterioration signals, not simply anxiety.",
        keywords: ["mother", "called twice", "shivering", "not eating", "carer", "reassure", "deterioration"],
      },
      {
        id: "s6",
        name: "Inappropriate attempt to avoid serious incident review",
        category: "governance",
        severity: "important",
        clueInStem: "managed as a pharmacy error to avoid a formal serious incident review",
        whyItMatters: "This is a multi-system failure involving clinic, pharmacy, prescribing, pathology and carer communication. Avoiding review is unsafe governance.",
        relatedSystem: "Requires formal incident reporting, open disclosure and system learning.",
        modelWording: "This cannot be framed as a pharmacy error alone; it requires formal serious incident review across the clozapine pathway.",
        keywords: ["avoid", "serious incident", "pharmacy error", "formal review", "governance", "incident report", "system failure"],
      },
    ],
    priorityOrder: {
      urgent: ["s1", "s2", "s3", "s4"],
      secondary: ["s5", "s6"],
      lowYield: [],
    },
    modelAnswer: `The immediate priority is Daniel's safety: fever and mouth ulcers after a neutrophil red result should be treated as possible neutropenic sepsis. Clozapine dispensing despite "neutrophils below threshold" is a serious medication safety failure.

This is not a pharmacy error alone. The unsafe chain includes the covering nurse note, remote registrar prescribing without pathology review, an unsafe pharmacy instruction to continue dispensing unless told to stop, and dismissal of the mother's deterioration calls. I would ensure incident reporting, notify senior governance leads, commence open disclosure with Daniel and his mother, and conduct a multi-agency clozapine pathway review. Corrective actions include clear stop-dispense rules, pathology alert ownership, prescriber responsibilities, leave cover, and carer escalation protocols.`,
  },
  {
    id: "QA-003",
    questionNumber: "MEQ-055",
    topic: "quality_assurance",
    difficulty: "consultant",
    title: "Seclusion Injury and Incomplete Documentation",
    candidateRole: "Clinical director reviewing restrictive practice governance",
    setting: "Acute inpatient mental health unit",
    stem: `You are the clinical director of an acute inpatient mental health unit. Overnight, Lena, a 29-year-old woman admitted with psychosis and a history of childhood sexual trauma, was secluded after throwing a plastic chair at the nurses' station. At 3 am she was found on the floor of the seclusion room with a fractured wrist.

The seclusion form states "agitated, unsafe, secluded as per policy." There is no documented attempted de-escalation, no consultant notification, no review time, and no physical observation chart for the first 45 minutes. CCTV shows Lena repeatedly banging on the door and yelling, "Don't lock me in, he locked me in before." A junior nurse says staffing was short and "there was no time to keep writing." The night registrar says security advised seclusion and "everyone agreed." Lena's sister has phoned demanding to know why trauma history was ignored.`,
    totalMarks: 25,
    signals: [
      {
        id: "s1",
        name: "Restrictive practice injury is a serious incident",
        category: "governance",
        severity: "critical",
        clueInStem: "found on the floor of the seclusion room with a fractured wrist",
        whyItMatters: "An injury occurring during seclusion requires immediate clinical review, incident reporting and governance investigation.",
        relatedSystem: "Restrictive practices require heightened oversight and documentation.",
        modelWording: "A fractured wrist in seclusion is a serious restrictive-practice incident requiring immediate reporting and review.",
        keywords: ["fractured wrist", "seclusion", "serious incident", "restrictive practice", "injury", "report", "review"],
      },
      {
        id: "s2",
        name: "Failure to document least restrictive alternatives",
        category: "mental_health_act",
        severity: "critical",
        clueInStem: "There is no documented attempted de-escalation",
        whyItMatters: "Seclusion must be justified as necessary and least restrictive; absence of de-escalation documentation is a major governance failure.",
        relatedLegal: "Restrictive practice legality depends on necessity, proportionality and documentation.",
        modelWording: "No documented attempted de-escalation means the team has not demonstrated that seclusion was the least restrictive option.",
        keywords: ["de-escalation", "least restrictive", "seclusion", "necessity", "proportionate", "alternative", "document"],
      },
      {
        id: "s3",
        name: "Observation failure in seclusion",
        category: "immediate_safety",
        severity: "critical",
        clueInStem: "no physical observation chart for the first 45 minutes",
        whyItMatters: "Seclusion requires regular observation to detect injury, collapse, distress and physical deterioration.",
        relatedRisk: "Observation gap may have contributed to delayed detection of injury.",
        modelWording: "The 45-minute absence of physical observations is an immediate patient safety failure.",
        keywords: ["observation", "45 minutes", "physical observations", "chart", "monitor", "seclusion room"],
      },
      {
        id: "s4",
        name: "Trauma-informed care failure",
        category: "trauma",
        severity: "critical",
        clueInStem: "Don't lock me in, he locked me in before",
        whyItMatters: "The patient explicitly linked being locked in to prior trauma; seclusion risked re-traumatisation and escalation.",
        relatedCultural: "Trauma history must shape restrictive practice planning, not sit as background information.",
        modelWording: "The phrase 'Don't lock me in, he locked me in before' should have triggered trauma-informed alternatives and heightened review.",
        keywords: ["trauma", "locked me in", "re-traumatisation", "childhood sexual trauma", "trauma-informed", "distress"],
      },
      {
        id: "s5",
        name: "Consultant notification failure",
        category: "mdt_conflict",
        severity: "important",
        clueInStem: "no consultant notification",
        whyItMatters: "Restrictive practice involving injury and complex trauma requires senior medical oversight.",
        relatedSystem: "Consultant accountability cannot be replaced by security or informal team agreement.",
        modelWording: "No consultant notification is a governance and supervision failure in restrictive practice.",
        keywords: ["consultant notification", "senior review", "medical oversight", "supervision", "notify consultant"],
      },
      {
        id: "s6",
        name: "Staffing pressure does not remove documentation obligation",
        category: "system_pressure",
        severity: "important",
        clueInStem: "staffing was short and \"there was no time to keep writing\"",
        whyItMatters: "Staffing pressure is a system factor to review, but it does not remove the requirement to document restrictive practices.",
        relatedSystem: "Requires review of night staffing, acuity, training and escalation.",
        modelWording: "Short staffing is relevant as a systems contributor, but cannot justify absent seclusion documentation.",
        keywords: ["staffing", "short", "no time", "documentation", "night", "acuity", "system factor"],
      },
    ],
    priorityOrder: {
      urgent: ["s1", "s2", "s3", "s4"],
      secondary: ["s5", "s6"],
      lowYield: [],
    },
    modelAnswer: `This is a serious restrictive-practice incident. Lena sustained a fractured wrist in seclusion, with no documented de-escalation, no review time, no consultant notification and no observation chart for 45 minutes. I would first ensure her physical injury and psychological distress are addressed, notify senior management, complete incident reporting, preserve records including CCTV, and commence open disclosure with Lena and, with consent or appropriate authority, her sister.

The review must examine whether seclusion was necessary, proportionate and least restrictive. The phrase "Don't lock me in, he locked me in before" makes trauma-informed failure central, not incidental. Staffing pressure is a systems contributor but does not remove documentation and observation obligations. The consultant response should include staff debrief, restrictive practice audit, training, and review of night staffing and escalation pathways.`,
  },
  {
    id: "QA-004",
    questionNumber: "MEQ-056",
    topic: "quality_assurance",
    difficulty: "consultant",
    title: "Absconding From ED After Delayed Psychiatric Review",
    candidateRole: "Consultant psychiatrist asked to review an ED adverse event",
    setting: "Overcrowded metropolitan Emergency Department",
    stem: `You are the consultant psychiatrist responsible for ED liaison. At 7 am you are told that Omar, a 22-year-old man brought in by police under an emergency apprehension power, absconded from ED at 2 am and was later found on railway tracks with serious injuries.

He had presented at 8 pm with persecutory beliefs that "the police implanted a tracker in my jaw." He was pacing, refusing oral medication, and repeatedly asking where the exits were. The ED was overcrowded and Omar was placed in a corridor bay because no mental health assessment room was available. The triage note states "psychiatry aware; review when able." The mental health nurse was covering two hospitals by phone. Security had been asked to "keep an eye on him" but there was no documented observation level.

At midnight, the ED medical registrar documented "likely drug-induced psychosis; medically cleared." No urine drug screen was obtained. Omar's father phoned ED saying Omar had not slept for five nights and had recently bought a knife because "people are coming." This was not entered into the chart.`,
    totalMarks: 25,
    signals: [
      {
        id: "s1",
        name: "Absconding with serious injury is a sentinel safety event",
        category: "governance",
        severity: "critical",
        clueInStem: "absconded from ED at 2 am and was later found on railway tracks with serious injuries",
        whyItMatters: "Absconding from ED followed by serious harm requires immediate incident reporting and systems review.",
        relatedRisk: "Severe risk to self due to psychosis, disorganisation and unsafe environment.",
        relatedSystem: "Requires review of ED observation, mental health escalation and environmental safety.",
        modelWording: "Absconding followed by railway-track injury is a serious safety incident requiring formal governance review.",
        keywords: ["abscond", "railway", "serious injuries", "sentinel", "incident", "adverse event", "safety"],
      },
      {
        id: "s2",
        name: "High absconding risk was visible before the event",
        category: "immediate_safety",
        severity: "critical",
        clueInStem: "repeatedly asking where the exits were",
        whyItMatters: "Repeated exit-seeking in a psychotic patient under emergency powers is a direct absconding signal.",
        relatedRisk: "Failure to set observation level exposed Omar to preventable harm.",
        modelWording: "Asking where the exits were should have triggered absconding-risk precautions and documented observations.",
        keywords: ["exits", "exit", "absconding risk", "observation", "pacing", "leave", "precaution"],
      },
      {
        id: "s3",
        name: "No documented observation level",
        category: "governance",
        severity: "critical",
        clueInStem: "there was no documented observation level",
        whyItMatters: "Security being asked informally to watch a patient is not a clinical observation plan.",
        relatedSystem: "Requires clear ownership of observations between ED, mental health and security.",
        modelWording: "The absence of a documented observation level is a core safety and governance failure.",
        keywords: ["observation level", "security", "keep an eye", "documented", "watch", "ownership"],
      },
      {
        id: "s4",
        name: "Unsafe corridor placement due to lack of assessment room",
        category: "system_pressure",
        severity: "important",
        clueInStem: "placed in a corridor bay because no mental health assessment room was available",
        whyItMatters: "The environment increased stimulation, absconding opportunity and risk; resource constraints must be named as system contributors.",
        relatedSystem: "Requires escalation pathway when no safe assessment space exists.",
        modelWording: "The corridor bay placement is a system risk factor, not just a logistical detail.",
        keywords: ["corridor", "assessment room", "overcrowded", "environment", "safe space", "resource"],
      },
      {
        id: "s5",
        name: "Collateral about weapon and insomnia not documented",
        category: "collateral",
        severity: "critical",
        clueInStem: "father phoned ED saying Omar had not slept for five nights and had recently bought a knife",
        whyItMatters: "Collateral indicated escalating psychosis, sleep deprivation and weapon acquisition; failure to document removed critical risk information.",
        relatedRisk: "Risk to self and others was higher than recorded.",
        modelWording: "The father's collateral about five nights without sleep and knife purchase was critical risk information and should have been documented and acted on.",
        keywords: ["father", "five nights", "knife", "collateral", "not documented", "weapon", "sleep"],
      },
      {
        id: "s6",
        name: "Premature diagnostic closure on drug-induced psychosis",
        category: "diagnosis_formulation",
        severity: "important",
        clueInStem: "likely drug-induced psychosis; medically cleared",
        whyItMatters: "Drug-induced psychosis was assumed without testing or collateral integration; diagnostic closure contributed to under-triage.",
        modelWording: "The phrase 'likely drug-induced psychosis' was premature diagnostic closure and did not address immediate risk.",
        keywords: ["drug-induced", "diagnostic closure", "medically cleared", "urine", "premature", "formulation"],
      },
    ],
    priorityOrder: {
      urgent: ["s1", "s2", "s3", "s5"],
      secondary: ["s4", "s6"],
      lowYield: [],
    },
    modelAnswer: `This is a serious ED mental health adverse event: Omar absconded under emergency powers and sustained severe injury. The risk was visible in the stem: persecutory psychosis, pacing, refusal of medication, repeated exit-seeking, collateral about five nights without sleep and knife purchase, and no documented observation level.

I would ensure Omar's immediate medical care, notify senior ED and mental health leadership, complete incident reporting, preserve records, and contact family through open disclosure processes. The review should focus on systems: corridor placement, lack of mental health room, unclear observation ownership, phone-only mental health cover, poor collateral documentation and premature diagnostic closure. Security cannot substitute for a documented clinical observation plan.`,
  },
  {
    id: "QA-005",
    questionNumber: "MEQ-057",
    topic: "quality_assurance",
    difficulty: "consultant",
    title: "Wrong Patient Long-Acting Injection",
    candidateRole: "Consultant psychiatrist leading immediate response to a medication error",
    setting: "Community depot clinic",
    stem: `You are the consultant psychiatrist covering a busy community depot clinic. A nurse phones you distressed after realising that Sam, a 44-year-old man prescribed oral sertraline only, was given paliperidone long-acting injection intended for another patient with the same surname.

The clinic was running 50 minutes late. The usual two-nurse identity check was not completed because one nurse was called to an urgent home visit. The medication fridge contained two depot packs with handwritten sticky notes rather than printed labels. Sam questioned the injection, saying, "I don't usually have needles," but the nurse reassured him that "the doctor changed the plan." No doctor had changed the plan.

Sam has a history of severe neuroleptic sensitivity and works as a truck driver. He is angry and wants to leave immediately. The team leader says, "Can we just apologise and monitor him? Reporting this will make the service look unsafe."`,
    totalMarks: 25,
    signals: [
      {
        id: "s1",
        name: "Wrong patient LAI administration",
        category: "governance",
        severity: "critical",
        clueInStem: "given paliperidone long-acting injection intended for another patient with the same surname",
        whyItMatters: "Wrong-patient medication administration is a serious medication incident requiring urgent clinical and governance response.",
        relatedRisk: "Paliperidone LAI cannot be rapidly removed and may cause prolonged adverse effects.",
        modelWording: "This is a serious wrong-patient LAI administration error, not a minor clinic mistake.",
        keywords: ["wrong patient", "paliperidone", "long-acting", "LAI", "same surname", "medication error", "depot"],
      },
      {
        id: "s2",
        name: "Failure of identity-check procedure",
        category: "governance",
        severity: "critical",
        clueInStem: "usual two-nurse identity check was not completed",
        whyItMatters: "The failed identity check is the core preventable safety barrier that should have stopped the error.",
        relatedSystem: "Requires review of clinic workflow, staffing and mandatory checking process.",
        modelWording: "The missed two-nurse identity check is a failed medication safety barrier.",
        keywords: ["identity check", "two-nurse", "not completed", "checking", "safety barrier", "ID"],
      },
      {
        id: "s3",
        name: "Unsafe medication labelling system",
        category: "system_pressure",
        severity: "important",
        clueInStem: "handwritten sticky notes rather than printed labels",
        whyItMatters: "Handwritten sticky notes on depot packs create foreseeable selection and identification errors.",
        relatedSystem: "Requires medication storage and labelling redesign.",
        modelWording: "Handwritten sticky notes in the medication fridge are an unsafe system design issue.",
        keywords: ["sticky notes", "printed labels", "labelling", "fridge", "storage", "system design"],
      },
      {
        id: "s4",
        name: "Patient voiced discrepancy but was overridden",
        category: "ethics",
        severity: "critical",
        clueInStem: "I don't usually have needles",
        whyItMatters: "The patient's concern was a final safety alert. Overriding it without checking worsened the error and undermined trust.",
        modelWording: "Sam's statement 'I don't usually have needles' should have stopped administration and triggered immediate verification.",
        keywords: ["don't usually have needles", "questioned", "patient concern", "overridden", "verify", "stopped"],
      },
      {
        id: "s5",
        name: "Need for immediate clinical monitoring and driving advice",
        category: "physical_health",
        severity: "important",
        clueInStem: "history of severe neuroleptic sensitivity and works as a truck driver",
        whyItMatters: "The error creates occupational and physical safety risks requiring monitoring, advice about driving, and follow-up.",
        relatedRisk: "Sedation, EPS or akathisia could endanger Sam and the public if he drives.",
        modelWording: "His neuroleptic sensitivity and truck-driving work mean he needs urgent medical advice, monitoring and driving safety discussion.",
        keywords: ["neuroleptic sensitivity", "truck driver", "driving", "monitor", "EPS", "sedation", "occupational"],
      },
      {
        id: "s6",
        name: "Attempt to avoid reporting is a governance failure",
        category: "governance",
        severity: "important",
        clueInStem: "Reporting this will make the service look unsafe",
        whyItMatters: "Avoiding incident reporting prioritises reputation over patient safety and prevents system learning.",
        relatedSystem: "Requires incident reporting, open disclosure and medication safety review.",
        modelWording: "The team leader's suggestion not to report is itself a governance concern; this requires formal reporting and open disclosure.",
        keywords: ["reporting", "look unsafe", "avoid", "incident", "open disclosure", "reputation", "governance"],
      },
    ],
    priorityOrder: {
      urgent: ["s1", "s2", "s4"],
      secondary: ["s3", "s5", "s6"],
      lowYield: [],
    },
    modelAnswer: `This is a serious wrong-patient LAI medication error. Immediate priorities are Sam's safety, honest disclosure, medical monitoring and practical risk management. Paliperidone LAI cannot be withdrawn, and Sam has severe neuroleptic sensitivity and works as a truck driver, so he needs advice about adverse effects, driving, emergency contacts and follow-up.

The error was not simply individual nurse failure. Safety barriers failed: the two-nurse identity check was skipped, depot packs had handwritten sticky notes, the clinic was under pressure, and Sam's statement "I don't usually have needles" was overridden. The team leader's wish to avoid reporting is inappropriate. I would ensure formal incident reporting, open disclosure, medication safety review, staff support and redesign of identity checking and labelling systems.`,
  },
  {
    id: "QA-006",
    questionNumber: "MEQ-058",
    topic: "quality_assurance",
    difficulty: "consultant",
    title: "Interpreter Failure and Cultural Safety Complaint",
    candidateRole: "Service clinical lead responding to a complaint",
    setting: "Consultation-liaison psychiatry service",
    stem: `You are the clinical lead for a consultation-liaison psychiatry service. A complaint is received from the family of Mrs Tran, a 72-year-old Vietnamese-speaking woman admitted with delirium secondary to urosepsis. Psychiatry was asked to assess "refusal of antibiotics and possible depression."

The note states "patient lacks capacity; family agree with treatment." The assessment was conducted using Mrs Tran's adult son as interpreter. No professional interpreter was used. The son later told staff that his mother was "ashamed and did not want strangers to know family business." Nursing notes from the same morning describe Mrs Tran as fluctuating, pulling at lines, and speaking to deceased relatives. The psychiatry note contains no cognitive assessment, no delirium formulation, and no record of the actual decision being assessed.

Mrs Tran was physically restrained for IV antibiotics. Her daughter says no one explained why restraint was used and that the family now believes the hospital "treated her like a difficult migrant rather than a sick older woman."`,
    totalMarks: 25,
    signals: [
      {
        id: "s1",
        name: "Capacity assessment invalid without professional interpreter",
        category: "capacity",
        severity: "critical",
        clueInStem: "conducted using Mrs Tran's adult son as interpreter. No professional interpreter was used",
        whyItMatters: "Capacity assessment through a family interpreter is unreliable, compromises autonomy and may distort information.",
        relatedLegal: "Capacity is decision-specific and requires effective communication.",
        relatedCultural: "Language access is part of culturally safe care, not an optional courtesy.",
        modelWording: "The capacity assessment is procedurally unsafe because it was done through her son without a professional interpreter.",
        keywords: ["interpreter", "professional interpreter", "son", "capacity", "language", "procedurally", "communication"],
      },
      {
        id: "s2",
        name: "Delirium missed despite fluctuating cognition",
        category: "diagnosis_formulation",
        severity: "critical",
        clueInStem: "fluctuating, pulling at lines, and speaking to deceased relatives",
        whyItMatters: "These are delirium features in the context of urosepsis and must guide capacity and treatment decisions.",
        relatedRisk: "Mislabeling delirium as refusal or depression can lead to unsafe coercion and poor medical care.",
        modelWording: "Fluctuation, line-pulling and speaking to deceased relatives point to delirium, not simply depression or difficult behaviour.",
        keywords: ["delirium", "fluctuat", "pulling at lines", "deceased relatives", "urosepsis", "cognitive", "confusion"],
      },
      {
        id: "s3",
        name: "No decision-specific capacity documentation",
        category: "consent_refusal",
        severity: "critical",
        clueInStem: "no record of the actual decision being assessed",
        whyItMatters: "Capacity cannot be documented globally; the specific treatment decision and reasoning abilities must be recorded.",
        relatedLegal: "Invalid documentation weakens authority for treatment and restraint.",
        modelWording: "The note fails because it does not state the specific decision, information provided, understanding, weighing, or communication.",
        keywords: ["decision-specific", "actual decision", "understand", "weigh", "capacity documentation", "global"],
      },
      {
        id: "s4",
        name: "Restrictive treatment requires explanation and documentation",
        category: "mental_health_act",
        severity: "important",
        clueInStem: "physically restrained for IV antibiotics",
        whyItMatters: "Physical restraint for medical treatment requires legal authority, proportionality, monitoring and family communication.",
        relatedLegal: "Must clarify legal pathway for treatment without consent depending on jurisdiction.",
        modelWording: "The restraint for IV antibiotics required clear legal authority, least-restrictive justification and monitoring.",
        keywords: ["physically restrained", "IV antibiotics", "restraint", "least restrictive", "legal authority", "proportionate"],
      },
      {
        id: "s5",
        name: "Cultural safety failure perceived by family",
        category: "cultural_safety",
        severity: "important",
        clueInStem: "treated her like a difficult migrant rather than a sick older woman",
        whyItMatters: "The family's complaint identifies cultural unsafety and perceived discrimination, which affects trust and engagement.",
        relatedCultural: "Cultural safety includes how care is experienced by patient and family.",
        modelWording: "The phrase 'difficult migrant' signals a cultural safety complaint, not merely dissatisfaction with communication.",
        keywords: ["difficult migrant", "cultural safety", "discrimination", "migrant", "family complaint", "trust"],
      },
      {
        id: "s6",
        name: "Poor CL psychiatry documentation quality",
        category: "governance",
        severity: "important",
        clueInStem: "no cognitive assessment, no delirium formulation",
        whyItMatters: "A CL opinion that drives coercive medical treatment must document cognition, delirium, capacity and legal reasoning.",
        relatedSystem: "Requires supervision, audit and documentation improvement.",
        modelWording: "The CL note is unsafe because it lacks cognitive assessment and delirium formulation despite being used to justify treatment.",
        keywords: ["no cognitive assessment", "no delirium formulation", "CL note", "documentation", "audit", "supervision"],
      },
    ],
    priorityOrder: {
      urgent: ["s1", "s2", "s3"],
      secondary: ["s4", "s5", "s6"],
      lowYield: [],
    },
    modelAnswer: `The complaint identifies failures in delirium recognition, interpreter use, capacity documentation, restrictive practice and cultural safety. A capacity assessment through an adult son without a professional interpreter is procedurally unsafe. The nursing description of fluctuation, line-pulling and speaking to deceased relatives strongly suggests delirium in urosepsis, yet the psychiatry note contains no cognitive assessment or delirium formulation.

I would review Mrs Tran's current safety, meet the family with a professional interpreter, acknowledge concerns, and explain the review process. The governance response should examine legal authority and documentation for restraint, CL supervision, capacity-assessment quality, interpreter policy compliance and cultural safety. The family statement that she was treated like a "difficult migrant" must be addressed as a clinical safety and trust issue, not dismissed as offence-taking.`,
  },
  {
    id: "QA-007",
    questionNumber: "MEQ-059",
    topic: "quality_assurance",
    difficulty: "consultant",
    title: "Unsafe Weekend Discharge Under Bed Pressure",
    candidateRole: "Consultant psychiatrist reviewing bed-pressure discharge practice",
    setting: "Acute adult inpatient unit",
    stem: `You are the consultant psychiatrist covering an acute adult unit. On Monday morning, the bed manager asks you to review a complaint. Over the weekend, Nikhil, a 27-year-old man admitted after a serious overdose, was discharged to create a bed for an aggressive patient waiting in ED.

The Saturday registrar note says: "No SI today. Bed pressure high. Discharge with crisis number." The discharge occurred without consultant discussion. Nikhil's partner had told nursing staff that morning he was "still giving away possessions and saying I will be free soon." This was written in the nursing continuation notes but not communicated at handover. The discharge summary was auto-generated and sent to the wrong GP. There was no medication supply plan; Nikhil left without antidepressants or follow-up appointment.

On Sunday night Nikhil re-presented after cutting his forearm. His partner says, "You discharged the bed, not the patient." Staff say bed pressure was extreme and ED was unsafe.`,
    totalMarks: 25,
    signals: [
      {
        id: "s1",
        name: "Unsafe discharge driven by bed pressure",
        category: "system_pressure",
        severity: "critical",
        clueInStem: "discharged to create a bed for an aggressive patient waiting in ED",
        whyItMatters: "Bed pressure is a system reality but cannot override clinical discharge safety.",
        relatedSystem: "Requires escalation and transparent risk decision-making, not unsafe displacement.",
        modelWording: "The phrase 'discharged to create a bed' signals unsafe system-driven discharge rather than clinically justified discharge.",
        keywords: ["bed pressure", "create a bed", "discharged the bed", "system pressure", "unsafe discharge", "ED waiting"],
      },
      {
        id: "s2",
        name: "Suicide risk warning ignored",
        category: "risk_self",
        severity: "critical",
        clueInStem: "still giving away possessions and saying I will be free soon",
        whyItMatters: "Giving away possessions and future-oriented death statements are high-risk suicide warning signs.",
        relatedRisk: "Recent serious overdose plus ongoing warning signs makes discharge unsafe.",
        modelWording: "The partner's report of giving away possessions and saying 'I will be free soon' should have stopped discharge and triggered senior review.",
        keywords: ["giving away possessions", "free soon", "partner", "warning sign", "suicide", "recent overdose"],
      },
      {
        id: "s3",
        name: "No consultant discussion for high-risk discharge",
        category: "governance",
        severity: "critical",
        clueInStem: "without consultant discussion",
        whyItMatters: "High-risk discharge after serious overdose under bed pressure requires consultant-level decision-making and documentation.",
        relatedSystem: "Registrar should not carry this governance burden alone.",
        modelWording: "Discharge after serious overdose under bed pressure without consultant discussion is a supervision and governance failure.",
        keywords: ["without consultant", "consultant discussion", "supervision", "registrar", "high-risk discharge"],
      },
      {
        id: "s4",
        name: "Handover failure of critical collateral",
        category: "collateral",
        severity: "important",
        clueInStem: "written in the nursing continuation notes but not communicated at handover",
        whyItMatters: "Critical collateral was present in the record but not transferred into the decision-making process.",
        relatedSystem: "Requires structured handover and escalation of family risk information.",
        modelWording: "The nursing note was not enough; the partner's warning needed active handover to the decision-maker.",
        keywords: ["handover", "nursing notes", "not communicated", "collateral", "partner", "continuation notes"],
      },
      {
        id: "s5",
        name: "Faulty discharge communication to GP",
        category: "disposition",
        severity: "important",
        clueInStem: "discharge summary was auto-generated and sent to the wrong GP",
        whyItMatters: "Sending the discharge summary to the wrong GP undermines continuity and safety during the high-risk post-discharge period.",
        relatedSystem: "Requires discharge communication audit and patient identifier verification.",
        modelWording: "The wrong-GP discharge summary is a continuity-of-care failure in a high-risk discharge.",
        keywords: ["wrong GP", "discharge summary", "auto-generated", "communication", "continuity", "GP"],
      },
      {
        id: "s6",
        name: "No medication or follow-up plan",
        category: "disposition",
        severity: "important",
        clueInStem: "left without antidepressants or follow-up appointment",
        whyItMatters: "Discharge after serious overdose requires medication plan, follow-up timing, safety plan and crisis pathway.",
        modelWording: "Leaving without medication supply or follow-up appointment shows discharge planning failure.",
        keywords: ["without antidepressants", "follow-up appointment", "medication supply", "discharge plan", "crisis number"],
      },
    ],
    priorityOrder: {
      urgent: ["s1", "s2", "s3"],
      secondary: ["s4", "s5", "s6"],
      lowYield: [],
    },
    modelAnswer: `This is an unsafe system-driven discharge. Bed pressure was real, but the phrase "discharged to create a bed" shows clinical need was displaced by service pressure. Nikhil had a recent serious overdose and his partner reported giving away possessions and saying "I will be free soon" on the morning of discharge. That collateral should have triggered senior review, not weekend discharge.

I would review Nikhil's current risk, communicate with his partner, complete incident reporting and conduct open disclosure. The governance review must examine consultant escalation, registrar supervision, handover of nursing collateral, discharge summary errors, wrong-GP communication, absence of medication supply and lack of follow-up. The system issue is not solved by blaming the registrar; it requires a safe bed-pressure escalation pathway.`,
  },
  {
    id: "QA-008",
    questionNumber: "MEQ-060",
    topic: "quality_assurance",
    difficulty: "consultant",
    title: "Child Protection Signal Missed in Perinatal Admission",
    candidateRole: "Clinical director reviewing perinatal service safety",
    setting: "Mother-baby liaison pathway in a general hospital",
    stem: `You are the clinical director asked to review a perinatal psychiatry complaint. Alana, a 32-year-old woman, was admitted to the postnatal ward five days after delivery. Midwives documented that she had not slept for three nights, was whispering that "the baby is contaminated," and refused to let staff weigh the baby. Psychiatry reviewed her at 11 pm and documented "anxious mother; no SI; discharge with community follow-up."

The next day, Alana's partner phoned the hospital saying she had locked herself and the baby in the bathroom and was praying loudly. He said he had told the night registrar that Alana's sister had postpartum psychosis and that Alana had stopped quetiapine during pregnancy. These details do not appear in the psychiatry note. Community follow-up was booked for seven days later.

Child protection was not contacted. The baby was brought back to hospital dehydrated 36 hours later. The midwifery manager asks whether psychiatry should apologise, because "technically she denied wanting to hurt the baby."`,
    totalMarks: 25,
    signals: [
      {
        id: "s1",
        name: "Postpartum psychosis red flags missed",
        category: "diagnosis_formulation",
        severity: "critical",
        clueInStem: "not slept for three nights, was whispering that \"the baby is contaminated\"",
        whyItMatters: "Sleep deprivation and contamination delusion in the early postpartum period indicate possible postpartum psychosis.",
        relatedRisk: "Risk to mother and infant can escalate rapidly even without expressed intent.",
        modelWording: "No sleep for three nights plus belief the baby is contaminated should have triggered postpartum psychosis risk assessment, not simple anxiety.",
        keywords: ["postpartum psychosis", "not slept", "baby is contaminated", "delusion", "postnatal", "psychosis"],
      },
      {
        id: "s2",
        name: "Infant safety risk not dependent on stated intent",
        category: "risk_vulnerable",
        severity: "critical",
        clueInStem: "refused to let staff weigh the baby",
        whyItMatters: "Refusal of baby care in psychosis creates infant neglect/dehydration risk even if the mother denies intent to harm.",
        relatedRisk: "Baby later returned dehydrated, confirming foreseeable infant risk.",
        modelWording: "Refusal to allow weighing was an infant safety signal; denial of intent did not make discharge safe.",
        keywords: ["baby", "infant", "weigh", "dehydrated", "neglect", "risk to baby", "vulnerable"],
      },
      {
        id: "s3",
        name: "Collateral omitted from psychiatry note",
        category: "collateral",
        severity: "important",
        clueInStem: "These details do not appear in the psychiatry note",
        whyItMatters: "Family history of postpartum psychosis and stopping quetiapine were highly relevant risk factors that were not documented.",
        relatedSystem: "Documentation omission impaired formulation and safety planning.",
        modelWording: "The partner's collateral about family postpartum psychosis and stopping quetiapine should have been documented and used in formulation.",
        keywords: ["collateral", "partner", "sister", "postpartum psychosis", "quetiapine", "not documented"],
      },
      {
        id: "s4",
        name: "Unsafe delayed follow-up",
        category: "disposition",
        severity: "critical",
        clueInStem: "Community follow-up was booked for seven days later",
        whyItMatters: "Possible postpartum psychosis with infant risk requires urgent review or admission pathway, not routine follow-up in seven days.",
        relatedSystem: "Requires perinatal escalation pathway and out-of-hours consultant involvement.",
        modelWording: "Seven-day follow-up was unsafe given possible postpartum psychosis and active infant-care refusal.",
        keywords: ["seven days", "follow-up", "routine", "urgent", "admission", "perinatal escalation"],
      },
      {
        id: "s5",
        name: "Child protection not contacted despite infant risk",
        category: "child_protection",
        severity: "critical",
        clueInStem: "Child protection was not contacted",
        whyItMatters: "Infant safety concerns in the context of maternal psychosis require child safety planning and possible statutory consultation.",
        relatedLegal: "Mandatory reporting/consultation thresholds depend on jurisdiction, but risk must be assessed and documented.",
        modelWording: "Child protection consultation should have been considered because the baby was a vulnerable dependent at foreseeable risk.",
        keywords: ["child protection", "infant safety", "mandatory", "statutory", "baby", "safeguard"],
      },
      {
        id: "s6",
        name: "Over-reliance on denial of harm",
        category: "governance",
        severity: "important",
        clueInStem: "technically she denied wanting to hurt the baby",
        whyItMatters: "Denial of intent is not sufficient when behaviour and delusional content indicate risk to a vulnerable infant.",
        modelWording: "The midwifery manager's phrase shows anchoring on denial of intent instead of behavioural infant-risk formulation.",
        keywords: ["denied", "wanting to hurt", "denial", "intent", "anchoring", "behavioural risk"],
      },
    ],
    priorityOrder: {
      urgent: ["s1", "s2", "s4", "s5"],
      secondary: ["s3", "s6"],
      lowYield: [],
    },
    modelAnswer: `The review should identify a foreseeable perinatal safety failure. Alana had possible postpartum psychosis: no sleep for three nights, belief the baby was contaminated, refusal to allow weighing, family history of postpartum psychosis and medication cessation. Infant safety risk did not require her to state an intention to harm the baby.

I would ensure Alana and the baby are currently safe, notify perinatal psychiatry, paediatrics and child protection as appropriate, and conduct open disclosure with the partner. The incident review should examine out-of-hours psychiatric assessment, missing collateral, documentation quality, perinatal escalation thresholds, delayed follow-up and failure to create an infant safety plan. The learning point is that postpartum psychosis risk is behavioural and contextual, not dependent on a simple denial of harm.`,
  },
  {
    id: "QA-009",
    questionNumber: "MEQ-061",
    topic: "quality_assurance",
    difficulty: "consultant",
    title: "ECT Consent and Wrong-Site Governance Failure",
    candidateRole: "ECT clinical lead reviewing a procedural safety incident",
    setting: "Hospital ECT suite",
    stem: `You are the ECT clinical lead. During a morning list, Mei, a 46-year-old woman with severe psychotic depression, received bilateral ECT although the treating consultant's plan specified "right unilateral ECT due cognitive risk." The error was noticed only after the treatment when the recovery nurse read the progress note.

The ECT consent form states "ECT discussed; patient agreeable." It does not specify electrode placement, cognitive risks, alternatives, or interpreter use. Mei speaks conversational English but had asked for a Mandarin interpreter at admission because "medical words are hard." The ECT checklist was completed after the anaesthetic induction because the list was running late. The psychiatry registrar says the ECT nurse told him "bilateral is what we usually do here." Mei's husband is distressed and says no one explained the difference between unilateral and bilateral ECT.`,
    totalMarks: 25,
    signals: [
      {
        id: "s1",
        name: "Wrong ECT modality delivered",
        category: "governance",
        severity: "critical",
        clueInStem: "received bilateral ECT although the treating consultant's plan specified \"right unilateral ECT due cognitive risk\"",
        whyItMatters: "Delivering a different ECT modality than planned is a procedural safety incident with clinical implications.",
        relatedRisk: "Bilateral ECT may increase cognitive adverse effects, particularly where cognitive risk was already identified.",
        modelWording: "This is a wrong-procedure/wrong-modality ECT incident because bilateral ECT was given despite a right unilateral plan.",
        keywords: ["bilateral", "right unilateral", "ECT", "wrong modality", "procedure", "cognitive risk"],
      },
      {
        id: "s2",
        name: "Consent documentation inadequate",
        category: "consent_refusal",
        severity: "critical",
        clueInStem: "does not specify electrode placement, cognitive risks, alternatives, or interpreter use",
        whyItMatters: "ECT consent must document material risks, alternatives and the specific treatment plan; generic agreement is inadequate.",
        relatedLegal: "Poor consent documentation increases medico-legal risk and undermines patient autonomy.",
        modelWording: "The consent form is inadequate because it does not document electrode placement, cognitive risk, alternatives or interpreter use.",
        keywords: ["consent", "electrode placement", "cognitive risks", "alternatives", "interpreter", "generic"],
      },
      {
        id: "s3",
        name: "Interpreter request ignored for consent",
        category: "cultural_safety",
        severity: "important",
        clueInStem: "had asked for a Mandarin interpreter at admission because \"medical words are hard\"",
        whyItMatters: "Conversational English is not enough for complex consent when the patient requested interpreter support.",
        relatedCultural: "Language access is necessary for valid, culturally safe consent.",
        modelWording: "Mei's request for a Mandarin interpreter should have been honoured for ECT consent discussions.",
        keywords: ["Mandarin", "interpreter", "medical words are hard", "language", "consent", "cultural safety"],
      },
      {
        id: "s4",
        name: "Checklist completed after induction",
        category: "immediate_safety",
        severity: "critical",
        clueInStem: "ECT checklist was completed after the anaesthetic induction",
        whyItMatters: "A safety checklist completed after induction cannot prevent wrong-procedure errors.",
        relatedSystem: "Requires procedural timeout before anaesthesia.",
        modelWording: "Completing the ECT checklist after induction defeats its safety purpose and contributed to the error.",
        keywords: ["checklist", "after induction", "anaesthetic", "timeout", "running late", "safety check"],
      },
      {
        id: "s5",
        name: "Informal local practice overrode individual plan",
        category: "mdt_conflict",
        severity: "important",
        clueInStem: "bilateral is what we usually do here",
        whyItMatters: "Local custom cannot override the documented consultant treatment plan and consent.",
        relatedSystem: "Requires role clarity in ECT suite and pre-procedure verification.",
        modelWording: "The nurse's statement that bilateral is usual practice shows unsafe reliance on routine instead of patient-specific plan verification.",
        keywords: ["usually do here", "routine", "local practice", "treatment plan", "verification", "ECT nurse"],
      },
      {
        id: "s6",
        name: "Need for open disclosure to Mei and husband",
        category: "family_carer",
        severity: "important",
        clueInStem: "husband is distressed and says no one explained the difference",
        whyItMatters: "The family has identified a consent and communication failure requiring open disclosure and clear explanation.",
        modelWording: "Mei and her husband require prompt open disclosure about the wrong ECT modality and potential cognitive implications.",
        keywords: ["husband", "distressed", "open disclosure", "explained", "difference", "communication"],
      },
    ],
    priorityOrder: {
      urgent: ["s1", "s2", "s4"],
      secondary: ["s3", "s5", "s6"],
      lowYield: [],
    },
    modelAnswer: `This is a serious ECT procedural safety and consent incident. Bilateral ECT was delivered despite a documented plan for right unilateral ECT due cognitive risk. The checklist was completed after anaesthetic induction, so it could not function as a safety barrier. The consent documentation was inadequate because it did not specify electrode placement, cognitive risks, alternatives or interpreter use.

I would ensure Mei's immediate recovery and cognitive monitoring, notify the treating consultant and hospital governance, complete incident reporting and conduct open disclosure with Mei and her husband. The review should examine ECT consent standards, interpreter access, pre-procedure timeout, role clarity, checklist timing, and the unsafe culture implied by "bilateral is what we usually do here."`,
  },
  {
    id: "QA-010",
    questionNumber: "MEQ-062",
    topic: "quality_assurance",
    difficulty: "consultant",
    title: "Registrar Working Beyond Competence After Hours",
    candidateRole: "Director of training and consultant psychiatrist reviewing a supervision incident",
    setting: "Regional mental health service after-hours roster",
    stem: `You are the director of training and a consultant psychiatrist in a regional mental health service. A Stage 1 registrar, working their second weekend on call, assessed three high-risk ED patients overnight while also covering the inpatient unit by phone. At 4 am the registrar discharged Talia, a 19-year-old woman brought in after ligature self-harm in a police cell.

The registrar documented "emotionally unstable personality traits; no admission benefit." There was no psychosocial formulation, no contact with Talia's mother, no police collateral, and no safety plan. Talia returned six hours later after another ligature attempt in the ED bathroom. The registrar is now tearful and says, "I thought calling the consultant at 4 am would show I couldn't cope."

The roster shows the consultant was covering three hospitals and had told registrars by email, "Use your judgement overnight unless absolutely necessary." The ED director says psychiatry trainees are being left to manage unacceptable risk.`,
    totalMarks: 25,
    signals: [
      {
        id: "s1",
        name: "High-risk discharge after ligature self-harm",
        category: "risk_self",
        severity: "critical",
        clueInStem: "discharged Talia, a 19-year-old woman brought in after ligature self-harm in a police cell",
        whyItMatters: "Ligature self-harm in custody is a high-risk presentation requiring careful formulation and safety planning.",
        relatedRisk: "Repeat ligature attempt occurred within six hours.",
        modelWording: "Ligature self-harm in a police cell is a high-risk contextual presentation, not a low-benefit admission question alone.",
        keywords: ["ligature", "police cell", "self-harm", "high-risk", "custody", "repeat attempt"],
      },
      {
        id: "s2",
        name: "Stigmatising diagnostic shortcut",
        category: "diagnosis_formulation",
        severity: "important",
        clueInStem: "emotionally unstable personality traits; no admission benefit",
        whyItMatters: "This wording suggests diagnostic shortcutting and therapeutic nihilism rather than formulation of acute risk.",
        relatedSystem: "Training and supervision should address stigma and formulation quality.",
        modelWording: "The phrase 'emotionally unstable personality traits; no admission benefit' is not a formulation and risks minimising acute danger.",
        keywords: ["emotionally unstable", "personality traits", "no admission benefit", "stigma", "formulation", "therapeutic nihilism"],
      },
      {
        id: "s3",
        name: "Missing collateral and safety plan",
        category: "collateral",
        severity: "critical",
        clueInStem: "no contact with Talia's mother, no police collateral, and no safety plan",
        whyItMatters: "Discharge after custodial ligature self-harm without collateral or safety plan is unsafe.",
        relatedRisk: "Key information about triggers, means, custody context and supports was absent.",
        modelWording: "The absence of mother contact, police collateral and safety plan makes the discharge process unsafe.",
        keywords: ["mother", "police collateral", "safety plan", "collateral", "no contact", "discharge"],
      },
      {
        id: "s4",
        name: "Registrar felt unable to call consultant",
        category: "governance",
        severity: "critical",
        clueInStem: "calling the consultant at 4 am would show I couldn't cope",
        whyItMatters: "A trainee who fears escalation is a supervision and patient-safety risk.",
        relatedSystem: "Requires culture of escalation, not shame-based independence.",
        modelWording: "The registrar's fear that calling would show inability to cope indicates a supervision culture failure.",
        keywords: ["couldn't cope", "calling consultant", "4 am", "escalation", "supervision", "trainee"],
      },
      {
        id: "s5",
        name: "Unsafe consultant cover across three hospitals",
        category: "system_pressure",
        severity: "important",
        clueInStem: "consultant was covering three hospitals",
        whyItMatters: "The consultant workload may have created unsafe barriers to direct supervision.",
        relatedSystem: "Requires roster review and escalation to service leadership.",
        modelWording: "Consultant cover across three hospitals is a system contributor to inadequate after-hours supervision.",
        keywords: ["three hospitals", "consultant covering", "roster", "after-hours", "workload", "service pressure"],
      },
      {
        id: "s6",
        name: "Email discouraged escalation",
        category: "governance",
        severity: "important",
        clueInStem: "Use your judgement overnight unless absolutely necessary",
        whyItMatters: "This wording may discourage junior trainees from calling in high-risk situations.",
        relatedSystem: "Supervision policy should define mandatory escalation triggers.",
        modelWording: "The email 'unless absolutely necessary' created an unsafe ambiguity for a Stage 1 registrar.",
        keywords: ["use your judgement", "absolutely necessary", "email", "mandatory escalation", "ambiguity", "Stage 1"],
      },
    ],
    priorityOrder: {
      urgent: ["s1", "s3", "s4"],
      secondary: ["s2", "s5", "s6"],
      lowYield: [],
    },
    modelAnswer: `This incident should be reviewed as both a clinical safety event and a supervision governance failure. Talia's ligature self-harm in a police cell was high risk; discharge without psychosocial formulation, mother contact, police collateral or safety plan was unsafe. The label "emotionally unstable personality traits; no admission benefit" suggests diagnostic shortcutting rather than acute risk formulation.

The registrar's distress and belief that calling at 4 am would show they could not cope is a central safety signal. I would support the registrar while addressing accountability, ensure Talia's current safety, report the incident, and review after-hours supervision. The consultant covering three hospitals and the email advising registrars to use judgement unless "absolutely necessary" require roster and escalation-policy review, including mandatory consultant contact triggers for high-risk discharge.`,
  },
  {
    id: "SYS-002",
    questionNumber: "MEQ-063",
    topic: "quality_assurance",
    difficulty: "consultant",
    title: "Repeated bipolar admissions and carer burnout",
    candidateRole: "Consultant psychiatrist, community continuing care team",
    setting: "Regional community mental health service",
    stem: `You are the consultant psychiatrist in a regional community continuing care team.

Maria is a 48-year-old woman with bipolar I disorder and seven admissions in the past four years, mostly following medication cessation during hypomanic periods. Her husband reports she becomes "brilliant for a few weeks" before stopping lithium because she believes she no longer needs treatment. During recent episodes she has accumulated large debts and driven long distances without sleep.

Maria was discharged from the inpatient unit three weeks ago after a manic relapse. At today's review she says, "Lithium takes away who I am." She admits reducing the dose herself because she wants "more energy to start a business." Her husband becomes visibly distressed and says, "I can't keep doing this every year." He reports hiding car keys and monitoring Maria's medications because he fears another relapse.

The case manager believes Maria requires intensive monitoring, while Maria says the team is "treating me like a child." The registrar asks whether ongoing assertive follow-up is justified when Maria is not currently psychotic and technically attends appointments voluntarily.`,
    totalMarks: 22,
    signals: [
      {
        id: "s1",
        name: "Identity-based ambivalence about lithium",
        category: "diagnosis_formulation",
        severity: "critical",
        clueInStem: "Lithium takes away who I am.",
        whyItMatters: "Identity-related ambivalence is a major driver of relapse and requires nuanced formulation beyond simple non-compliance.",
        modelWording: "Explore ambivalence regarding mood stabilisation including perceived loss of identity, creativity and autonomy — this is not simple non-compliance, it is a formulation target.",
        keywords: ["ambivalence", "lithium adherence", "identity", "bipolar disorder", "partial insight"],
      },
      {
        id: "s2",
        name: "High historical risk justifies assertive follow-up",
        category: "risk_self",
        severity: "critical",
        clueInStem: "driven long distances without sleep.",
        whyItMatters: "Repeated severe behavioural consequences — dangerous driving, financial harm, repeated admissions — justify proactive relapse prevention even when currently euthymic.",
        modelWording: "Recognise that seven admissions with dangerous driving and financial harm justify assertive follow-up regardless of current stability — this is not paternalism, it is proportionate risk management.",
        keywords: ["relapse prevention", "mania", "behavioural risk", "historical risk", "dangerous driving", "assertive"],
      },
      {
        id: "s3",
        name: "Carer over-functioning and burnout",
        category: "family_carer",
        severity: "important",
        clueInStem: "hiding car keys and monitoring Maria's medications",
        whyItMatters: "A husband hiding car keys and monitoring medications daily is over-functioning unsustainably — this will break down and must be addressed as a clinical issue.",
        modelWording: "Assess caregiver burden and reduce reliance on the husband as the sole relapse monitoring system — this is unsustainable and relationship-damaging.",
        keywords: ["carer burnout", "over-functioning", "relapse monitoring", "family strain", "husband"],
      },
      {
        id: "s4",
        name: "Autonomy versus assertive follow-up tension",
        category: "ethics",
        severity: "important",
        clueInStem: "treating me like a child.",
        whyItMatters: "Maria's experience of care as paternalistic is clinically significant and must be addressed through collaborative, autonomy-respecting care planning.",
        modelWording: "Balance assertive relapse prevention with collaborative care — explain rationale for close follow-up based on specific historical consequences, not general concern.",
        keywords: ["autonomy", "assertive follow-up", "paternalism", "collaborative care", "shared decision-making"],
      },
      {
        id: "s5",
        name: "Predictable relapse signature — opportunity for advance planning",
        category: "governance",
        severity: "important",
        clueInStem: "becomes brilliant for a few weeks",
        whyItMatters: "A consistent early warning sign — feeling brilliant, stopping lithium — creates a specific opportunity for an advance directive and agreed early intervention plan.",
        modelWording: "Identify Maria's relapse signature and develop an advance directive with agreed interventions when she reports feeling brilliant — this converts a predictable pattern into a prevention opportunity.",
        keywords: ["early warning signs", "relapse signature", "advance directive", "mania prevention", "advance planning"],
      },
      {
        id: "s6",
        name: "Longitudinal care model needed",
        category: "system_pressure",
        severity: "optional",
        clueInStem: "seven admissions in the past four years",
        whyItMatters: "Seven admissions in four years suggests episodic crisis care rather than structured longitudinal management.",
        modelWording: "Review whether current service structure addresses Maria's recurrent pattern — a structured longitudinal care model with named case manager and rapid review pathway is indicated.",
        keywords: ["continuity of care", "repeated admissions", "longitudinal care", "service planning", "case management"],
      },
    ],
    priorityOrder: {
      urgent: ["s1", "s2"],
      secondary: ["s3", "s4", "s5"],
      lowYield: ["s6"],
    },
    modelAnswer: `Review Maria using a longitudinal bipolar formulation. Seven admissions in four years is not a coincidence — it is a pattern driven by identity-based ambivalence about lithium that requires direct formulation, not just psychoeducation.

Assess current mood, insight, adherence, sleep, and psychosocial stressors. Explore the specific meaning of lithium for Maria — fear of emotional blunting, loss of creativity, loss of the "brilliant" self. This is the treatment target.

Recognise high historical risk despite current stability: dangerous driving, financial harm, repeated admissions justify assertive follow-up. Explain this rationale to Maria directly — not as paternalism but as proportionate response to specific consequences.

Develop an advance directive with Maria: what are her early warning signs, what has she agreed can happen when she reports feeling brilliant, who contacts the team.

Address carer burden: the husband hiding car keys daily is unsustainable. Reduce his sole responsibility through a structured team relapse response plan.

Review medication tolerability — explore whether side effect concerns are driving dose reduction, and whether adjuncts or alternatives address her identity concerns.

Supervise registrar: assertive follow-up for a patient with seven admissions and dangerous historical behaviour is clinically justified regardless of current voluntary attendance.`,
  },
  {
    id: "SYS-003",
    questionNumber: "MEQ-064",
    topic: "old_age",
    difficulty: "consultant",
    title: "Dementia, driving and enduring power of attorney conflict",
    candidateRole: "Consultant psychiatrist, old age psychiatry consultation service",
    setting: "Residential aged care facility",
    stem: `You are the consultant psychiatrist providing outreach to a residential aged care facility.

George is an 82-year-old retired accountant with vascular dementia who moved into residential care six months ago after several episodes of getting lost while driving. Staff report increasing irritability, accusations that belongings are being stolen, and repeated attempts to leave the facility to "go check the office." George insists he is capable of driving and says, "My son just wants control of my money."

George's son holds enduring power of attorney for finances and health matters. He asks you to formally document that George lacks capacity so the family can sell his car and former home. George's daughter disagrees and says, "Dad still knows exactly what he wants — you're all trying to strip away his independence." Facility staff report escalating conflict between siblings during visits.

Last week George attempted to enter another resident's vehicle in the car park. The GP has already notified the licensing authority regarding driving concerns. The registrar asks whether your role is primarily to assess cognition, mediate the family dispute, or support the facility's risk management concerns.`,
    totalMarks: 22,
    signals: [
      {
        id: "s1",
        name: "Decision-specific capacity — not global incapacity",
        category: "capacity",
        severity: "critical",
        clueInStem: "Dad still knows exactly what he wants",
        whyItMatters: "Dementia does not automatically mean global incapacity — capacity must be assessed for each specific decision including driving, finances, and accommodation separately.",
        modelWording: "Conduct decision-specific capacity assessments for driving, finances, accommodation and health decisions separately — dementia diagnosis alone does not equal global incapacity.",
        keywords: ["decision-specific", "capacity", "vascular dementia", "not global", "driving capacity", "specific decision"],
      },
      {
        id: "s2",
        name: "Public safety — driving risk is immediate",
        category: "immediate_safety",
        severity: "critical",
        clueInStem: "attempted to enter another resident's vehicle",
        whyItMatters: "Attempting to enter another person's vehicle demonstrates active driving-related risk that is immediate and public — this cannot wait for family resolution.",
        modelWording: "George's attempt to enter another resident's vehicle is an immediate public safety issue requiring urgent action independent of the family dispute — I will support the GP's licensing notification and recommend means restriction.",
        keywords: ["driving risk", "public safety", "vehicle", "licensing authority", "immediate", "means restriction"],
      },
      {
        id: "s3",
        name: "EPOA conflict of interest — assessment must remain neutral",
        category: "governance",
        severity: "important",
        clueInStem: "sell his car and former home.",
        whyItMatters: "A son holding EPOA and asking for a capacity documentation to enable asset sale creates a potential conflict of interest — the assessment must be clinically neutral and not serve family financial interests.",
        modelWording: "I will conduct a neutral capacity assessment based on clinical evidence only — I will not allow the son's request to sell assets to frame my findings, and I will document my independence explicitly.",
        keywords: ["EPOA", "conflict of interest", "neutral", "financial", "asset sale", "independent", "documentation"],
      },
      {
        id: "s4",
        name: "Family conflict worsening BPSD",
        category: "family_carer",
        severity: "important",
        clueInStem: "escalating conflict between siblings during visits",
        whyItMatters: "Escalating sibling conflict during visits is a direct trigger for George's behavioural disturbance — addressing the family system is part of treating the BPSD.",
        modelWording: "Address sibling conflict as a clinical issue — it is directly contributing to George's distress and behavioural symptoms, and requires structured family communication with consistent information from the team.",
        keywords: ["family conflict", "siblings", "BPSD", "distress", "behavioural symptoms", "family meeting"],
      },
      {
        id: "s5",
        name: "BPSD — paranoia and exit-seeking require assessment and management",
        category: "diagnosis_formulation",
        severity: "important",
        clueInStem: "accusations that belongings are being stolen",
        whyItMatters: "Paranoid ideation and exit-seeking in vascular dementia are BPSD symptoms requiring non-pharmacological management first — they are not simply character traits.",
        modelWording: "Assess BPSD including paranoid ideation, exit-seeking and irritability — implement non-pharmacological strategies first and reserve antipsychotics for severe distress after risk-benefit discussion.",
        keywords: ["BPSD", "paranoia", "exit-seeking", "non-pharmacological", "vascular dementia", "behavioural management"],
      },
      {
        id: "s6",
        name: "Integrated consultant role — not just cognitive testing",
        category: "system_pressure",
        severity: "optional",
        clueInStem: "whether your role is primarily to assess cognition",
        whyItMatters: "The consultant old age psychiatrist integrates cognition, risk, systems, family, and legal frameworks — not just administers cognitive tests.",
        modelWording: "My role is integrated assessment of cognition, risk, functional capacity, BPSD, family systems and legal/EPOA issues — not cognitive testing in isolation.",
        keywords: ["integrated", "consultant role", "not just cognition", "risk", "family", "legal", "systems"],
      },
    ],
    priorityOrder: {
      urgent: ["s1", "s2"],
      secondary: ["s3", "s4", "s5"],
      lowYield: ["s6"],
    },
    modelAnswer: `Immediate priority: George's attempt to enter another resident's vehicle is a public safety issue requiring action now — I will support the GP's licensing notification and recommend means restriction independent of the family dispute.

Capacity assessment: I will conduct decision-specific assessments for driving, finances, accommodation and health decisions separately. Dementia does not mean global incapacity. I will assess each domain with clinical evidence and document my findings independently of the son's financial request.

EPOA neutrality: The son's request to document incapacity to enable asset sales creates a potential conflict of interest. My assessment is clinical, not financial. I will document this explicitly.

BPSD: Paranoid ideation about stolen belongings and exit-seeking are BPSD symptoms driving distress and conflict — I will recommend non-pharmacological management first and involve RACF staff in consistent behavioural strategies.

Family conflict: Escalating sibling conflict is a clinical issue — it is worsening George's distress. I will hold a structured family meeting with consistent information and clear role boundaries.

My role is integrated: cognition, risk, BPSD, family, legal and systems — not cognitive testing in isolation.`,
  },
];
