import type { QuizStem } from "../quizData";

export const SU_STEMS: QuizStem[] = [
  {
    id: "SU-001",
    questionNumber: "MEQ-073",
    topic: "substance_use",
    difficulty: "consultant",
    title: "Alcohol Dependence with Decompensated Liver Disease",
    candidateRole: "Consultant psychiatrist, consultation-liaison addiction psychiatry",
    setting: "Hepatology ward in tertiary hospital",
    stem: `You are the consultant psychiatrist asked to review Peter, a 57-year-old man with severe alcohol dependence and decompensated cirrhosis admitted with ascites, encephalopathy and variceal bleeding.

Peter is refusing lactulose, blood tests and alcohol withdrawal medication. He says, "I know I'm dying, so let me drink and leave me alone." His wife says, "He says this every time, but when he sobers up he wants treatment." The hepatology team says he is intermittently confused and may deteriorate without treatment.

Peter asks to self-discharge to attend his local pub. His adult daughter says the family cannot keep rescuing him and asks whether the team can "force rehab this time." The medical registrar asks whether Peter has capacity to refuse treatment.`,
    totalMarks: 22,
    signals: [
      { id: "s1", name: "Fluctuating confusion makes refusal capacity uncertain", category: "capacity", severity: "critical", clueInStem: "The hepatology team says he is intermittently confused and may deteriorate without treatment.", whyItMatters: "Missing this signal means the candidate has accepted refusal despite possible fluctuating capacity from encephalopathy, intoxication or withdrawal.", modelWording: "Assess decision-specific and fluctuating capacity because intermittent confusion may invalidate refusal of urgent liver and withdrawal treatment.", keywords: ["capacity", "hepatic encephalopathy", "fluctuating cognition", "alcohol withdrawal", "intoxication", "refusal"] },
      { id: "s2", name: "Decompensated cirrhosis creates life-threatening medical risk", category: "physical_health", severity: "critical", clueInStem: "You are the consultant psychiatrist asked to review Peter, a 57-year-old man with severe alcohol dependence and decompensated cirrhosis admitted with ascites, encephalopathy and variceal bleeding.", whyItMatters: "Missing this signal means the candidate has treated the issue as addiction refusal while overlooking immediately serious liver disease.", modelWording: "Clarify immediate medical risk from variceal bleeding, ascites, encephalopathy and withdrawal before deciding whether treatment can be refused.", keywords: ["cirrhosis", "variceal bleeding", "ascites", "encephalopathy", "medical deterioration", "urgent treatment"] },
      { id: "s3", name: "Hopeless drinking statement needs assessment for demoralisation", category: "diagnosis_formulation", severity: "important", clueInStem: "He says, \"I know I'm dying, so let me drink and leave me alone.\"", whyItMatters: "Missing this signal means the candidate has accepted a possibly state-dependent hopeless statement as a settled end-of-life decision.", modelWording: "Assess depression, demoralisation, delirium and suicidality because wanting to drink and be left alone may not be a stable capacitous value.", keywords: ["demoralisation", "depression", "hopelessness", "treatment refusal", "end-stage liver disease"] },
      { id: "s4", name: "Wife's collateral suggests refusal is state-dependent", category: "collateral", severity: "important", clueInStem: "His wife says, \"He says this every time, but when he sobers up he wants treatment.\"", whyItMatters: "Missing this signal means the candidate has ignored collateral that the current refusal may reverse when Peter is sober or less encephalopathic.", modelWording: "Use the wife's collateral to test whether Peter's refusal is stable or state-dependent on intoxication, withdrawal or encephalopathy.", keywords: ["collateral", "state-dependent refusal", "wife", "sobriety", "stable preference", "capacity"] },
      { id: "s5", name: "Family request for forced rehabilitation needs legal clarification", category: "family_carer", severity: "important", clueInStem: "His adult daughter says the family cannot keep rescuing him and asks whether the team can \"force rehab this time.\"", whyItMatters: "Missing this signal means the candidate has blurred emergency medical treatment with coercive rehabilitation in response to family exhaustion.", modelWording: "Explain that emergency medical treatment and involuntary rehabilitation have different legal thresholds and aims.", keywords: ["family expectations", "forced rehab", "legal threshold", "addiction treatment", "psychoeducation"] },
      { id: "s6", name: "Self-discharge to the pub creates immediate relapse and safety risk", category: "substance_use", severity: "important", clueInStem: "Peter asks to self-discharge to attend his local pub.", whyItMatters: "Missing this signal means the candidate has not addressed foreseeable alcohol exposure, withdrawal disruption and medical deterioration if he leaves.", modelWording: "Plan harm reduction and relapse prevention because self-discharge to the pub would expose Peter to immediate alcohol-related deterioration.", keywords: ["harm reduction", "relapse prevention", "addiction medicine", "alcohol dependence", "withdrawal", "self-discharge"] },
      { id: "s7", name: "Each refused intervention needs separate capacity reasoning", category: "consent_refusal", severity: "important", clueInStem: "Peter is refusing lactulose, blood tests and alcohol withdrawal medication.", whyItMatters: "Missing this signal means the candidate has treated capacity as global rather than assessing each refused intervention and its consequences.", modelWording: "Assess capacity separately for lactulose, blood tests and withdrawal medication because each refusal carries different risks and legal options.", keywords: ["lactulose", "blood tests", "withdrawal medication", "decision-specific", "capacity", "refusal"] },
    ],
    priorityOrder: { urgent: ["s1", "s2"], secondary: ["s3", "s4", "s5", "s6", "s7"], lowYield: [] },
    modelAnswer: `Peter's refusal cannot be treated as a stable autonomous end-of-life decision without first addressing the acute medical and cognitive context. He has severe alcohol dependence and decompensated cirrhosis with ascites, encephalopathy and variceal bleeding. The hepatology team also says he is intermittently confused and may deteriorate without treatment, so capacity may fluctuate because of hepatic encephalopathy, intoxication or withdrawal.

The capacity question must be decision-specific. Peter is refusing lactulose, blood tests and alcohol withdrawal medication, and each refusal has different consequences. I would assess whether he can understand, retain, appreciate and weigh the risks of worsening encephalopathy, bleeding, withdrawal, dehydration and self-discharge, and I would reassess when medically optimised if delay is safe.

His statement, "I know I'm dying, so let me drink and leave me alone," needs careful interpretation. It may be a values-based refusal in a person with advanced illness, but it may also reflect depression, demoralisation, delirium, intoxication or a suicidal wish to deteriorate. I would assess mood, hopelessness, suicidality, cognition and whether the decision is consistent with his settled values.

The wife's collateral is critical because she says, "He says this every time, but when he sobers up he wants treatment." That suggests the refusal may be state-dependent rather than enduring. Her view does not override Peter, but it strongly informs whether his current refusal is authentic and capacitous.

The daughter's request to "force rehab this time" needs a clear explanation. Emergency medical treatment for life-threatening deterioration, treatment of withdrawal and compulsory rehabilitation are different legal and ethical issues. Family exhaustion is understandable, but it does not create authority to force long-term rehabilitation. If Peter lacks capacity and faces imminent serious harm, emergency or substitute decision pathways may justify treatment; if he has capacity, harmful refusal may need to be respected.

If Peter wants to self-discharge to attend his local pub, I would address immediate safety and harm reduction. That includes withdrawal management, addiction medicine input, relapse planning, family support, realistic follow-up and documentation of why the final plan is the least restrictive lawful option.`,
  },
  {
    id: "SU-002",
    questionNumber: "MEQ-074",
    topic: "substance_use",
    difficulty: "consultant",
    title: "Methamphetamine Psychosis versus Primary Psychosis",
    candidateRole: "Consultant psychiatrist, emergency psychiatry service",
    setting: "Metropolitan emergency department short-stay unit",
    stem: `You are the consultant psychiatrist supervising assessment of Kai, a 25-year-old man brought to ED by ambulance after barricading himself in his room.

Kai says, "The neighbours have installed cameras in the smoke alarm." Urine drug screen is positive for methamphetamine and cannabis. His father reports Kai has been increasingly withdrawn for six months, stopped working and has been muttering to himself even during periods when the family believe he was not using drugs.

Kai has not slept for four nights and punched a hole in the wall before ambulance arrived. He says, "If they come in again, I'll be ready." The ED registrar asks whether he can be discharged once he sleeps because this is probably just methamphetamine intoxication.`,
    totalMarks: 22,
    signals: [
      { id: "s1", name: "Six-month decline suggests possible primary psychosis", category: "diagnosis_formulation", severity: "critical", clueInStem: "His father reports Kai has been increasingly withdrawn for six months, stopped working and has been muttering to himself even during periods when the family believe he was not using drugs.", whyItMatters: "Missing this signal means the candidate has accepted a drug-only explanation despite longitudinal deterioration outside apparent intoxication.", modelWording: "Formulate methamphetamine-induced psychosis versus emerging primary psychosis using the six-month functional decline and collateral about abstinent periods.", keywords: ["methamphetamine psychosis", "primary psychosis", "six-month decline", "collateral", "functional deterioration", "differential diagnosis"] },
      { id: "s2", name: "Persecutory belief is directed at identifiable neighbours", category: "risk_others", severity: "critical", clueInStem: "Kai says, \"The neighbours have installed cameras in the smoke alarm.\"", whyItMatters: "Missing this signal means the candidate has not recognised that the psychotic belief identifies possible targets of defensive violence.", modelWording: "Assess risk to the neighbours specifically because Kai's persecutory belief names them as the source of threat.", keywords: ["persecutory beliefs", "neighbours", "specific target", "violence risk", "threat perception"] },
      { id: "s3", name: "Threat readiness indicates psychosis-linked violence risk", category: "risk_others", severity: "critical", clueInStem: "He says, \"If they come in again, I'll be ready.\"", whyItMatters: "Missing this signal means the candidate has accepted no stated intent while overlooking defensive preparedness in response to delusional threat.", modelWording: "Assess violence risk driven by persecutory beliefs because Kai is preparing to respond if he thinks people enter again.", keywords: ["violence risk", "persecutory beliefs", "threat perception", "property damage", "sleep deprivation", "stimulant use"] },
      { id: "s4", name: "Methamphetamine and cannabis use are important but not diagnostic closure", category: "substance_use", severity: "important", clueInStem: "Urine drug screen is positive for methamphetamine and cannabis.", whyItMatters: "Missing this signal means the candidate has either ignored substances or used the positive screen to prematurely close the diagnosis.", modelWording: "Assess methamphetamine and cannabis use as precipitants and risk amplifiers while avoiding premature diagnostic closure.", keywords: ["methamphetamine", "cannabis", "urine drug screen", "substance-induced", "psychosis", "risk"] },
      { id: "s5", name: "Sleep deprivation and wall-punching show behavioural escalation", category: "immediate_safety", severity: "important", clueInStem: "Kai has not slept for four nights and punched a hole in the wall before ambulance arrived.", whyItMatters: "Missing this signal means the candidate has not recognised acute behavioural dysregulation and worsening risk before ED arrival.", modelWording: "Treat sleep deprivation and wall-punching as dynamic escalation because they worsen psychosis, agitation and risk to others.", keywords: ["sleep deprivation", "agitation", "psychosis", "dynamic risk", "property damage", "behavioural disturbance"] },
      { id: "s6", name: "Barricading indicates severe fear and containment risk", category: "immediate_safety", severity: "important", clueInStem: "You are the consultant psychiatrist supervising assessment of Kai, a 25-year-old man brought to ED by ambulance after barricading himself in his room.", whyItMatters: "Missing this signal means the candidate has underestimated the severity of disorganisation and fear that required ambulance attendance.", modelWording: "Use the barricading behaviour to justify safe containment and careful assessment because it shows severe fear and behavioural disturbance.", keywords: ["barricading", "ambulance", "containment", "fear", "behavioural disturbance", "ED"] },
      { id: "s7", name: "Sleep alone is not a safe discharge threshold", category: "disposition", severity: "important", clueInStem: "The ED registrar asks whether he can be discharged once he sleeps because this is probably just methamphetamine intoxication.", whyItMatters: "Missing this signal means the candidate has accepted sedation or sleep as resolution of diagnostic uncertainty and violence risk.", modelWording: "Do not discharge solely after sleep because disposition depends on persistent psychosis, violence risk, supports and follow-up.", keywords: ["premature discharge", "short-stay", "risk reassessment", "supports", "follow-up", "ED"] },
    ],
    priorityOrder: { urgent: ["s1", "s2", "s3"], secondary: ["s4", "s5", "s6", "s7"], lowYield: [] },
    modelAnswer: `Kai should not be discharged simply because he sleeps and appears calmer. His father's collateral describes six months of withdrawal, stopping work and muttering to himself even during periods when the family believe he was not using drugs. That history requires formulation of methamphetamine-induced psychosis versus emerging primary psychosis rather than diagnostic closure on intoxication.

The violence risk is threat-based and specific. Kai believes the neighbours have installed cameras in his smoke alarm, and says, "If they come in again, I'll be ready." That means the neighbours may be perceived targets, and his risk may arise from defensive action against a delusional threat rather than declared malice.

His acute presentation also shows behavioural escalation. He was brought by ambulance after barricading himself in his room, had not slept for four nights, and punched a hole in the wall. These features justify safe containment, low-stimulus assessment, removal of potential weapons and collateral from family and ambulance or police if available.

The positive urine drug screen for methamphetamine and cannabis is important. These substances can precipitate, worsen or mimic psychosis, disrupt sleep and increase impulsivity. I would assess timing, amount, route, withdrawal, previous episodes, periods of abstinence and whether psychosis persists after observation.

The disposition decision should depend on persisting psychosis, violence risk, sleep, family capacity and follow-up, not on one period of sleep. If persecutory beliefs or threat readiness persist, admission or intensive crisis containment is required, using involuntary assessment if criteria are met. Discharge would require family agreement, means restriction, early psychosis follow-up, substance-use intervention and clear return criteria.`,
  },
  {
    id: "SU-003",
    questionNumber: "MEQ-075",
    topic: "substance_use",
    difficulty: "consultant",
    title: "Pregnancy, Methadone and Neonatal Planning",
    candidateRole: "Consultant psychiatrist, perinatal addiction psychiatry liaison",
    setting: "Public antenatal clinic and opioid treatment service",
    stem: `You are the consultant psychiatrist asked to review Alana, a 29-year-old woman who is 30 weeks pregnant and on methadone maintenance treatment.

Alana says, "If child protection hears I'm on methadone, they'll take my baby." She has missed two antenatal appointments but attends the dosing clinic regularly. Urine drug screens show intermittent benzodiazepine and cannabis use. Her partner is also using heroin and has recently become verbally aggressive at clinic.

The midwife wants a neonatal abstinence syndrome plan, but Alana says, "I don't want the baby labelled an addict." She becomes tearful and says methadone is the only thing stopping her from using heroin. The registrar asks whether methadone should be reduced before delivery to reduce foetal risk.`,
    totalMarks: 22,
    signals: [
      { id: "s1", name: "Methadone maintenance is protective in pregnancy", category: "substance_use", severity: "critical", clueInStem: "You are the consultant psychiatrist asked to review Alana, a 29-year-old woman who is 30 weeks pregnant and on methadone maintenance treatment.", whyItMatters: "Missing this signal means the candidate has treated methadone as the problem rather than protective stabilising treatment in pregnancy.", modelWording: "Maintain opioid substitution treatment as protective because stable methadone reduces heroin relapse and maternal-foetal instability.", keywords: ["methadone", "opioid substitution treatment", "pregnancy", "heroin relapse", "stabilisation", "harm reduction"] },
      { id: "s2", name: "Fear of child protection may undermine engagement", category: "child_protection", severity: "critical", clueInStem: "Alana says, \"If child protection hears I'm on methadone, they'll take my baby.\"", whyItMatters: "Missing this signal means the candidate has not addressed a fear that could drive antenatal disengagement and concealed substance use.", modelWording: "Address child protection fears transparently because engagement and safety planning are more protective than concealment.", keywords: ["child protection", "fear of removal", "engagement", "pregnancy", "transparency", "safety planning"] },
      { id: "s3", name: "Regular dosing attendance is an engagement strength", category: "collateral", severity: "important", clueInStem: "She has missed two antenatal appointments but attends the dosing clinic regularly.", whyItMatters: "Missing this signal means the candidate has framed Alana as non-compliant rather than using her reliable dosing attendance to rebuild antenatal care.", modelWording: "Use regular dosing attendance as a strength because care can be coordinated around the service Alana already trusts.", keywords: ["dosing clinic", "antenatal care", "engagement", "strength", "missed appointments", "outreach"] },
      { id: "s4", name: "Polysubstance use increases maternal and neonatal risk", category: "substance_use", severity: "important", clueInStem: "Urine drug screens show intermittent benzodiazepine and cannabis use.", whyItMatters: "Missing this signal means the candidate has not assessed sedation, overdose and neonatal risk from substances used alongside methadone.", modelWording: "Assess benzodiazepine and cannabis use because polysubstance exposure increases overdose, sedation and neonatal risk.", keywords: ["benzodiazepines", "cannabis", "polysubstance use", "overdose risk", "neonatal risk", "pregnancy"] },
      { id: "s5", name: "Partner heroin use and aggression affect safety", category: "risk_vulnerable", severity: "important", clueInStem: "Her partner is also using heroin and has recently become verbally aggressive at clinic.", whyItMatters: "Missing this signal means the candidate has not considered family violence, coercion, clinic safety and postnatal infant risk.", modelWording: "Assess family violence and partner substance use as risks to Alana, the foetus, staff and postnatal safety.", keywords: ["family violence", "partner substance use", "heroin", "maternal safety", "infant safety", "clinic aggression"] },
      { id: "s6", name: "NAS planning must be non-stigmatising", category: "physical_health", severity: "important", clueInStem: "The midwife wants a neonatal abstinence syndrome plan, but Alana says, \"I don't want the baby labelled an addict.\"", whyItMatters: "Missing this signal means the candidate has allowed necessary neonatal planning to become shaming and disengaging.", modelWording: "Coordinate NAS planning with non-stigmatising education because the baby needs monitoring without being labelled an addict.", keywords: ["neonatal abstinence syndrome", "NAS", "paediatrics", "maternity", "postnatal planning", "education"] },
      { id: "s7", name: "Methadone reduction before delivery may destabilise her", category: "substance_use", severity: "critical", clueInStem: "The registrar asks whether methadone should be reduced before delivery to reduce foetal risk.", whyItMatters: "Missing this signal means the candidate has accepted a well-intended but unsafe plan that may increase heroin relapse and foetal instability.", modelWording: "Avoid dose reduction solely to reduce foetal risk because destabilising methadone may cause greater maternal and neonatal harm.", keywords: ["methadone reduction", "foetal risk", "delivery", "relapse", "stabilisation", "NAS"] },
    ],
    priorityOrder: { urgent: ["s1", "s2", "s7"], secondary: ["s3", "s4", "s5", "s6"], lowYield: [] },
    modelAnswer: `Alana's treatment should be framed around stabilisation and harm reduction, not making the pregnancy appear drug-free. She is 30 weeks pregnant and on methadone maintenance treatment, and she says methadone is the only thing stopping her from using heroin. Methadone is therefore protective treatment, not simply a foetal exposure to remove.

The registrar's question about reducing methadone before delivery is important but unsafe if applied simplistically. Reducing the dose solely to reduce foetal risk may destabilise Alana, increase heroin relapse, worsen withdrawal cycling and increase maternal and foetal harm. Neonatal abstinence syndrome planning should occur without undermining opioid substitution treatment.

Alana's fear that child protection will take her baby if they hear about methadone must be addressed transparently. I would explain that methadone treatment can be evidence of engagement, while being honest that risks such as unstable substance use, unsafe caregiving, family violence or inability to meet the baby's needs may require safeguarding involvement.

The engagement pattern should be used constructively. She has missed two antenatal appointments but attends the dosing clinic regularly, so I would coordinate antenatal care around the service she already trusts. The aim is supportive outreach rather than labelling her as non-compliant.

The urine drug screens showing intermittent benzodiazepine and cannabis use require assessment because benzodiazepines with methadone increase sedation, overdose and neonatal risks. Her partner's heroin use and verbal aggression at clinic also require assessment of family violence, coercion, clinic safety and postnatal infant safety.

The midwife's request for a neonatal abstinence syndrome plan is appropriate, but the language must be non-stigmatising. I would explain that the baby is not an addict; the baby may need monitoring, feeding support, soothing strategies and paediatric review after birth. The final plan should coordinate opioid treatment, maternity, paediatrics, social work, addiction medicine and child protection if indicated, while keeping Alana engaged in care.`,
  },
];
